DROP VIEW MCRE_OWN.V_MCRES_CL_RACCORDO_PROD;


CREATE OR REPLACE FORCE VIEW MCRE_OWN.V_MCRES_CL_RACCORDO_PROD
(
   COD_TIPO_SOFFERENZA,
   VAL_DESC_SOFFERENZA,
   COD_FORMA_TECNICA,
   VAL_DESC_FORMA_TECNICA,
   DTA_INS,
   MATRICOLA_INS,
   DTA_ANNULLO,
   MATRICOLA_ANNULLO
)
AS
   SELECT A.COD_TIPO_SOFFERENZA,
          A.VAL_DESC_SOFFERENZA,
          A.COD_FORMA_TECNICA,
          A.VAL_DESC_FORMA_TECNICA,
          A.DTA_INS,
          A.MATRICOLA_INS,
          A.DTA_ANNULLO,
          A.MATRICOLA_ANNULLO
     FROM T_MCRES_CL_RACCORDO_PROD A
          JOIN T_MCRES_CL_PRODOTTI_SOFF B
             ON A.COD_TIPO_SOFFERENZA = B.COD_TIPO_SOFF
    WHERE B.FLG_FILIALE = 'S;


CREATE OR REPLACE SYNONYM MCRE_APP.V_MCRES_CL_RACCORDO_PROD FOR MCRE_OWN.V_MCRES_CL_RACCORDO_PROD;


CREATE OR REPLACE SYNONYM MCRE_USR.V_MCRES_CL_RACCORDO_PROD FOR MCRE_OWN.V_MCRES_CL_RACCORDO_PROD;


GRANT SELECT ON MCRE_OWN.V_MCRES_CL_RACCORDO_PROD TO MCRE_APP;

GRANT SELECT ON MCRE_OWN.V_MCRES_CL_RACCORDO_PROD TO MCRE_USR;
