   

CREATE TABLE MCRE_OWN.T_MCREI_DAY_POSMCI
   (	"ID_DPER" NUMBER, 
	"COD_ABI" VARCHAR2(5 BYTE), 
	"COD_NDG" VARCHAR2(16 BYTE), 
	"ESPOSIZIONE_OGGI" CHAR(1 BYTE), 
	"ESPOSIZIONE_IERI" CHAR(1 BYTE),
	"ID_UTENTE" VARCHAR2(6 BYTE)
   ) ;
   
   GRANT SELECT,UPDATE,INSERT,DELETE ON MCRE_OWN.T_MCREI_DAY_POSMCI TO MCRE_USR;  