CREATE TABLE T_MCRE0_DAY_LIV_CRIT
(
  ID_DPER         VARCHAR2(8 BYTE),
  COD_ABI         VARCHAR2(5 BYTE),
  COD_NDG         VARCHAR2(16 BYTE),
  FL_SEMAFORO     VARCHAR2(1 BYTE),
  NOTE            VARCHAR2(500 BYTE),
  DTA_TIMESTAMP  DATE,
  MATR_AGG        VARCHAR2(10 BYTE)
);

GRANT SELECT,insert,update,delete ON MCRE_OWN.T_MCRE0_DAY_LIV_CRIT TO MCRE_USR;
GRANT SELECT,insert,update,delete ON MCRE_OWN.T_MCRE0_DAY_LIV_CRIT TO MCRE_APP;

