CREATE TABLE MCRE_OWN.T_MCRE0_SC_CONVERT_LGD_GRI(
ID_FLUSSO         NUMBER,
ID_DPER					  VARCHAR2(8 BYTE),
COD_ABI					  VARCHAR2(5 BYTE),
SEGM_ECO					VARCHAR2(2 BYTE),
COD_TIPO_RISK			VARCHAR2(2 BYTE),
TIPO_PROD					VARCHAR2(1 BYTE),
IND_C_F					  VARCHAR2(2 BYTE),
AREA_GEO					VARCHAR2(2 BYTE),
TIPO_LEAS					VARCHAR2(2 BYTE),
TIPO_ESP_FACT			VARCHAR2(2 BYTE),
IND_PRES_ASS			VARCHAR2(2 BYTE),
NAT_GIUR					VARCHAR2(1 BYTE),
FORMA_TEC					VARCHAR2(3 BYTE),
TIPO_GAR					VARCHAR2(2 BYTE),
TPERM_ST_RISK			VARCHAR2(3 BYTE),
SEGNO_ESPOS_CLI		VARCHAR2(1 BYTE),
ESPOS_CLI					VARCHAR2(13 BYTE),
SEGNO_ESPOS_RAPP	VARCHAR2(1 BYTE),
ESPOS_RAPP				VARCHAR2(13 BYTE),
COP_GAR_IMMOB			VARCHAR2(5 BYTE),
PERC_LGD					VARCHAR2(5 BYTE),
TMR_1					    VARCHAR2(3 BYTE),
TMR_2					    VARCHAR2(3 BYTE),
DT_ESTRAZ					VARCHAR2(8 BYTE)
)
TABLESPACE TSD_MCRE_ST_OWN
RESULT_CACHE (MODE DEFAULT);   

CREATE INDEX MCRE_OWN.IX_T_MCRE0_SC_CONV_LGD_GRI_01 ON MCRE_OWN.T_MCRE0_SC_CONVERT_LGD_GRI(ID_FLUSSO) TABLESPACE TSI_MCRE_OWN;
CREATE INDEX MCRE_OWN.IX_T_MCRE0_SC_CONV_LGD_GRI_02 ON MCRE_OWN.T_MCRE0_SC_CONVERT_LGD_GRI(ID_DPER) TABLESPACE TSI_MCRE_OWN;

GRANT SELECT,INSERT,UPDATE,DELETE ON MCRE_OWN.T_MCRE0_SC_CONVERT_LGD_GRI TO MCRE_APP;
GRANT SELECT,INSERT,UPDATE,DELETE ON MCRE_OWN.T_MCRE0_SC_CONVERT_LGD_GRI TO MCRE_USR;

CREATE PUBLIC SYNONYM T_MCRE0_SC_CONVERT_LGD_GRI FOR MCRE_OWN.T_MCRE0_SC_CONVERT_LGD_GRI;