
CREATE TABLE T_MCRE0_LIV_CRIT_DWH_PERCORSI
(
  ID_DPER         VARCHAR2(8 BYTE),
  COD_ABI         VARCHAR2(5 BYTE),
  COD_NDG         VARCHAR2(16 BYTE),
  FL_SEMAFORO     VARCHAR2(1 BYTE),
  NOTE            VARCHAR2(500 BYTE),
  COD_STATO_PRE   VARCHAR2(2 BYTE),
  COD_PROCESSO    VARCHAR2(2 BYTE),
  COD_PERCORSO    NUMBER,
  DTA_SCADENZA    DATE,
  DTA_TIMESTAMP   DATE,
  COD_STATO       VARCHAR2(2 BYTE),
  MATR_AGG        VARCHAR2(10 BYTE)
);

GRANT SELECT,insert,update,delete ON MCRE_OWN.T_MCRE0_LIV_CRIT_DWH_PERCORSI TO MCRE_USR;
GRANT SELECT,insert,update,delete ON MCRE_OWN.T_MCRE0_LIV_CRIT_DWH_PERCORSI TO MCRE_APP;