CREATE TABLE MCRE_OWN.TE_MCREI_LGD_GRI_BAD
(
BAD VARCHAR2(81 BYTE)
) 
ORGANIZATION EXTERNAL 
    ( TYPE ORACLE_LOADER
      DEFAULT DIRECTORY D_MCRE0_BAD
      ACCESS PARAMETERS
      ( RECORDS FIXED 81 CHARACTERSET WE8EBCDIC500
        NOBADFILE
        NODISCARDFILE
        NOLOGFILE
        FIELDS (
                BAD CHAR (81)
               )                                      
      )
      LOCATION
       ( D_MCRE0_BAD:'LGD_GRI.bad')
    )
   REJECT LIMIT UNLIMITED;

GRANT SELECT ON MCRE_OWN.TE_MCREI_LGD_GRI_BAD TO MCRE_APP;
GRANT SELECT ON MCRE_OWN.TE_MCREI_LGD_GRI_BAD TO MCRE_USR;
CREATE PUBLIC SYNONYM TE_MCREI_LGD_GRI_BAD FOR MCRE_OWN.TE_MCREI_LGD_GRI_BAD;
