CREATE TABLE "MCRE_OWN"."TE_MCREI_POSMCI" 
   (	"DATA_FLUSSO" VARCHAR2(8 BYTE), 
      "COD_ABI" VARCHAR2(5 BYTE), 
      "COD_NDG" VARCHAR2(13 BYTE), 
      "ESPOSIZIONE_OGGI" VARCHAR2(1 BYTE), 
      "ESPOSIZIONE_IERI" VARCHAR2(1 BYTE),
      "GESTORE" VARCHAR2(6 BYTE)
   ) 
   ORGANIZATION EXTERNAL 
    ( TYPE ORACLE_LOADER
      DEFAULT DIRECTORY "D_MCRE0_ITT"
      ACCESS PARAMETERS
      ( RECORDS DELIMITED BY NEWLINE 
        STRING SIZES ARE IN BYTES
        BADFILE 'D_MCRE0_BAD':'TE_MCREI_POSMCI.bad'
        NODISCARDFILE
        LOGFILE 'D_MCRE0_LOG':'TE_MCREI_POSMCI.log'
    FIELDS
    MISSING FIELD VALUES ARE NULL(
    "DATA_FLUSSO" POSITION(1:8) CHAR(8),
    "COD_ABI" POSITION(9:13) CHAR(5),
    "COD_NDG" POSITION(14:26) CHAR(13),
    "ESPOSIZIONE_OGGI"POSITION(27:27) CHAR(1),  
    "ESPOSIZIONE_IERI" POSITION(28:28) CHAR(1),
    "GESTORE" POSITION(29:34) CHAR(6) 
    )
        )
      LOCATION
       ( "D_MCRE0_ITT":'POSMCI')
    )
   REJECT LIMIT UNLIMITED ;

GRANT SELECT ON MCRE_OWN.TE_MCREI_POSMCI TO MCRE_USR;