
CREATE TABLE TE_MCRE0_LIV_CRIT
(
  ID_DPER         VARCHAR2(8 BYTE),
  COD_ABI         VARCHAR2(5 BYTE),
  COD_NDG         VARCHAR2(16 BYTE),
  FL_SEMAFORO     VARCHAR2(1 BYTE),
  NOTE            VARCHAR2(500 BYTE),
  DTA_TIMESTAMP   VARCHAR2(19 BYTE),
  MATR_AGG        VARCHAR2(10 BYTE)
)ORGANIZATION EXTERNAL 
    ( TYPE ORACLE_LOADER
      DEFAULT DIRECTORY D_MCRE0_ITT
      ACCESS PARAMETERS
      ( RECORDS DELIMITED BY NEWLINE CHARACTERSET UTF8
        STRING SIZES ARE IN BYTES
        BADFILE 'D_MCRE0_BAD':'TE_MCRE0_LIV_CRIT.bad'
        NODISCARDFILE
        LOGFILE 'D_MCRE0_LOG':'TE_MCRE0_LIV_CRIT.log'
    FIELDS
    MISSING FIELD VALUES ARE NULL(
    ID_DPER POSITION(1:8) CHAR(8),
    COD_ABI POSITION(9:13) CHAR(5),
    COD_NDG POSITION(14:29) CHAR(16),
    FL_SEMAFORO POSITION(30:30) CHAR(1),  
    NOTE POSITION(31:530) CHAR(500),
    DTA_TIMESTAMP POSITION(531:549) char(19),
    MATR_AGG POSITION(550:559) char(10)
    )
        )
      LOCATION
       ( D_MCRE0_ITT:'LIVCRITMCRE0')
    )
   REJECT LIMIT UNLIMITED ;

GRANT SELECT ON MCRE_OWN.TE_MCRE0_LIV_CRIT TO MCRE_USR;