
CREATE TABLE TE_MCRE0_LIV_CRIT_ST_PERCORSI
(
  ID_DPER         VARCHAR2(8 BYTE),
  COD_ABI         VARCHAR2(5 BYTE),
  COD_NDG         VARCHAR2(16 BYTE),
  FL_SEMAFORO     VARCHAR2(1 BYTE),
  NOTE            VARCHAR2(500 BYTE),
  COD_STATO_PRE   VARCHAR2(2 BYTE),
  COD_PROCESSO    VARCHAR2(2 BYTE),
  COD_PERCORSO    VARCHAR2(3 BYTE),
  DTA_SCADENZA    VARCHAR2(19 BYTE),
  DTA_TIMESTAMP   VARCHAR2(19 BYTE),
  COD_STATO       VARCHAR2(2 BYTE),
  MATR_AGG        VARCHAR2(10 BYTE)
)ORGANIZATION EXTERNAL 
    ( TYPE ORACLE_LOADER
      DEFAULT DIRECTORY D_MCRE0_ITT
      ACCESS PARAMETERS
      ( RECORDS DELIMITED BY NEWLINE CHARACTERSET UTF8 
        STRING SIZES ARE IN BYTES
        BADFILE 'D_MCRE0_BAD':'TE_MCRE0_LIV_CRIT_ST_PERCORSI.bad'
        NODISCARDFILE
        LOGFILE 'D_MCRE0_LOG':'TE_MCRE0_LIV_CRIT_ST_PERCORSI.log'
    FIELDS
    MISSING FIELD VALUES ARE NULL(
    ID_DPER POSITION(1:8) CHAR(8),
    COD_ABI POSITION(9:13) CHAR(5),
    COD_NDG POSITION(14:29) CHAR(16),
    FL_SEMAFORO POSITION(30:30) CHAR(1),  
    NOTE POSITION(31:530) CHAR(500),
    COD_STATO_PRE POSITION(531:532) CHAR(2),
    COD_PROCESSO POSITION(533:534) CHAR(2),
    COD_PERCORSO POSITION(535:537)  CHAR(3),
    DTA_SCADENZA POSITION(538:556)  CHAR(19),
    DTA_TIMESTAMP POSITION(557:575)  CHAR(19),
    COD_STATO POSITION(576:577) char(2),
    MATR_AGG POSITION(578:587) char(10)
    )
        )
      LOCATION
       ( D_MCRE0_ITT:'LIVSTPER')
    )
   REJECT LIMIT UNLIMITED ;

GRANT SELECT ON MCRE_OWN.TE_MCRE0_LIV_CRIT_ST_PERCORSI TO MCRE_USR;