CREATE TABLE MCRE_OWN.TE_MCRE0_LIV_CRIT_DT
   (	PERIODO_RIF VARCHAR2(8 BYTE)
   ) 
   ORGANIZATION EXTERNAL 
    ( TYPE ORACLE_LOADER
      DEFAULT DIRECTORY D_MCRE0_ITT
      ACCESS PARAMETERS
      ( RECORDS DELIMITED BY NEWLINE 
        STRING SIZES ARE IN BYTES
        BADFILE 'D_MCRE0_BAD':'TE_MCRE0_LIV_CRIT_DT.bad'
        NODISCARDFILE
        LOGFILE 'D_MCRE0_LOG':'TE_MCRE0_LIV_CRIT_DT.log'
    FIELDS
    MISSING FIELD VALUES ARE NULL(
    PERIODO_RIF POSITION(1:8) CHAR(8),
     FILLER POSITION(9:559) CHAR(6) 
    )
        )
      LOCATION
       ( D_MCRE0_ITT:'LIVCRITMCRE0')
    )
   REJECT LIMIT UNLIMITED ;

GRANT SELECT ON MCRE_OWN.TE_MCRE0_LIV_CRIT_DT TO MCRE_USR;