/* Formatted on 17/06/2014 17:59:22 (QP5 v5.227.12220.39754) */
CREATE OR REPLACE FORCE VIEW MCRE_OWN.T_MCRE0_APP_ISTITUTI
(
   COD_ISTITUTO,
   COD_ABI,
   DESC_ISTITUTO,
   DESC_BREVE,
   COD_ISTITUTO_SOA,
   COD_ABI_VISUALIZZATO,
   FLG_OUTSOURCING,
   FLG_TARGET,
   FLG_CARTOLARIZZATO,
   FLG_CHIUSURA_MANCATO_AGG,
   FLG_SEGREGATO,
   COD_ABI_ISTITUTO,
   FLG_CCP,
   FLG_SOFF,
   FLG_TIPO_ABI
)
AS
   SELECT "COD_ISTITUTO",
          "COD_ABI",
          "DESC_ISTITUTO",
          "DESC_BREVE",
          "COD_ISTITUTO_SOA",
          "COD_ABI_VISUALIZZATO",
          "FLG_OUTSOURCING",
          "FLG_TARGET",
          "FLG_CARTOLARIZZATO",
          "FLG_CHIUSURA_MANCATO_AGG",
          "FLG_SEGREGATO",
          "COD_ABI_ISTITUTO",
          "FLG_CCP",
          "FLG_SOFF",
          "FLG_TIPO_ABI"
     FROM T_MCRE0_APP_ISTITUTI_ALL
    WHERE FLG_CCP = 1;


GRANT DELETE, INSERT, REFERENCES, SELECT, UPDATE, ON COMMIT REFRESH, QUERY REWRITE, DEBUG, FLASHBACK, MERGE VIEW ON MCRE_OWN.T_MCRE0_APP_ISTITUTI TO MCRE_USR;
