/* Formatted on 17/06/2014 18:05:33 (QP5 v5.227.12220.39754) */
CREATE OR REPLACE FORCE VIEW MCRE_OWN.V_MCRE0_PCR_GB
(
   ID_DPER_GB,
   FLG_LAST_RUN,
   TODAY_FLG,
   COD_ABI_ISTITUTO,
   COD_ABI_CARTOLARIZZATO,
   COD_NDG,
   COD_SNDG,
   FLG_SNDG_GE,
   ID_DPER,
   FLG_GRUPPO_ECONOMICO,
   COD_GRUPPO_ECONOMICO,
   FLG_GRUPPO_LEGAME,
   GB_DTA_RIFERIMENTO,
   GEGB_TOT_GAR,
   SCGB_TOT_GAR,
   GLGB_TOT_GAR,
   SCGB_ACC_CONSEGNE,
   SCGB_ACC_CONSEGNE_DT,
   SCGB_UTI_CONSEGNE,
   SCGB_UTI_CONSEGNE_DT,
   GEGB_ACC_CONSEGNE,
   GEGB_ACC_CONSEGNE_DT,
   GEGB_UTI_CONSEGNE,
   GEGB_UTI_CONSEGNE_DT,
   GLGB_ACC_CONSEGNE,
   GLGB_ACC_CONSEGNE_DT,
   GLGB_UTI_CONSEGNE,
   GLGB_UTI_CONSEGNE_DT,
   SCGB_UTI_MASSIMALI,
   SCGB_UTI_SOSTITUZIONI,
   SCGB_UTI_RISCHI_INDIRETTI,
   SCGB_UTI_MASSIMALI_DT,
   SCGB_UTI_SOSTITUZIONI_DT,
   SCGB_UTI_RISCHI_INDIRETTI_DT,
   SCGB_ACC_MASSIMALI,
   SCGB_ACC_SOSTITUZIONI,
   SCGB_ACC_RISCHI_INDIRETTI,
   SCGB_ACC_MASSIMALI_DT,
   SCGB_ACC_SOSTITUZIONI_DT,
   SCGB_ACC_RISCHI_INDIRETTI_DT,
   GEGB_UTI_MASSIMALI,
   GEGB_UTI_SOSTITUZIONI,
   GEGB_UTI_RISCHI_INDIRETTI,
   GEGB_UTI_MASSIMALI_DT,
   GEGB_UTI_SOSTITUZIONI_DT,
   GEGB_UTI_RISCHI_INDIRETTI_DT,
   GEGB_ACC_MASSIMALI,
   GEGB_ACC_SOSTITUZIONI,
   GEGB_ACC_RISCHI_INDIRETTI,
   GEGB_ACC_MASSIMALI_DT,
   GEGB_ACC_SOSTITUZIONI_DT,
   GEGB_ACC_RISCHI_INDIRETTI_DT,
   GLGB_UTI_MASSIMALI,
   GLGB_UTI_SOSTITUZIONI,
   GLGB_UTI_RISCHI_INDIRETTI,
   GLGB_UTI_MASSIMALI_DT,
   GLGB_UTI_SOSTITUZIONI_DT,
   GLGB_UTI_RISCHI_INDIRETTI_DT,
   GLGB_ACC_MASSIMALI,
   GLGB_ACC_SOSTITUZIONI,
   GLGB_ACC_RISCHI_INDIRETTI,
   GLGB_ACC_MASSIMALI_DT,
   GLGB_ACC_SOSTITUZIONI_DT,
   GLGB_ACC_RISCHI_INDIRETTI_DT,
   SCGB_UTI_CASSA,
   SCGB_UTI_FIRMA,
   SCGB_ACC_CASSA,
   SCGB_ACC_FIRMA,
   SCGB_UTI_CASSA_BT,
   SCGB_UTI_CASSA_MLT,
   SCGB_UTI_SMOBILIZZO,
   SCGB_UTI_FIRMA_DT,
   SCGB_ACC_CASSA_BT,
   SCGB_ACC_CASSA_MLT,
   SCGB_ACC_SMOBILIZZO,
   SCGB_ACC_FIRMA_DT,
   GEGB_UTI_CASSA,
   GEGB_UTI_FIRMA,
   GEGB_ACC_CASSA,
   GEGB_ACC_FIRMA,
   GEGB_UTI_CASSA_BT,
   GEGB_UTI_CASSA_MLT,
   GEGB_UTI_SMOBILIZZO,
   GEGB_UTI_FIRMA_DT,
   GEGB_ACC_CASSA_BT,
   GEGB_ACC_CASSA_MLT,
   GEGB_ACC_SMOBILIZZO,
   GEGB_ACC_FIRMA_DT,
   GLGB_UTI_CASSA,
   GLGB_UTI_FIRMA,
   GLGB_ACC_CASSA,
   GLGB_ACC_FIRMA,
   GLGB_UTI_CASSA_BT,
   GLGB_UTI_CASSA_MLT,
   GLGB_UTI_SMOBILIZZO,
   GLGB_UTI_FIRMA_DT,
   GLGB_ACC_CASSA_BT,
   GLGB_ACC_CASSA_MLT,
   GLGB_ACC_SMOBILIZZO,
   GLGB_ACC_FIRMA_DT,
   GEGB_UTI_TOT,
   GEGB_ACC_TOT,
   GLGB_UTI_TOT,
   GLGB_ACC_TOT,
   SCGB_UTI_TOT,
   SCGB_ACC_TOT,
   GEGB_MAU,
   GLGB_MAU,
   SCGB_MAU,
   DTA_INS,
   DTA_UPD,
   MY_RNK
)
AS
   SELECT gb.id_dper id_dper_gb,
          flg_last_run,
          NVL (
             (SELECT '1'
                FROM t_mcre0_day_mopl t
               WHERE     t.cod_abi_cartolarizzato = f.cod_abi_cartolarizzato
                     AND t.cod_ndg = f.cod_ndg),
             '0')
             today_flg,
          f.cod_abi_istituto,
          f.cod_abi_cartolarizzato,
          f.cod_ndg,
          f.cod_sndg,
          NULL flg_sndg_ge,                                    --nolonger used
          f.id_dper,
          CASE
             WHEN NVL (f.cod_gruppo_economico, '-1') = '-1' THEN 0
             ELSE 1
          END
             flg_gruppo_economico, --nvl( (select  decode (ge.cod_gruppo_economico, null, '0', '1')  from mcre_own.t_mcre0_app_gruppo_economico ge where f.cod_sndg = ge.cod_sndg(+) ),'0') flg_gruppo_economico,
          f.cod_gruppo_economico, --(select  ge.cod_gruppo_economico from mcre_own.t_mcre0_app_gruppo_economico ge where f.cod_sndg = ge.cod_sndg(+) ) cod_gruppo_economico,
          CASE WHEN NVL (f.cod_gruppo_legame, '-1') = '-1' THEN 0 ELSE 1 END
             flg_gruppo_legame, --nvl( (select decode (cod_gruppo_legame, null, '0', '1') from mcre_own.t_mcre0_app_gruppo_legame gl where  f.cod_sndg = gl.cod_sndg(+)),'0') flg_gruppo_legame,
          DTA_RIFERIMENTO gb_dta_riferimento,
          gegb_tot_gar,
          scgb_tot_gar,
          glgb_tot_gar,
          scgb_acc_consegne,
          scgb_acc_consegne_dt,
          scgb_uti_consegne,
          scgb_uti_consegne_dt,
          gegb_acc_consegne,
          gegb_acc_consegne_dt,
          gegb_uti_consegne,
          gegb_uti_consegne_dt,
          glgb_acc_consegne,
          glgb_acc_consegne_dt,
          glgb_uti_consegne,
          glgb_uti_consegne_dt,
          scgb_uti_massimali,
          scgb_uti_sostituzioni,
          scgb_uti_rischi_indiretti,
          scgb_uti_massimali_dt,
          scgb_uti_sostituzioni_dt,
          scgb_uti_rischi_indiretti_dt,
          scgb_acc_massimali,
          scgb_acc_sostituzioni,
          scgb_acc_rischi_indiretti,
          scgb_acc_massimali_dt,
          scgb_acc_sostituzioni_dt,
          scgb_acc_rischi_indiretti_dt,
          gegb_uti_massimali,
          gegb_uti_sostituzioni,
          gegb_uti_rischi_indiretti,
          gegb_uti_massimali_dt,
          gegb_uti_sostituzioni_dt,
          gegb_uti_rischi_indiretti_dt,
          gegb_acc_massimali,
          gegb_acc_sostituzioni,
          gegb_acc_rischi_indiretti,
          gegb_acc_massimali_dt,
          gegb_acc_sostituzioni_dt,
          gegb_acc_rischi_indiretti_dt,
          glgb_uti_massimali,
          glgb_uti_sostituzioni,
          glgb_uti_rischi_indiretti,
          glgb_uti_massimali_dt,
          glgb_uti_sostituzioni_dt,
          glgb_uti_rischi_indiretti_dt,
          glgb_acc_massimali,
          glgb_acc_sostituzioni,
          glgb_acc_rischi_indiretti,
          glgb_acc_massimali_dt,
          glgb_acc_sostituzioni_dt,
          glgb_acc_rischi_indiretti_dt,
          scgb_uti_cassa,
          scgb_uti_firma,
          scgb_acc_cassa,
          scgb_acc_firma,
          scgb_uti_cassa_bt,
          scgb_uti_cassa_mlt,
          scgb_uti_smobilizzo,
          scgb_uti_firma_dt,
          scgb_acc_cassa_bt,
          scgb_acc_cassa_mlt,
          scgb_acc_smobilizzo,
          scgb_acc_firma_dt,
          gegb_uti_cassa,
          gegb_uti_firma,
          gegb_acc_cassa,
          gegb_acc_firma,
          gegb_uti_cassa_bt,
          gegb_uti_cassa_mlt,
          gegb_uti_smobilizzo,
          gegb_uti_firma_dt,
          gegb_acc_cassa_bt,
          gegb_acc_cassa_mlt,
          gegb_acc_smobilizzo,
          gegb_acc_firma_dt,
          glgb_uti_cassa,
          glgb_uti_firma,
          glgb_acc_cassa,
          glgb_acc_firma,
          glgb_uti_cassa_bt,
          glgb_uti_cassa_mlt,
          glgb_uti_smobilizzo,
          glgb_uti_firma_dt,
          glgb_acc_cassa_bt,
          glgb_acc_cassa_mlt,
          glgb_acc_smobilizzo,
          glgb_acc_firma_dt,
          gegb_uti_cassa + gegb_uti_firma gegb_uti_tot,
          gegb_acc_cassa + gegb_acc_firma gegb_acc_tot,
          glgb_uti_cassa + glgb_uti_firma glgb_uti_tot,
          glgb_acc_cassa + glgb_acc_firma glgb_acc_tot,
          scgb_uti_cassa + scgb_uti_firma scgb_uti_tot,
          scgb_acc_cassa + scgb_acc_firma scgb_acc_tot,
          /* nuovo mau*/
          DECODE (
             SIGN (
                  (gegb_uti_cassa + gegb_uti_firma + gegb_uti_sostituzioni)
                - (gegb_acc_cassa + gegb_acc_firma + gegb_acc_sostituzioni)),
             -1, (gegb_acc_cassa + gegb_acc_firma + gegb_acc_sostituzioni),
             (gegb_uti_cassa + gegb_uti_firma + gegb_uti_sostituzioni))
             gegb_mau,
          DECODE (
             SIGN (
                  (glgb_uti_cassa + glgb_uti_firma + glgb_uti_sostituzioni)
                - (glgb_acc_cassa + glgb_acc_firma + glgb_acc_sostituzioni)),
             -1, (glgb_acc_cassa + glgb_acc_firma + glgb_acc_sostituzioni),
             (glgb_uti_cassa + glgb_uti_firma + glgb_uti_sostituzioni))
             glgb_mau,
          DECODE (
             SIGN (
                  (scgb_uti_cassa + scgb_uti_firma + scgb_uti_sostituzioni)
                - (scgb_acc_cassa + scgb_acc_firma + scgb_acc_sostituzioni)),
             -1, (scgb_acc_cassa + scgb_acc_firma + scgb_acc_sostituzioni),
             (scgb_uti_cassa + scgb_uti_firma + scgb_uti_sostituzioni))
             scgb_mau,
          gb.DTA_INS,
          gb.DTA_UPD,
          1 my_rnk
     FROM t_mcre0_day_fg f,
          (SELECT * FROM ttmcre0_pcr_gb1
           UNION ALL
           SELECT * FROM ttmcre0_pcr_gb2) gb
    WHERE f.cod_sndg = gb.cod_sndg;


GRANT SELECT ON MCRE_OWN.V_MCRE0_PCR_GB TO MCRE_USR;
