/* Formatted on 17/06/2014 18:12:00 (QP5 v5.227.12220.39754) */
CREATE OR REPLACE FORCE VIEW MCRE_OWN.V_MCRES_CL_CAUSALI_MO
(
   COD_CAUSALE,
   VAL_DESCRIZIONE
)
AS
   SELECT COD_CAUSALE, VAL_DESCRIZIONE
     FROM T_MCRES_CL_CAUSALI_MO
    WHERE FLG_MOV_PROP_FILIALE = 'S';


GRANT SELECT ON MCRE_OWN.V_MCRES_CL_CAUSALI_MO TO MCRE_USR;
