/* Formatted on 17/06/2014 18:12:02 (QP5 v5.227.12220.39754) */
CREATE OR REPLACE FORCE VIEW MCRE_OWN.V_MCRES_CL_FORME_TECNICHE
(
   COD_FORMA_TECNICA,
   VAL_DESC_FORMA_TECNICA,
   DTA_INS,
   MATRICOLA_INS
)
AS
   SELECT COD_FORMA_TECNICA,
          VAL_DESC_FORMA_TECNICA,
          DTA_INS,
          MATRICOLA_INS
     FROM T_MCRES_CL_FORME_TECNICHE;


GRANT SELECT ON MCRE_OWN.V_MCRES_CL_FORME_TECNICHE TO MCRE_USR;
