/* Formatted on 17/06/2014 18:11:23 (QP5 v5.227.12220.39754) */
CREATE OR REPLACE FORCE VIEW MCRE_OWN.V_MCRES_APP_SISBA_LAST
(
   COD_ABI,
   COD_NDG,
   COD_RAPPORTO,
   COD_FILIALE_RAPPORTO,
   DTA_RIF_SISBA,
   VAL_VOCE_1495,
   VAL_VOCE_1637,
   VAL_VOCE_2150,
   VAL_VOCE_2187,
   VAL_VOCE_8573,
   VAL_VOCE_8574,
   VAL_IMP_UTI_RETTIFICATO,
   VAL_IMP_CREDITO_VANTATO,
   VAL_IMP_PREV_PERDITA_ANALITICA,
   VAL_IMP_PREV_PERDITA_AN_CAP,
   VAL_IMP_PREV_PERDITA_CR_PREC,
   VAL_IMP_PREV_PERDITA_DELTA_ATT,
   VAL_IMP_RATEI_PER_SOFF_MORA
)
AS
     SELECT                                      -- VG 20140220 unico rapporto
           COD_ABI,
            COD_NDG,
            COD_RAPPORTO,
            COD_FILIALE_RAPPORTO,
            DTA_RIF_SISBA,
            SUM (VAL_VOCE_1495) VAL_VOCE_1495,
            SUM (VAL_VOCE_1637) VAL_VOCE_1637,
            SUM (VAL_VOCE_2150) VAL_VOCE_2150,
            SUM (VAL_VOCE_2187) VAL_VOCE_2187,
            SUM (VAL_VOCE_8573) VAL_VOCE_8573,
            SUM (VAL_VOCE_8574) VAL_VOCE_8574,
            SUM (VAL_IMP_UTI_RETTIFICATO) VAL_IMP_UTI_RETTIFICATO,
            SUM (VAL_IMP_CREDITO_VANTATO) VAL_IMP_CREDITO_VANTATO,
            SUM (VAL_IMP_PREV_PERDITA_ANALITICA) VAL_IMP_PREV_PERDITA_ANALITICA,
            SUM (VAL_IMP_PREV_PERDITA_AN_CAP) VAL_IMP_PREV_PERDITA_AN_CAP,
            SUM (VAL_IMP_PREV_PERDITA_CR_PREC) VAL_IMP_PREV_PERDITA_CR_PREC,
            SUM (VAL_IMP_PREV_PERDITA_DELTA_ATT) VAL_IMP_PREV_PERDITA_DELTA_ATT,
            SUM (VAL_IMP_RATEI_PER_SOFF_MORA) VAL_IMP_RATEI_PER_SOFF_MORA
       FROM t_mcres_app_sisba
      WHERE     id_dper = (SELECT id_dper
                             FROM V_MCRES_ULTIMA_ACQUISIZIONE
                            WHERE cod_flusso = 'SISBA')
            AND COD_FTECNICA != 'PD390'
   GROUP BY COD_ABI,
            COD_NDG,
            COD_RAPPORTO,
            COD_FILIALE_RAPPORTO,
            DTA_RIF_SISBA;


GRANT SELECT ON MCRE_OWN.V_MCRES_APP_SISBA_LAST TO MCRE_USR;
