/* Formatted on 17/06/2014 18:07:27 (QP5 v5.227.12220.39754) */
CREATE OR REPLACE FORCE VIEW MCRE_OWN.V_MCREI_APP_COINTESTATARI_PROP
(
   COD_ABI,
   COD_NDG,
   COD_SNDG,
   COD_SNDG_COINT,
   COD_ABI_COINT,
   COD_NDG_COINT,
   DESC_NOME_CONTROPARTE,
   COD_TIPO_LEGAME,
   COD_PROTOCOLLO_DELIBERA
)
AS
   SELECT cod_abi,
          cod_ndg,
          cod_sndg,
          COD_SNDG_COINTestatario COD_SNDG_COINT,
          COD_ABI_COINTESTATARIO COD_ABI_COINT,
          COD_NDG_COINTESTATARIO COD_NDG_COINT,
          DESC_NOME_CONTROPARTE,
          'GCO' COD_TIPO_LEGAME,
          COD_PROTOCOLLO_DELIBERA
     FROM T_MCREI_APP_COINTEST_PROP;


GRANT DELETE, INSERT, REFERENCES, SELECT, UPDATE, ON COMMIT REFRESH, QUERY REWRITE, DEBUG, FLASHBACK, MERGE VIEW ON MCRE_OWN.V_MCREI_APP_COINTESTATARI_PROP TO MCRE_USR;
