/* Formatted on 17/06/2014 18:02:35 (QP5 v5.227.12220.39754) */
CREATE OR REPLACE FORCE VIEW MCRE_OWN.V_MCRE0_APP_PT_POS_ANZIANITA
(
   COD_COMPARTO,
   COD_ABI_CARTOLARIZZATO,
   COD_ABI_ISTITUTO,
   ID_UTENTE,
   ID_REFERENTE,
   VAL_ORDINE,
   DESC_PERIODO,
   VAL_NUM_POS,
   SCSB_UTI_TOT,
   SCSB_UTI_CASSA,
   SCSB_UTI_FIRMA,
   COD_STRUTTURA_COMPETENTE_DC,
   DESC_STRUTTURA_COMPETENTE_DC,
   COD_STRUTTURA_COMPETENTE_DV,
   DESC_STRUTTURA_COMPETENTE_DV,
   COD_STRUTTURA_COMPETENTE_AR,
   DESC_STRUTTURA_COMPETENTE_AR,
   COD_STRUTTURA_COMPETENTE_FI,
   DESC_STRUTTURA_COMPETENTE_FI,
   COD_STRUTTURA_COMPETENTE_RG,
   DESC_STRUTTURA_COMPETENTE_RG,
   COD_LIVELLO
)
AS
     SELECT                                       -- v1 17/06/2011 VG: New PCR
           cod_comparto,
            cod_abi_cartolarizzato,
            cod_abi_istituto,
            id_utente,
            id_referente,
            val_ordine,
            desc_periodo,
            SUM (val_num_pos) val_num_pos,
            SUM (scsb_uti_tot) scsb_uti_tot,
            SUM (scsb_uti_cassa) scsb_uti_cassa,
            SUM (scsb_uti_firma) scsb_uti_firma,
            cod_struttura_competente_dc,
            desc_struttura_competente_dc,
            cod_struttura_competente_dv,
            desc_struttura_competente_dv,
            cod_struttura_competente_ar,
            desc_struttura_competente_ar,
            cod_struttura_competente_fi,
            desc_struttura_competente_fi,
            cod_struttura_competente_rg,
            desc_struttura_competente_rg,
            cod_livello
       FROM (  SELECT cod_comparto,
                      cod_abi_cartolarizzato,
                      cod_abi_istituto,
                      id_utente,
                      id_referente,
                      val_ordine,
                      DECODE (val_ordine,
                              1, '<=30 giorni',
                              2, '31-60 giorni',
                              3, '61-90 giorni',
                              '>90 giorni')
                         desc_periodo,
                      COUNT (*) val_num_pos,
                      SUM (scsb_uti_tot) scsb_uti_tot,
                      SUM (scsb_uti_cassa) scsb_uti_cassa,
                      SUM (scsb_uti_firma) scsb_uti_firma,
                      cod_struttura_competente_dc,
                      desc_struttura_competente_dc,
                      cod_struttura_competente_dv,
                      desc_struttura_competente_dv,
                      cod_struttura_competente_ar,
                      desc_struttura_competente_ar,
                      cod_struttura_competente_fi,
                      desc_struttura_competente_fi,
                      cod_struttura_competente_rg,
                      desc_struttura_competente_rg,
                      cod_livello
                 FROM (SELECT x.cod_comparto,
                              x.id_utente,
                              x.id_referente,
                              x.cod_abi_cartolarizzato,
                              x.cod_abi_istituto,
                              x.cod_ndg,
                              DECODE (
                                 SIGN (
                                    TRUNC (SYSDATE) - x.dta_decorrenza_stato - 31),
                                 -1, 1,
                                 DECODE (
                                    SIGN (
                                         TRUNC (SYSDATE)
                                       - x.dta_decorrenza_stato
                                       - 61),
                                    -1, 2,
                                    DECODE (
                                       SIGN (
                                            TRUNC (SYSDATE)
                                          - x.dta_decorrenza_stato
                                          - 91),
                                       -1, 3,
                                       4)))
                                 val_ordine,
                              p.scsb_uti_tot,
                              p.scsb_uti_cassa,
                              p.scsb_uti_firma,
                              x.cod_struttura_competente_dc,
                              x.desc_struttura_competente_dc,
                              x.cod_struttura_competente_dv,
                              x.desc_struttura_competente_dv,
                              x.cod_struttura_competente_ar,
                              x.desc_struttura_competente_ar,
                              x.cod_struttura_competente_fi,
                              x.desc_struttura_competente_fi,
                              cod_struttura_competente_rg,
                              desc_struttura_competente_rg,
                              x.cod_livello
                         FROM v_mcre0_app_upd_fields x, --T_MCRE0_APP_UTENTI U,
                                                       t_mcre0_app_pcr p
                        --MV_MCRE0_DENORM_STR_ORG S
                        WHERE     x.cod_stato = 'PT'
                              AND NVL (x.flg_outsourcing, 'N') = 'Y'
                              AND x.cod_abi_cartolarizzato =
                                     p.cod_abi_cartolarizzato(+)
                              AND x.cod_ndg = p.cod_ndg(+) --                        AND X.ID_UTENTE = U.ID_UTENTE(+)
  --                         AND X.COD_ABI_ISTITUTO = S.COD_ABI_ISTITUTO_FI(+)
 --                         AND X.COD_FILIALE = S.COD_STRUTTURA_COMPETENTE_FI(+)
                      )
             GROUP BY cod_comparto,
                      cod_abi_cartolarizzato,
                      cod_abi_istituto,
                      id_utente,
                      id_referente,
                      val_ordine,
                      cod_struttura_competente_dc,
                      desc_struttura_competente_dc,
                      cod_struttura_competente_dv,
                      desc_struttura_competente_dv,
                      cod_struttura_competente_ar,
                      desc_struttura_competente_ar,
                      cod_struttura_competente_fi,
                      desc_struttura_competente_fi,
                      cod_struttura_competente_rg,
                      desc_struttura_competente_rg,
                      cod_livello
             UNION ALL
             SELECT NULL cod_comparto,
                    NULL cod_abi_cartolarizzato,
                    NULL cod_abi_istituto,
                    NULL id_utente,
                    NULL id_referente,
                    1 val_ordine,
                    '<=30 giorni' desc_periodo,
                    0 val_num_pos,
                    0 scsb_uti_tot,
                    0 scsb_uti_cassa,
                    0 scsb_uti_firma,
                    NULL cod_struttura_competente_dc,
                    NULL desc_struttura_competente_dc,
                    NULL cod_struttura_competente_dv,
                    NULL desc_struttura_competente_dv,
                    NULL cod_struttura_competente_ar,
                    NULL desc_struttura_competente_ar,
                    NULL cod_struttura_competente_fi,
                    NULL desc_struttura_competente_fi,
                    NULL cod_struttura_competente_rg,
                    NULL desc_struttura_competente_rg,
                    NULL AS cod_livello
               FROM DUAL
             UNION ALL
             SELECT NULL cod_comparto,
                    NULL cod_abi_cartolarizzato,
                    NULL cod_abi_istituto,
                    NULL id_utente,
                    NULL id_referente,
                    2 val_ordine,
                    '31-60 giorni' desc_periodo,
                    0 val_num_pos,
                    0 scsb_uti_tot,
                    0 scsb_uti_cassa,
                    0 scsb_uti_firma,
                    NULL cod_struttura_competente_dc,
                    NULL desc_struttura_competente_dc,
                    NULL cod_struttura_competente_dv,
                    NULL desc_struttura_competente_dv,
                    NULL cod_struttura_competente_ar,
                    NULL desc_struttura_competente_ar,
                    NULL cod_struttura_competente_fi,
                    NULL desc_struttura_competente_fi,
                    NULL cod_struttura_competente_rg,
                    NULL desc_struttura_competente_rg,
                    NULL AS cod_livello
               FROM DUAL
             UNION ALL
             SELECT NULL cod_comparto,
                    NULL cod_abi_cartolarizzato,
                    NULL cod_abi_istituto,
                    NULL id_utente,
                    NULL id_referente,
                    3 val_ordine,
                    '61-90 giorni' desc_periodo,
                    0 val_num_pos,
                    0 scsb_uti_tot,
                    0 scsb_uti_cassa,
                    0 scsb_uti_firma,
                    NULL cod_struttura_competente_dc,
                    NULL desc_struttura_competente_dc,
                    NULL cod_struttura_competente_dv,
                    NULL desc_struttura_competente_dv,
                    NULL cod_struttura_competente_ar,
                    NULL desc_struttura_competente_ar,
                    NULL cod_struttura_competente_fi,
                    NULL desc_struttura_competente_fi,
                    NULL cod_struttura_competente_rg,
                    NULL desc_struttura_competente_rg,
                    NULL AS cod_livello
               FROM DUAL
             UNION ALL
             SELECT NULL cod_comparto,
                    NULL cod_abi_cartolarizzato,
                    NULL cod_abi_istituto,
                    NULL id_utente,
                    NULL id_referente,
                    4 val_ordine,
                    '>90 giorni' desc_periodo,
                    0 val_num_pos,
                    0 scsb_uti_tot,
                    0 scsb_uti_cassa,
                    0 scsb_uti_firma,
                    NULL cod_struttura_competente_dc,
                    NULL desc_struttura_competente_dc,
                    NULL cod_struttura_competente_dv,
                    NULL desc_struttura_competente_dv,
                    NULL cod_struttura_competente_ar,
                    NULL desc_struttura_competente_ar,
                    NULL cod_struttura_competente_fi,
                    NULL desc_struttura_competente_fi,
                    NULL cod_struttura_competente_rg,
                    NULL desc_struttura_competente_rg,
                    NULL AS cod_livello
               FROM DUAL)
   GROUP BY cod_comparto,
            cod_abi_cartolarizzato,
            cod_abi_istituto,
            id_utente,
            id_referente,
            val_ordine,
            desc_periodo,
            cod_struttura_competente_dc,
            desc_struttura_competente_dc,
            cod_struttura_competente_dv,
            desc_struttura_competente_dv,
            cod_struttura_competente_ar,
            desc_struttura_competente_ar,
            cod_struttura_competente_fi,
            desc_struttura_competente_fi,
            cod_struttura_competente_rg,
            desc_struttura_competente_rg,
            cod_livello;


GRANT SELECT ON MCRE_OWN.V_MCRE0_APP_PT_POS_ANZIANITA TO MCRE_USR;
