/* Formatted on 17/06/2014 18:09:06 (QP5 v5.227.12220.39754) */
CREATE OR REPLACE FORCE VIEW MCRE_OWN.V_MCREI_RWA_PACCHETTO
(
   COD_PROTOCOLLO_PACCHETTO,
   COD_BS,
   TICKET_ID,
   RWA_TICKET_ID,
   FLG_VALIDITA,
   DTA_INS,
   DTA_UPD
)
AS
   SELECT COD_PROTOCOLLO_PACCHETTO,
          COD_BS,
          TICKET_ID,
          RWA_TICKET_ID,
          FLG_VALIDITA,
          DTA_INS,
          DTA_UPD
     FROM T_MCREI_RWA_PACCHETTO;


GRANT SELECT ON MCRE_OWN.V_MCREI_RWA_PACCHETTO TO MCRE_USR;
