/* Formatted on 17/06/2014 18:02:33 (QP5 v5.227.12220.39754) */
CREATE OR REPLACE FORCE VIEW MCRE_OWN.V_MCRE0_APP_PT_PIANI_COMPL
(
   COD_ABI_CARTOLARIZZATO,
   COD_NDG,
   FLG_PIANO,
   FLG_WORKFLOW,
   DTA_PIANO,
   DTA_TAVOLO,
   DTA_TAVOLO_ORIG,
   DTA_FORZATURA_PIANO,
   DTA_PIANO_CONFERMA_FILIALE,
   DTA_PIANO_CONFERMA_AREA,
   DESC_NOME_CONTROPARTE,
   COD_GRUPPO_ECONOMICO,
   VAL_ANA_GRE,
   DESC_ISTITUTO,
   COD_STRUTTURA_COMPETENTE_DC,
   DESC_STRUTTURA_COMPETENTE_DC,
   COD_STRUTTURA_COMPETENTE_RG,
   DESC_STRUTTURA_COMPETENTE_RG,
   COD_STRUTTURA_COMPETENTE_AR,
   DESC_STRUTTURA_COMPETENTE_AR,
   COD_STRUTTURA_COMPETENTE_FI,
   DESC_STRUTTURA_COMPETENTE_FI,
   ID_UTENTE,
   ID_REFERENTE,
   COD_COMPARTO,
   FLG_ABI_LAVORATO
)
AS
   SELECT                                            -- V1  VG: Prima versione
                                 -- V2 11/03/2011 FS: Aggiunta DTA_TAVOLO_ORIG
                                 -- v3 07/04/2011 VG: Outer join per angrafica
         T.COD_ABI_CARTOLARIZZATO,
         T.COD_NDG,
         T.FLG_PIANO,
         T.FLG_WORKFLOW,
         T.DTA_PIANO,
         T.DTA_TAVOLO,
         T.DTA_TAVOLO_ORIG,
         DECODE (T.FLG_PIANO, 0, T.DTA_PIANO, NULL) DTA_FORZATURA_PIANO,
         (CASE WHEN T.FLG_PIANO >= 1 THEN T.DTA_PIANO ELSE NULL END)
            DTA_PIANO_CONFERMA_FILIALE,
         T.DTA_PIANO_CONFERMA_AREA,
         G.DESC_NOME_CONTROPARTE,
         T.COD_GRUPPO_ECONOMICO,
         E.VAL_ANA_GRE,
         I.DESC_ISTITUTO,
         S.COD_STRUTTURA_COMPETENTE_DC,
         S.DESC_STRUTTURA_COMPETENTE_DC,
         S.COD_STRUTTURA_COMPETENTE_RG,
         S.DESC_STRUTTURA_COMPETENTE_RG,
         S.COD_STRUTTURA_COMPETENTE_AR,
         S.DESC_STRUTTURA_COMPETENTE_AR,
         S.COD_STRUTTURA_COMPETENTE_FI,
         S.DESC_STRUTTURA_COMPETENTE_FI,
         U.ID_UTENTE,
         U.ID_REFERENTE,
         T.COD_COMPARTO,
         I.FLG_ABI_LAVORATO
    FROM V_MCRE0_APP_PT_GESTIONE_TAVOLI T,
         T_MCRE0_APP_ANAGRAFICA_GRUPPO G,
         T_MCRE0_APP_ANAGR_GRE E,
         MV_MCRE0_APP_ISTITUTI I,
         MV_MCRE0_DENORM_STR_ORG S,
         T_MCRE0_APP_UTENTI U
   WHERE     FLG_WORKFLOW IN (2, 3)
         AND T.COD_SNDG = G.COD_SNDG(+)
         AND T.ID_UTENTE IS NOT NULL
         AND T.ID_UTENTE = U.ID_UTENTE
         AND T.COD_ABI_ISTITUTO = S.COD_ABI_ISTITUTO_FI(+)
         AND T.COD_FILIALE = S.COD_STRUTTURA_COMPETENTE_FI(+)
         AND T.COD_ABI_CARTOLARIZZATO = I.COD_ABI
         AND T.COD_GRUPPO_ECONOMICO = E.COD_GRE(+);


GRANT DELETE, INSERT, REFERENCES, SELECT, UPDATE, ON COMMIT REFRESH, QUERY REWRITE, DEBUG, FLASHBACK, MERGE VIEW ON MCRE_OWN.V_MCRE0_APP_PT_PIANI_COMPL TO MCRE_USR;
