/* Formatted on 17/06/2014 18:02:32 (QP5 v5.227.12220.39754) */
CREATE OR REPLACE FORCE VIEW MCRE_OWN.V_MCRE0_APP_PT_GESTIONE_TAVOLI
(
   COD_ABI_CARTOLARIZZATO,
   COD_NDG,
   DTA_DEADLINE_INS_PIANO,
   DTA_DEADLINE_INS_PARERE_AREA,
   DTA_PIANO_CONFERMA_AREA,
   VAL_CAUSE_INTERCETTAMENTO,
   DTA_CONVOCAZIONE,
   DTA_SOLLECITO,
   DTA_TAVOLO,
   DTA_TAVOLO_ORIG,
   VAL_ANALISI_INTERCETTAMENTO,
   VAL_ANALISI_COMPLESSIVA,
   VAL_VALUTAZIONE_QUANTITATIVA,
   COD_MACROSTATO_PROPOSTO,
   VAL_MOTIVAZIONI,
   VAL_STRATEGIA_CREDITIZIA,
   VAL_PARERE_AREA,
   DTA_PIANO,
   VAL_NOMINATIVO_FIRMA,
   COD_MATRICOLA_FIRMA,
   VAL_NOMINATIVO_PARERE,
   COD_MATRICOLA_PARERE,
   FLG_PIANO,
   VAL_PARTECIPANTI,
   COD_MACROSTATO,
   VAL_DURATA_STATO,
   VAL_STRATEGIA_CREDITIZIA_ASS,
   VAL_LINEE_GUIDA,
   VAL_COMMENTO,
   DTA_VERBALE,
   COD_OD_CALCOLATO,
   COD_OD,
   FLG_WORKFLOW,
   VAL_SPECIALISTA_CRED_AREA,
   ID_UTENTE,
   DTA_INS,
   COD_ABI_ISTITUTO,
   FLG_VERBALE,
   VAL_OD,
   VAL_OD_CALCOLATO,
   COD_MATRICOLA_PRESAVISIONE,
   DTA_PRESAVISIONE,
   COD_STATO,
   DTA_DECORRENZA_STATO,
   DTA_SCADENZA_STATO,
   COD_STATO_PRECEDENTE,
   COD_PERCORSO,
   COD_PROCESSO,
   COD_FILIALE,
   COD_SNDG,
   COD_COMPARTO,
   COD_GRUPPO_ECONOMICO,
   COD_MATRICOLA,
   DESC_COGNOME,
   COD_STRUTTURA_COMPETENTE_DC,
   DESC_STRUTTURA_COMPETENTE_DC,
   COD_STRUTTURA_COMPETENTE_RG,
   DESC_STRUTTURA_COMPETENTE_RG,
   COD_STRUTTURA_COMPETENTE_AR,
   DESC_STRUTTURA_COMPETENTE_AR,
   COD_STRUTTURA_COMPETENTE_FI,
   DESC_STRUTTURA_COMPETENTE_FI
)
AS
   SELECT                    --v1.1 07.02.11 MM -- upd_field al posto di mople
          --v2   18.03.14 TB --aggiunti campi per variazione perimetro DR
          T."COD_ABI_CARTOLARIZZATO",
          T."COD_NDG",
          T."DTA_DEADLINE_INS_PIANO",
          T."DTA_DEADLINE_INS_PARERE_AREA",
          t.dta_piano_conferma_area,
          T."VAL_CAUSE_INTERCETTAMENTO",
          T."DTA_CONVOCAZIONE",
          T."DTA_SOLLECITO",
          T."DTA_TAVOLO",
          T."DTA_TAVOLO_ORIG",
          T."VAL_ANALISI_INTERCETTAMENTO",
          T."VAL_ANALISI_COMPLESSIVA",
          T."VAL_VALUTAZIONE_QUANTITATIVA",
          T."COD_MACROSTATO_PROPOSTO",
          T."VAL_MOTIVAZIONI",
          T."VAL_STRATEGIA_CREDITIZIA",
          T."VAL_PARERE_AREA",
          T."DTA_PIANO",
          T."VAL_NOMINATIVO_FIRMA",
          T."COD_MATRICOLA_FIRMA",
          T."VAL_NOMINATIVO_PARERE",
          T."COD_MATRICOLA_PARERE",
          T."FLG_PIANO",
          T."VAL_PARTECIPANTI",
          T."COD_MACROSTATO",
          T."VAL_DURATA_STATO",
          T."VAL_STRATEGIA_CREDITIZIA_ASS",
          T."VAL_LINEE_GUIDA",
          T."VAL_COMMENTO",
          T."DTA_VERBALE",
          T."COD_OD_CALCOLATO",
          T."COD_OD",
          T."FLG_WORKFLOW",
          t.val_specialista_cred_area,                                --11 giu
          NULLIF (m.id_utente, -1) id_utente,
          T."DTA_INS",
          m.cod_abi_istituto,
          t.flg_verbale,
          t.val_od,
          t.val_od_calcolato,
          t.cod_matricola_presavisione,
          t.dta_presavisione,
          m.cod_stato,
          m.dta_decorrenza_stato,
          m.dta_scadenza_stato,
          m.cod_stato_precedente,
          m.cod_percorso,
          m.cod_processo,
          m.cod_filiale,
          m.cod_sndg,
          m.cod_comparto,
          NULLIF (m.cod_gruppo_economico, '-1') cod_gruppo_economico,
          -------------------------------PERIMETRO_DR-----------------------------
          M.COD_MATRICOLA,
          M.COGNOME DESC_COGNOME,
          M.COD_STRUTTURA_COMPETENTE_DC,
          M.DESC_STRUTTURA_COMPETENTE_DC,
          M.COD_STRUTTURA_COMPETENTE_RG,
          M.DESC_STRUTTURA_COMPETENTE_RG,
          M.COD_STRUTTURA_COMPETENTE_AR,
          M.DESC_STRUTTURA_COMPETENTE_AR,
          M.COD_STRUTTURA_COMPETENTE_FI,
          M.DESC_STRUTTURA_COMPETENTE_FI
     -------------------------------PERIMETRO_DR-----------------------------
     FROM t_mcre0_app_pt_gestione_tavoli t, v_mcre0_app_upd_fields m
    WHERE     t.cod_abi_cartolarizzato = m.cod_abi_cartolarizzato
          AND t.cod_ndg = m.cod_ndg
          -- AND NVL (m.flg_outsourcing, 'N') = 'Y'
          AND m.flg_outsourcing = 'Y'
          AND m.cod_stato = 'PT'
          AND m.today_flg = '1';


GRANT DELETE, INSERT, REFERENCES, SELECT, UPDATE, ON COMMIT REFRESH, QUERY REWRITE, DEBUG, FLASHBACK, MERGE VIEW ON MCRE_OWN.V_MCRE0_APP_PT_GESTIONE_TAVOLI TO MCRE_USR;
