/* Formatted on 17/06/2014 18:11:06 (QP5 v5.227.12220.39754) */
CREATE OR REPLACE FORCE VIEW MCRE_OWN.V_MCRES_APP_REPORT_NOTIZIE
(
   ID_DPER,
   COD_ABI,
   COD_NDG,
   COD_TIPO_NOTIZIA,
   DTA_INIZO_VALIDITA,
   DTA_FINE_VALIDITA,
   DTA_INSERIMENTO_NOTIZIA,
   DESC_NOTIZIA,
   VAL_ANNO_PRATICA,
   COD_PRATICA,
   COD_SNDG,
   DTA_INS,
   DTA_UPD,
   COD_OPERATORE_INS_UPD
)
AS
   SELECT "ID_DPER",
          "COD_ABI",
          "COD_NDG",
          "COD_TIPO_NOTIZIA",
          "DTA_INIZO_VALIDITA",
          "DTA_FINE_VALIDITA",
          "DTA_INSERIMENTO_NOTIZIA",
          "DESC_NOTIZIA",
          "VAL_ANNO_PRATICA",
          "COD_PRATICA",
          "COD_SNDG",
          "DTA_INS",
          "DTA_UPD",
          "COD_OPERATORE_INS_UPD"
     FROM T_MCRES_APP_NOTIZIE P
    WHERE     DTA_FINE_VALIDITA = TO_DATE ('99991231', 'YYYYMMDD')
          AND ID_DPER <
                 (SELECT TO_CHAR (ID_DPER - 5, 'YYYYMMDD')
                    FROM T_MCRES_WRK_LAST_ACQUISIZIONE A
                   WHERE COD_FLUSSO = 'NOTIZIE' AND A.COD_ABI = P.COD_ABI);


GRANT DELETE, INSERT, REFERENCES, SELECT, UPDATE, ON COMMIT REFRESH, QUERY REWRITE, DEBUG, FLASHBACK, MERGE VIEW ON MCRE_OWN.V_MCRES_APP_REPORT_NOTIZIE TO MCRE_USR;
