/* Formatted on 17/06/2014 18:14:02 (QP5 v5.227.12220.39754) */
CREATE OR REPLACE FORCE VIEW MCRE_OWN.VOMCRE0_APP_RIO_ANOMALIE
(
   COD_ABI_CARTOLARIZZATO,
   COD_GRUPPO_ECONOMICO,
   COD_NDG,
   DTA_RILEVAZIONE,
   FLG_SINGOLO_CLIENTE,
   FLG_TIPO_ANOMALIA,
   ID_ANOMALIA,
   VAL_ANOMALIA,
   COD_MACROSTATO,
   COD_STATO
)
AS
   SELECT A.COD_ABI_CARTOLARIZZATO,
          X.COD_GRUPPO_ECONOMICO,
          A.COD_NDG,
          A.DTA_RILEVAZIONE,
          A.FLG_SINGOLO_CLIENTE,
          A.FLG_TIPO_ANOMALIA,
          A.ID_ANOMALIA,
          A.VAL_ANOMALIA,
          X.COD_MACROSTATO,
          X.COD_STATO
     FROM T_MCRE0_APP_RIO_ANOMALIE A, MV_MCRE0_APP_UPD_FIELD X
    WHERE     A.COD_ABI_CARTOLARIZZATO = X.COD_ABI_CARTOLARIZZATO
          AND A.COD_NDG = X.COD_NDG;


GRANT DELETE, INSERT, REFERENCES, SELECT, UPDATE, ON COMMIT REFRESH, QUERY REWRITE, DEBUG, FLASHBACK, MERGE VIEW ON MCRE_OWN.VOMCRE0_APP_RIO_ANOMALIE TO MCRE_USR;
