/* Formatted on 17/06/2014 18:14:23 (QP5 v5.227.12220.39754) */
CREATE OR REPLACE FORCE VIEW MCRE_OWN.VOMCRE0_APP_RIO_POS_DA_LAV
(
   COD_SNDG,
   COD_ABI_CARTOLARIZZATO,
   COD_ABI_ISTITUTO,
   DESC_ISTITUTO,
   COD_NDG,
   COD_COMPARTO,
   COD_RAMO_CALCOLATO,
   DESC_NOME_CONTROPARTE,
   COD_GRUPPO_ECONOMICO,
   VAL_ANA_GRE,
   COD_STRUTTURA_COMPETENTE_DC,
   DESC_STRUTTURA_COMPETENTE_DC,
   COD_STRUTTURA_COMPETENTE_RG,
   DESC_STRUTTURA_COMPETENTE_RG,
   COD_STRUTTURA_COMPETENTE_AR,
   DESC_STRUTTURA_COMPETENTE_AR,
   COD_STRUTTURA_COMPETENTE_FI,
   DESC_STRUTTURA_COMPETENTE_FI,
   COD_PROCESSO,
   COD_STATO,
   DTA_DECORRENZA_STATO,
   DTA_SCADENZA_STATO,
   COD_STATO_PRECEDENTE,
   VAL_GG_IN_MACROSTATO,
   ID_UTENTE,
   DTA_UTENTE_ASSEGNATO,
   DESC_NOME,
   DESC_COGNOME,
   SCSB_ACC_TOT,
   SCSB_UTI_TOT,
   ID_REFERENTE,
   FLG_ABI_LAVORATO,
   COD_ISTITUTO_SOA
)
AS
   SELECT                                    -- VG 11-03-2011 COD_ISTITUTO_SOA
                                                  -- v1 17/06/2011 VG: New PCR
         X.COD_SNDG,
         X.COD_ABI_CARTOLARIZZATO,
         X.COD_ABI_ISTITUTO,
         I.DESC_ISTITUTO,
         X.COD_NDG,
         X.COD_COMPARTO,
         X.COD_RAMO_CALCOLATO,
         G.DESC_NOME_CONTROPARTE,
         X.COD_GRUPPO_ECONOMICO,
         GE.VAL_ANA_GRE,
         S.COD_STRUTTURA_COMPETENTE_DC,
         S.DESC_STRUTTURA_COMPETENTE_DC,
         S.COD_STRUTTURA_COMPETENTE_RG,
         S.DESC_STRUTTURA_COMPETENTE_RG,
         S.COD_STRUTTURA_COMPETENTE_AR,
         S.DESC_STRUTTURA_COMPETENTE_AR,
         S.COD_STRUTTURA_COMPETENTE_FI,
         S.DESC_STRUTTURA_COMPETENTE_FI,
         X.COD_PROCESSO,
         X.COD_STATO,
         X.DTA_DECORRENZA_STATO,
         X.DTA_SCADENZA_STATO,
         X.COD_STATO_PRECEDENTE,
         TRUNC (SYSDATE) - X.DTA_DEC_MACROSTATO VAL_GG_IN_MACROSTATO,
         X.ID_UTENTE,
         X.DTA_UTENTE_ASSEGNATO,
         U.NOME DESC_NOME,
         U.COGNOME DESC_COGNOME,
         R.SCSB_ACC_TOT,
         R.SCSB_UTI_TOT,
         U.ID_REFERENTE,
         I.FLG_ABI_LAVORATO,
         I.COD_ISTITUTO_SOA
    FROM MV_MCRE0_APP_ISTITUTI I,
         T_MCRE0_APP_ANAGRAFICA_GRUPPO G,
         MV_MCRE0_APP_UPD_FIELD X,
         T_MCRE0_APP_ANAGR_GRE GE,
         MV_MCRE0_DENORM_STR_ORG S,
         T_MCRE0_APP_UTENTI U,
         T_MCRE0_APP_PCR R
   WHERE     X.COD_MACROSTATO = 'RIO'
         AND NVL (X.FLG_OUTSOURCING, 'N') = 'Y'
         AND X.COD_ABI_CARTOLARIZZATO = R.COD_ABI_CARTOLARIZZATO(+)
         AND X.COD_NDG = R.COD_NDG(+)
         AND X.COD_ABI_ISTITUTO = I.COD_ABI(+)
         AND X.COD_SNDG = G.COD_SNDG(+)
         AND X.COD_GRUPPO_ECONOMICO = GE.COD_GRE(+)
         AND X.COD_ABI_ISTITUTO = S.COD_ABI_ISTITUTO_FI(+)
         AND X.COD_FILIALE = S.COD_STRUTTURA_COMPETENTE_FI(+)
         AND X.ID_UTENTE = U.ID_UTENTE(+);


GRANT DELETE, INSERT, REFERENCES, SELECT, UPDATE, ON COMMIT REFRESH, QUERY REWRITE, DEBUG, FLASHBACK, MERGE VIEW ON MCRE_OWN.VOMCRE0_APP_RIO_POS_DA_LAV TO MCRE_USR;
