/* Formatted on 17/06/2014 18:13:51 (QP5 v5.227.12220.39754) */
CREATE OR REPLACE FORCE VIEW MCRE_OWN.VOMCRE0_APP_POS_DA_ASS
(
   ID_ALERT,
   VAL_ORDINE_COLORE,
   DESC_ALERT,
   VAL_ALERT,
   DTA_INS_ALERT,
   COD_COMPARTO,
   DESC_COMPARTO,
   COD_RAMO_CALCOLATO,
   COD_ABI_ISTITUTO,
   COD_ABI_CARTOLARIZZATO,
   COD_NDG,
   COD_SNDG,
   DESC_NOME_CONTROPARTE,
   COD_GRUPPO_ECONOMICO,
   COD_GRUPPO_SUPER,
   VAL_ANA_GRE,
   COD_LEGAME,
   FLG_GRUPPO_ECONOMICO,
   FLG_GRUPPO_LEGAME,
   FLG_SINGOLO,
   FLG_CONDIVISO,
   COD_STRUTTURA_COMPETENTE_DC,
   DESC_STRUTTURA_COMPETENTE_DC,
   COD_STRUTTURA_COMPETENTE_RG,
   DESC_STRUTTURA_COMPETENTE_RG,
   COD_STRUTTURA_COMPETENTE_AR,
   DESC_STRUTTURA_COMPETENTE_AR,
   COD_STRUTTURA_COMPETENTE_FI,
   DESC_STRUTTURA_COMPETENTE_FI,
   COD_PROCESSO,
   COD_STATO,
   COD_MACROSTATO,
   DTA_DECORRENZA_STATO,
   COD_STATO_DESTINAZIONE,
   ID_UTENTE_GIRATO_DA,
   DESC_UTENTE_GIRATO_DA,
   DESC_ISTITUTO,
   FLG_OUTSOURCING,
   ID_UTENTE_PRE,
   ID_UTENTE_PREASSEGNATO,
   DESC_COGNOME_PREASS,
   DESC_NOME_PREASS,
   COD_COMPARTO_PREASSEGNATO,
   DESC_COMPARTO_PREASS,
   COD_MATR_ASSEGNATORE,
   FLG_ABI_LAVORATO
)
AS
   SELECT                                       -- V1 02/12/2010 VG: Congelata
          --  17/12/2010 MM aggiunto grupppo Super
          -- V2 22/12/2010 VG: COD_RAMO_CALCOLATO
          -- V3 30/12/2010 ML: modifica clausola AND co2.cod_comparto=f.cod_comparto_preassegnato con OUTER JOIN e aggiunta flag gruppo / Legame
          -- VG 26/01/2011 Outsourcing e target
          -- VG 02/01/2011 vista alert sostituita con tabella
          -- VG 08/06/2011 TOLTA FILE_GUIDA
          DISTINCT
          DECODE (P.ALERT_5, NULL, 9, 5) ID_ALERT,
          (SELECT DECODE (
                     ALERT_5,
                     'V', VAL_VERDE,
                     DECODE (ALERT_5,
                             'A', VAL_ARANCIO,
                             DECODE (ALERT_5, 'R', VAL_ROSSO, NULL)))
             FROM T_MCRE0_APP_ALERT
            WHERE ID_ALERT = 5)
             VAL_ORDINE_COLORE,
          (SELECT R.DESC_ALERT
             FROM T_MCRE0_APP_ALERT R
            WHERE R.ID_ALERT = DECODE (P.ALERT_5, NULL, 9, 5))
             DESC_ALERT,
          NVL (P.ALERT_5, P.ALERT_9) VAL_ALERT,
          NVL (P.DTA_INS_5, P.DTA_INS_9) DTA_INS_ALERT,
          X.COD_COMPARTO,
          CO.DESC_COMPARTO,
          X.COD_RAMO_CALCOLATO,
          X.COD_ABI_ISTITUTO,
          X.COD_ABI_CARTOLARIZZATO,
          X.COD_NDG,
          X.COD_SNDG,
          A.DESC_NOME_CONTROPARTE,
          X.COD_GRUPPO_ECONOMICO,
          X.COD_GRUPPO_SUPER,
          GE.VAL_ANA_GRE,
          LE.COD_LEGAME,
          X.FLG_GRUPPO_ECONOMICO,
          X.FLG_GRUPPO_LEGAME,
          X.FLG_SINGOLO,
          X.FLG_CONDIVISO,
          S.COD_STRUTTURA_COMPETENTE_DC,
          S.DESC_STRUTTURA_COMPETENTE_DC,
          S.COD_STRUTTURA_COMPETENTE_RG,
          S.DESC_STRUTTURA_COMPETENTE_RG,
          S.COD_STRUTTURA_COMPETENTE_AR,
          S.DESC_STRUTTURA_COMPETENTE_AR,
          S.COD_STRUTTURA_COMPETENTE_FI,
          S.DESC_STRUTTURA_COMPETENTE_FI,
          X.COD_PROCESSO,
          X.COD_STATO,
          X.COD_MACROSTATO,
          X.DTA_DECORRENZA_STATO,
          ' ' COD_STATO_DESTINAZIONE,
          X.COD_OPERATORE_INS_UPD ID_UTENTE_GIRATO_DA,
          U.COGNOME || ' ' || U.NOME DESC_UTENTE_GIRATO_DA,
          I.DESC_ISTITUTO,
          I.FLG_OUTSOURCING,
          X.ID_UTENTE_PRE,
          X.ID_UTENTE_PREASSEGNATO,
          U2.COGNOME DESC_COGNOME_PREASS,
          U2.NOME DESC_NOME_PREASS,
          X.COD_COMPARTO_PREASSEGNATO,
          CO2.DESC_COMPARTO DESC_COMPARTO_PREASS,
          X.COD_MATR_ASSEGNATORE,
          I.FLG_ABI_LAVORATO
     FROM MCRE_OWN.MV_MCRE0_APP_UPD_FIELD X,
          T_MCRE0_APP_ANAGRAFICA_GRUPPO A,
          MV_MCRE0_DENORM_STR_ORG S,
          MCRE_OWN.MV_MCRE0_APP_ISTITUTI I,
          T_MCRE0_APP_COMPARTI CO,
          T_MCRE0_APP_COMPARTI CO2,
          T_MCRE0_APP_ALERT_POS P,
          T_MCRE0_APP_ANAGR_GRE GE,
          T_MCRE0_APP_GRUPPO_LEGAME LE,
          T_MCRE0_APP_UTENTI U,
          T_MCRE0_APP_UTENTI U2
    WHERE     CO.COD_COMPARTO = X.COD_COMPARTO
          --nvl(f.cod_comparto_calcolato,f.cod_comparto_assegnato) --
          AND CO.FLG_CHK = 1
          AND X.COD_COMPARTO_PREASSEGNATO = CO2.COD_COMPARTO(+)
          AND (P.ALERT_5 IS NOT NULL OR P.ALERT_9 IS NOT NULL)
          AND X.ID_UTENTE IS NULL
          AND X.COD_ABI_CARTOLARIZZATO = P.COD_ABI_CARTOLARIZZATO
          AND X.COD_NDG = P.COD_NDG
          AND X.COD_SNDG = A.COD_SNDG(+)
          AND X.COD_GRUPPO_ECONOMICO = GE.COD_GRE(+)
          AND X.COD_SNDG = LE.COD_SNDG(+)
          AND X.COD_ABI_ISTITUTO = S.COD_ABI_ISTITUTO_FI(+)
          AND X.COD_FILIALE = S.COD_STRUTTURA_COMPETENTE_FI(+)
          AND X.COD_ABI_CARTOLARIZZATO = I.COD_ABI(+)
          AND X.COD_OPERATORE_INS_UPD = U.COD_MATRICOLA(+)
          AND X.ID_UTENTE_PREASSEGNATO = U2.ID_UTENTE(+)
          AND X.COD_STATO IN (SELECT COD_MICROSTATO
                                FROM T_MCRE0_APP_STATI S
                               WHERE S.FLG_STATO_CHK = 1)
          AND NVL (X.FLG_OUTSOURCING, 'N') = 'Y'
          AND I.FLG_TARGET = 'Y'
          AND DECODE (P.ALERT_5, NULL, 9, 5) = 5;


GRANT DELETE, INSERT, REFERENCES, SELECT, UPDATE, ON COMMIT REFRESH, QUERY REWRITE, DEBUG, FLASHBACK, MERGE VIEW ON MCRE_OWN.VOMCRE0_APP_POS_DA_ASS TO MCRE_USR;
