/* Formatted on 17/06/2014 18:17:54 (QP5 v5.227.12220.39754) */
CREATE OR REPLACE FORCE VIEW MCRE_OWN.X_MCREI_APP_RAPPORTI_DERIVATI
(
   COD_RAPPORTO,
   COD_FORMA_TECNICA,
   COD_NATURA,
   COD_TIPO_FIDO,
   VAL_ACCORDATO,
   VAL_UTILIZZATO
)
AS
   SELECT PCR.COD_RAPPORTO,
          PCR.COD_FORMA_TECNICA,
          NAT.COD_NATURA,
          PCR.COD_TIPO_FIDO,
          PCR.VAL_ACCORDATO_DELIB,
          PCR.VAL_IMP_UTILIZZATO
     --  29/11/2011   Luca Ferretti   Creazione vista
     FROM T_MCREI_APP_PCR_RAPPORTI pcr, T_MCRE0_APP_NATURA_FTECNICA nat
    WHERE     PCR.COD_FORMA_TECNICA = NAT.COD_FTECNICA
          AND PCR.COD_CLASSE_FT = 'ST';


GRANT DELETE, INSERT, REFERENCES, SELECT, UPDATE, ON COMMIT REFRESH, QUERY REWRITE, DEBUG, FLASHBACK, MERGE VIEW ON MCRE_OWN.X_MCREI_APP_RAPPORTI_DERIVATI TO MCRE_USR;
