Insert into T_MCRE0_ETL_CALLER (CALLER,SQL_ORD,SQL_TEXT,STEP,FLG_EXEC,LAST_UPDATE_DATE,NOTE) values ('load_anagrafica_gruppo','5','MERGE INTO T_MCRE0_DWH_AGRU trg
USING T_MCRE0_DAY_AGRU src
ON  (src.COD_SNDG = trg.COD_SNDG)
WHEN MATCHED THEN UPDATE
SET trg.DESC_NOME_CONTROPARTE=src.DESC_NOME_CONTROPARTE,
    trg.VAL_PARTITA_IVA=src.VAL_PARTITA_IVA,
    trg.VAL_SETTORE_ECONOMICO=src.VAL_SETTORE_ECONOMICO,
    trg.VAL_RAMO_ECONOMICO=src.VAL_RAMO_ECONOMICO,
    trg.FLG_ART_136=src.FLG_ART_136,
    trg.COD_SNDG_SOGGETTO=src.COD_SNDG_SOGGETTO,
    trg.VAL_SEGMENTO_REGOLAMENTARE=src.VAL_SEGMENTO_REGOLAMENTARE,
    trg.DTA_SEGMENTO_REGOLAMENTARE=src.DTA_SEGMENTO_REGOLAMENTARE,
    trg.VAL_PD_ONLINE=src.VAL_PD_ONLINE,
    trg.DTA_RIF_PD_ONLINE=src.DTA_RIF_PD_ONLINE,
    trg.DTA_INIZIO_RELAZIONE=src.DTA_INIZIO_RELAZIONE ,
    trg.DTA_UPD= sysdate,
    trg.ID_DPER = src.ID_DPER,
    trg.VAL_RATING_ONLINE = src.VAL_RATING_ONLINE,
    trg.DTA_NASCITA_COSTITUZIONE = src.DTA_NASCITA_COSTITUZIONE
WHEN NOT MATCHED THEN INSERT (
            trg.COD_SNDG,
            trg.DESC_NOME_CONTROPARTE,
            trg.VAL_PARTITA_IVA,
            trg.VAL_SETTORE_ECONOMICO,
            trg.VAL_RAMO_ECONOMICO,
            trg.FLG_ART_136,
            trg.COD_SNDG_SOGGETTO,
            trg.VAL_SEGMENTO_REGOLAMENTARE,
            trg.DTA_SEGMENTO_REGOLAMENTARE,
            trg.VAL_PD_ONLINE,
            trg.DTA_RIF_PD_ONLINE,
            trg.DTA_INIZIO_RELAZIONE ,
            trg.DTA_INS ,
            trg.DTA_UPD ,            
            trg.ID_DPER ,
            trg.VAL_RATING_ONLINE,
            trg.DTA_NASCITA_COSTITUZIONE)
   VALUES (
            src.COD_SNDG,
            src.DESC_NOME_CONTROPARTE,
            src.VAL_PARTITA_IVA,
            src.VAL_SETTORE_ECONOMICO,
            src.VAL_RAMO_ECONOMICO,
            src.FLG_ART_136,
            src.COD_SNDG_SOGGETTO,
            src.VAL_SEGMENTO_REGOLAMENTARE,
            src.DTA_SEGMENTO_REGOLAMENTARE,
            src.VAL_PD_ONLINE,
            src.DTA_RIF_PD_ONLINE,
            src.DTA_INIZIO_RELAZIONE,
            sysdate,
            sysdate,
            src.ID_DPER,
            src.VAL_RATING_ONLINE,
            src.DTA_NASCITA_COSTITUZIONE )','DWH','1',to_date('18-NOV-2013 00:47:46','DD-MON-YYYY HH24:MI:SS'),'MERGE INTO T_MCRE0_DWH_AGRU');