Insert into T_MCRE0_ETL_CALLER (CALLER,SQL_ORD,SQL_TEXT,STEP,FLG_EXEC,LAST_UPDATE_DATE,NOTE) values ('load_anagrafica_gruppo','4','insert into T_MCRE0_DAY_AGRU 
select  COD_SNDG,
        DESC_NOME_CONTROPARTE,
        VAL_PARTITA_IVA,
        VAL_SETTORE_ECONOMICO,
        VAL_RAMO_ECONOMICO,
        FLG_ART_136,
        COD_SNDG_SOGGETTO,
        VAL_SEGMENTO_REGOLAMENTARE,
        DTA_SEGMENTO_REGOLAMENTARE,
        VAL_PD_ONLINE,
        DTA_RIF_PD_ONLINE,
        DTA_INIZIO_RELAZIONE,
        SYSDATE as DTA_INS,
        SYSDATE as DTA_UPD,
        ID_DPER,
        VAL_RATING_ONLINE,
        DTA_NASCITA_COSTITUZIONE
from T_MCRE0_STG_AGRU','DAY','1',to_date('18-NOV-2013 00:47:46','DD-MON-YYYY HH24:MI:SS'),'insert into T_MCRE0_DAY_AGRU ');