/* Formatted on 21/07/2014 18:30:48 (QP5 v5.227.12220.39754) */
CREATE OR REPLACE FORCE VIEW MCRE_OWN.T_MCREI_PROVA_JOIN_STIME
(
   COD_ABI,
   COD_NDG,
   COD_SNDG,
   RAPP_PCR,
   RAPP_STIME,
   COD_STATO,
   VAL_CNT_DELIBERE,
   VAL_CNT_RAPPORTI,
   COD_PROTOCOLLO_DELIBERA
)
AS
   SELECT PPCR.COD_ABI,
          PPCR.COD_NDG,
          PPCR.COD_SNDG,
          PPCR.COD_RAPPORTO AS RAPP_PCR,
          S.COD_RAPPORTO AS RAPP_STIME,
          AD.COD_STATO,
          1 AS VAL_CNT_DELIBERE,
          COUNT (*) OVER (PARTITION BY PPCR.COD_ABI, PPCR.COD_NDG)
             AS VAL_CNT_RAPPORTI,
          S.COD_PROTOCOLLO_DELIBERA
     FROM T_MCREI_APP_PCR_RAPPORTI PPCR,
          T_MCREI_APP_STIME PARTITION (INC_PATTIVE) S,
          T_MCREI_APP_PRATICHE PARTITION (INC_PATTIVE) P,
          V_MCRE0_APP_UPD_FIELDS AD
    WHERE     PPCR.COD_ABI = S.COD_ABI
          AND PPCR.COD_NDG = S.COD_NDG
          AND PPCR.COD_RAPPORTO = S.COD_RAPPORTO
          AND PPCR.COD_ABI = AD.COD_ABI_CARTOLARIZZATO
          AND PPCR.COD_NDG = AD.COD_NDG
          AND AD.FLG_OUTSOURCING = 'Y'
          AND AD.FLG_TARGET = 'Y'
          AND AD.COD_STATO IN ('IN', 'RS')
          AND PPCR.COD_ABI = P.COD_ABI
          AND PPCR.COD_NDG = P.COD_NDG;
