/* Formatted on 21/07/2014 18:30:47 (QP5 v5.227.12220.39754) */
CREATE OR REPLACE FORCE VIEW MCRE_OWN.T_MCRE0_APP_ISTITUTI
(
   COD_ISTITUTO,
   COD_ABI,
   DESC_ISTITUTO,
   DESC_BREVE,
   COD_ISTITUTO_SOA,
   COD_ABI_VISUALIZZATO,
   FLG_OUTSOURCING,
   FLG_TARGET,
   FLG_CARTOLARIZZATO,
   FLG_CHIUSURA_MANCATO_AGG,
   FLG_SEGREGATO,
   COD_ABI_ISTITUTO,
   FLG_CCP,
   FLG_SOFF,
   FLG_TIPO_ABI,
   FLG_SERVICING_PLF,
   FLG_CESSIONE_ROUT
)
AS
   SELECT "COD_ISTITUTO",
          "COD_ABI",
          "DESC_ISTITUTO",
          "DESC_BREVE",
          "COD_ISTITUTO_SOA",
          "COD_ABI_VISUALIZZATO",
          "FLG_OUTSOURCING",
          "FLG_TARGET",
          "FLG_CARTOLARIZZATO",
          "FLG_CHIUSURA_MANCATO_AGG",
          "FLG_SEGREGATO",
          "COD_ABI_ISTITUTO",
          "FLG_CCP",
          "FLG_SOFF",
          "FLG_TIPO_ABI",
          FLG_SERVICING_PLF,
          FLG_CESSIONE_ROUT
     FROM T_MCRE0_APP_ISTITUTI_ALL
    WHERE FLG_CCP = 1;
