/* Formatted on 21/07/2014 18:41:39 (QP5 v5.227.12220.39754) */
CREATE OR REPLACE FORCE VIEW MCRE_OWN.V_MCRES_APP_ALERT_VOCI_AG_EPC
(
   COD_AGENDA,
   COD_GESTORE,
   VAL_NUMERO
)
AS
     SELECT V.COD_AGENDA, V.COD_GESTORE, COUNT (*) AS VAL_NUMERO
       FROM T_MCRES_APP_VOCI_AGENDA_EPC V
      WHERE     1 = 1
            AND TRUNC (V.DTA_UPD) =
                   (SELECT TRUNC (MAX (DTA_UPD))
                      FROM T_MCRES_APP_VOCI_AGENDA_EPC)
   GROUP BY V.COD_AGENDA, V.COD_GESTORE;
