/* Formatted on 21/07/2014 18:39:04 (QP5 v5.227.12220.39754) */
CREATE OR REPLACE FORCE VIEW MCRE_OWN.V_MCREI_APP_ALLEGATI_DELIBERA
(
   COD_DOCUMENTO,
   DESC_DOCUMENTO,
   COD_PROTOCOLLO_PACCHETTO,
   DTA_UPD
)
AS
   SELECT DISTINCT (A.COD_DOCUMENTO),
                   A.DESC_DOCUMENTO,
                   B.COD_PROTOCOLLO_PACCHETTO,
                   B.DTA_UPD
     FROM T_MCREI_CL_ALLEGATI_DELIB A, T_MCREI_APP_ALLEGATI_DELIBERA B
    WHERE A.COD_DOCUMENTO = B.COD_DOCUMENTO;
