/* Formatted on 21/07/2014 18:41:12 (QP5 v5.227.12220.39754) */
CREATE OR REPLACE FORCE VIEW MCRE_OWN.V_MCREI_WRK_SVECCHIAMENTO
(
   TIPO_TABELLA,
   NOME_TABELLA,
   VAL_PERIODO_SVECCHIAMENTO,
   COD_FILE,
   FLG_ACTIVE,
   FLG_MOVE,
   TBSPACE_TMP
)
AS
     SELECT TIPO_TABELLA,
            NOME_TABELLA,
            VAL_PERIODO_SVECCHIAMENTO,
            COD_FILE,
            FLG_ACTIVE,
            FLG_MOVE,
            TBSPACE_TMP
       FROM T_MCREI_WRK_SVECCHIAMENTO
      WHERE 1 = 1
   GROUP BY TIPO_TABELLA,
            NOME_TABELLA,
            VAL_PERIODO_SVECCHIAMENTO,
            COD_FILE,
            FLG_ACTIVE,
            FLG_MOVE,
            TBSPACE_TMP
     HAVING FLG_ACTIVE = 1;
