/* Formatted on 21/07/2014 18:39:11 (QP5 v5.227.12220.39754) */
CREATE OR REPLACE FORCE VIEW MCRE_OWN.V_MCREI_APP_COINTEST_PROP_HST
(
   COD_ABI,
   COD_NDG,
   COD_SNDG,
   COD_SNDG_COINT,
   COD_ABI_COINT,
   COD_NDG_COINT,
   DESC_NOME_CONTROPARTE,
   COD_TIPO_LEGAME
)
AS
   SELECT "COD_ABI",
          "COD_NDG",
          "COD_SNDG",
          "COD_SNDG_COINT",
          "COD_ABI_COINT",
          "COD_NDG_COINT",
          "DESC_NOME_CONTROPARTE",
          "COD_TIPO_LEGAME"
     FROM V_MCREI_APP_COINTESTATARI_PROP;
