/* Formatted on 21/07/2014 18:32:59 (QP5 v5.227.12220.39754) */
CREATE OR REPLACE FORCE VIEW MCRE_OWN.V_MCRE0_APP_ALERT_SO_GEST_INT
(
   COD_ABI_CARTOLARIZZATO,
   COD_ABI_ISTITUTO,
   COD_COMPARTO_POSIZIONE,
   COD_COMPARTO_UTENTE,
   COD_GRUPPO_ECONOMICO,
   COD_MACROSTATO,
   COD_NDG,
   COD_PRIV,
   COD_PROCESSO,
   COD_RAMO_CALCOLATO,
   COD_SNDG,
   COD_STATO,
   COD_STRUTTURA_COMPETENTE_AR,
   COD_STRUTTURA_COMPETENTE_DC,
   COD_STRUTTURA_COMPETENTE_FI,
   COD_STRUTTURA_COMPETENTE_RG,
   DESC_COGNOME,
   DESC_ISTITUTO,
   DESC_NOME,
   DESC_NOME_CONTROPARTE,
   DESC_STRUTTURA_COMPETENTE_AR,
   DESC_STRUTTURA_COMPETENTE_DC,
   DESC_STRUTTURA_COMPETENTE_FI,
   DESC_STRUTTURA_COMPETENTE_RG,
   DTA_DECORRENZA_STATO,
   DTA_INS_ALERT,
   DTA_SCADENZA_STATO,
   DTA_UTENTE_ASSEGNATO,
   FLG_ABI_LAVORATO,
   FLG_GESTORE_ABILITATO,
   ID_REFERENTE,
   ID_UTENTE,
   VAL_ALERT,
   VAL_ANA_GRE,
   VAL_ORDINE_COLORE,
   COD_STRUTTURA_COMPETENTE,
   VAL_UTI_TOT
)
AS
   SELECT AD.COD_ABI_CARTOLARIZZATO,
          AD.COD_ABI_ISTITUTO,
          AD.COD_COMPARTO COD_COMPARTO_POSIZIONE,
          AD.COD_COMPARTO_UTENTE,
          AD.COD_GRUPPO_ECONOMICO,
          AD.COD_MACROSTATO,
          AD.COD_NDG,
          AD.COD_PRIV,
          AD.COD_PROCESSO,
          AD.COD_RAMO_CALCOLATO,
          AD.COD_SNDG,
          'SO' AS COD_STATO,
          AD.COD_STRUTTURA_COMPETENTE_AR,
          AD.COD_STRUTTURA_COMPETENTE_DC,
          AD.COD_STRUTTURA_COMPETENTE_FI,
          AD.COD_STRUTTURA_COMPETENTE_RG,
          AD.COGNOME DESC_COGNOME,
          AD.DESC_ISTITUTO,
          AD.NOME DESC_NOME,
          AD.DESC_NOME_CONTROPARTE,
          AD.DESC_STRUTTURA_COMPETENTE_AR,
          AD.DESC_STRUTTURA_COMPETENTE_DC,
          AD.DESC_STRUTTURA_COMPETENTE_FI,
          AD.DESC_STRUTTURA_COMPETENTE_RG,
          AD.DTA_DECORRENZA_STATO,
          POS.DTA_INS DTA_INS_ALERT,
          AD.DTA_SCADENZA_STATO,
          AD.DTA_UTENTE_ASSEGNATO,
          '1' FLG_ABI_LAVORATO,
          AD.FLG_GESTORE_ABILITATO,
          AD.ID_REFERENTE,
          AD.ID_UTENTE,
          CASE
             WHEN (SYSDATE - POS.DTA_INS) <= 2
             THEN
                'V'
             WHEN     (SYSDATE - POS.DTA_INS) <= 5
                  AND (SYSDATE - POS.DTA_INS) > 2
             THEN
                'A'
             WHEN (SYSDATE - POS.DTA_INS) > 5
             THEN
                'R'
          END
             VAL_ALERT,
          AD.DESC_GRUPPO_ECONOMICO AS VAL_ANA_GRE,
          POS.VAL_ORDINE_COLORE,
          AD.COD_STRUTTURA_COMPETENTE,
          ad.SCSB_UTI_TOT VAL_UTI_TOT
     FROM T_MCREI_APP_ALERT_POS_WRK PARTITION (INC_P42) POS,
          V_MCRE0_APP_UPD_FIELDS AD
    WHERE     POS.COD_ABI = AD.COD_ABI_CARTOLARIZZATO
          AND POS.COD_NDG = AD.COD_NDG            --mm 0606 filtro outsourcing
          AND AD.FLG_OUTSOURCING = 'Y';
