/* Formatted on 21/07/2014 18:32:33 (QP5 v5.227.12220.39754) */
CREATE OR REPLACE FORCE VIEW MCRE_OWN.V_MCRE0_APP_ALERT_PAC_NO_ALL
(
   COD_ABI_CARTOLARIZZATO,
   COD_COMPARTO_POSIZIONE,
   COD_DOC_APPENDICE_PARERE,
   COD_DOC_CLASSIFICAZIONE,
   COD_DOC_DELIBERA_BANCA,
   COD_DOC_DELIBERA_CAPOGRUPPO,
   COD_DOC_PARERE_CONFORMITA,
   COD_GRUPPO,
   COD_MACROSTATO,
   COD_MICROSTATO,
   COD_MICROTIPOLOGIA,
   COD_NDG,
   COD_PROCESSO,
   COD_PROT_DELIBERA,
   COD_SNDG,
   COD_STATO,
   COD_STRUTTURA_COMPETENTE_AR,
   COD_STRUTTURA_COMPETENTE_DC,
   COD_STRUTTURA_COMPETENTE_DV,
   COD_STRUTTURA_COMPETENTE_FI,
   COD_STRUTTURA_COMPETENTE_RG,
   DESC_COGNOME_GESTORE,
   DESC_GRUPPO,
   DESC_MACROSTATO,
   DESC_MICROSTATO,
   DESC_MICROTIPOLOGIA,
   DESC_NOME_CONTROPARTE,
   DESC_NOME_GESTORE,
   DESC_STRUTTURA_COMPETENTE_AR,
   DESC_STRUTTURA_COMPETENTE_DC,
   DESC_STRUTTURA_COMPETENTE_DV,
   DESC_STRUTTURA_COMPETENTE_FI,
   DESC_STRUTTURA_COMPETENTE_RG,
   DTA_FORZ_DELIBERA,
   DTA_INS_ALERT,
   DTA_RILEV,
   FLG_ABI_LAVORATO,
   FLG_GESTORE_ABILITATO,
   FLG_LAVORABILE,
   ID_UTENTE,
   VAL_ALERT
)
AS
   SELECT d.cod_abi AS cod_abi_cartolarizzato,
          NULL AS COD_COMPARTO_POSIZIONE,
          d.COD_DOC_APPENDICE_PARERE,
          d.COD_DOC_CLASSIFICAZIONE,
          d.COD_DOC_DELIBERA_BANCA,
          d.COD_DOC_DELIBERA_CAPOGRUPPO,
          d.COD_DOC_PARERE_CONFORMITA,
          AD.COD_GRUPPO_ECONOMICO AS COD_GRUPPO,
          AD.COD_MACROSTATO,
          AD.COD_STATO AS COD_MICROSTATO,
          d.cod_microtipologia_delib AS COD_MICROTIPOLOGIA,
          d.COD_NDG,
          ad.COD_PROCESSO,
          D.COD_PROTOCOLLO_DELIBERA AS COD_PROT_DELIB,
          D.COD_SNDG,
          AD.COD_STATO,
          org.COD_STRUTTURA_COMPETENTE_AR,
          org.COD_STRUTTURA_COMPETENTE_DC,
          org.COD_STRUTTURA_COMPETENTE_DV,
          org.COD_STRUTTURA_COMPETENTE_FI,
          org.COD_STRUTTURA_COMPETENTE_RG,
          NULL AS DESC_COGNOME_GESTORE,
          ad.DESC_GRUPPO_ECONOMICO AS DESC_GRUPPO,
          s.DESC_MACROSTATO,
          s.DESC_MICROSTATO,
          NULL AS DESC_MICROTIPOLOGIA,
          AD.DESC_NOME_CONTROPARTE,
          NULL AS DESC_NOME_GESTORE,
          org.DESC_STRUTTURA_COMPETENTE_AR,
          org.DESC_STRUTTURA_COMPETENTE_DC,
          org.DESC_STRUTTURA_COMPETENTE_DV,
          org.DESC_STRUTTURA_COMPETENTE_FI,
          org.DESC_STRUTTURA_COMPETENTE_RG,
          NULL AS DTA_FORZ_DELIBERA,
          pw.dta_ins,
          NULL AS DTA_RILEV,
          NULL AS FLG_ABI_LAVORATO,
          NULL AS FLG_GESTORE_ABILITATO,
          NULL AS FLG_LAVORABILE,
          NULL AS ID_UTENTE,
          pw.alert
     FROM t_mcrei_app_alert_pos_wrk PARTITION (inc_p44) pw,
          t_mcrei_app_delibere d,
          v_mcre0_app_upd_fields ad,
          mv_mcre0_denorm_str_org org,
          t_mcre0_app_stati s
    WHERE     pw.cod_abi = d.cod_abi
          AND pw.cod_ndg = d.cod_ndg
          AND pw.cod_protocollo_delibera = d.cod_protocollo_delibera
          AND ad.cod_abi_cartolarizzato = d.cod_abi
          AND ad.cod_ndg = d.cod_ndg
          AND ad.cod_struttura_competente = org.cod_struttura_competente_fi
          AND ad.cod_abi_istituto = org.cod_abi_istituto_fi
          AND ad.cod_stato = s.cod_microstato
          AND ad.flg_outsourcing = 'Y'
          AND ad.flg_target = 'Y'
          AND d.flg_no_delibera = 0;
