/* Formatted on 21/07/2014 18:34:47 (QP5 v5.227.12220.39754) */
CREATE OR REPLACE FORCE VIEW MCRE_OWN.V_MCRE0_APP_PT_POS_USCITE_MAN
(
   DESC_PERIODO,
   COD_Q,
   COD_COMPARTO,
   COD_ABI_CARTOLARIZZATO,
   COD_NDG,
   ID_UTENTE,
   ID_REFERENTE,
   COD_FILIALE,
   COD_ABI_ISTITUTO,
   GA_NUM_POS,
   IN_NUM_POS,
   RIO_NUM_POS,
   SO_NUM_POS,
   SCSB_UTI_TOT,
   SCSB_UTI_CASSA,
   SCSB_UTI_FIRMA,
   COD_STRUTTURA_COMPETENTE_DC,
   DESC_STRUTTURA_COMPETENTE_DC,
   COD_STRUTTURA_COMPETENTE_DV,
   DESC_STRUTTURA_COMPETENTE_DV,
   COD_STRUTTURA_COMPETENTE_AR,
   DESC_STRUTTURA_COMPETENTE_AR,
   COD_STRUTTURA_COMPETENTE_FI,
   DESC_STRUTTURA_COMPETENTE_FI,
   COD_STRUTTURA_COMPETENTE_RG,
   DESC_STRUTTURA_COMPETENTE_RG,
   COD_LIVELLO,
   NUM_POS_GIRO_COMP
)
AS
   SELECT DISTINCT q.desc_periodo,
                   q.cod_q,
                   cod_comparto,
                   cod_abi_cartolarizzato,
                   cod_ndg,
                   id_utente,
                   id_referente,
                   cod_filiale,
                   cod_abi_istituto,
                   DECODE (cod_macrostato, 'GA', 1, 0) ga_num_pos,
                   DECODE (cod_macrostato, 'IN', 1, 0) in_num_pos,
                   DECODE (cod_macrostato, 'RIO', 1, 0) rio_num_pos,
                   DECODE (cod_macrostato, 'SO', 1, 0) so_num_pos,
                   scsb_uti_tot,
                   scsb_uti_cassa,
                   scsb_uti_firma,
                   cod_struttura_competente_dc,
                   desc_struttura_competente_dc,
                   cod_struttura_competente_dv,
                   desc_struttura_competente_dv,
                   cod_struttura_competente_ar,
                   desc_struttura_competente_ar,
                   cod_struttura_competente_fi,
                   desc_struttura_competente_fi,
                   cod_struttura_competente_rg,
                   desc_struttura_competente_rg,
                   V.COD_LIVELLO,
                   0 num_pos_giro_comp
     FROM v_mcre0_app_pt_pos_uscite_man1 v,
          (SELECT 'Trimestre attuale' desc_periodo, 5 cod_q FROM DUAL
           UNION ALL
           SELECT 'Trimestre-1' desc_periodo, 4 cod_q FROM DUAL
           UNION ALL
           SELECT 'Trimestre-2' desc_periodo, 3 cod_q FROM DUAL
           UNION ALL
           SELECT 'Trimestre-3' desc_periodo, 2 cod_q FROM DUAL
           UNION ALL
           SELECT 'Trimestre-4' desc_periodo, 1 cod_q FROM DUAL) q
    WHERE q.cod_q = v.cod_q
   UNION ALL
   SELECT 'Trimestre-4' desc_periodo,
          1 cod_q,
          NULL cod_comparto,
          NULL cod_abi_cartolarizzato,
          NULL cod_ndg,
          NULL id_utente,
          NULL id_referente,
          NULL cod_filiale,
          NULL cod_abi_istituto,
          0 ga_num_pos,
          0 in_num_pos,
          0 rio_num_pos,
          0 so_num_pos,
          0 scsb_uti_tot,
          0 scsb_uti_cassa,
          0 scsb_uti_firma,
          NULL cod_struttura_competente_dc,
          NULL desc_struttura_competente_dc,
          NULL cod_struttura_competente_dv,
          NULL desc_struttura_competente_dv,
          NULL cod_struttura_competente_ar,
          NULL desc_struttura_competente_ar,
          NULL cod_struttura_competente_fi,
          NULL desc_struttura_competente_fi,
          NULL cod_struttura_competente_rg,
          NULL desc_struttura_competente_rg,
          NULL COD_LIVELLO,
          0 num_pos_giro_comp
     FROM DUAL
   UNION ALL
   SELECT 'Trimestre-3' desc_periodo,
          2 cod_q,
          NULL cod_comparto,
          NULL cod_abi_cartolarizzato,
          NULL cod_ndg,
          NULL id_utente,
          NULL id_referente,
          NULL cod_filiale,
          NULL cod_abi_istituto,
          0 ga_num_pos,
          0 in_num_pos,
          0 rio_num_pos,
          0 so_num_pos,
          0 scsb_uti_tot,
          0 scsb_uti_cassa,
          0 scsb_uti_firma,
          NULL cod_struttura_competente_dc,
          NULL desc_struttura_competente_dc,
          NULL cod_struttura_competente_dv,
          NULL desc_struttura_competente_dv,
          NULL cod_struttura_competente_ar,
          NULL desc_struttura_competente_ar,
          NULL cod_struttura_competente_fi,
          NULL desc_struttura_competente_fi,
          NULL cod_struttura_competente_rg,
          NULL desc_struttura_competente_rg,
          NULL COD_LIVELLO,
          0 num_pos_giro_comp
     FROM DUAL
   UNION ALL
   SELECT 'Trimestre-2' desc_periodo,
          3 cod_q,
          NULL cod_comparto,
          NULL cod_abi_cartolarizzato,
          NULL cod_ndg,
          NULL id_utente,
          NULL id_referente,
          NULL cod_filiale,
          NULL cod_abi_istituto,
          0 ga_num_pos,
          0 in_num_pos,
          0 rio_num_pos,
          0 so_num_pos,
          0 scsb_uti_tot,
          0 scsb_uti_cassa,
          0 scsb_uti_firma,
          NULL cod_struttura_competente_dc,
          NULL desc_struttura_competente_dc,
          NULL cod_struttura_competente_dv,
          NULL desc_struttura_competente_dv,
          NULL cod_struttura_competente_ar,
          NULL desc_struttura_competente_ar,
          NULL cod_struttura_competente_fi,
          NULL desc_struttura_competente_fi,
          NULL cod_struttura_competente_rg,
          NULL desc_struttura_competente_rg,
          NULL COD_LIVELLO,
          0 num_pos_giro_comp
     FROM DUAL
   UNION ALL
   SELECT 'Trimestre-1' desc_periodo,
          4 cod_q,
          NULL cod_comparto,
          NULL cod_abi_cartolarizzato,
          NULL cod_ndg,
          NULL id_utente,
          NULL id_referente,
          NULL cod_filiale,
          NULL cod_abi_istituto,
          0 ga_num_pos,
          0 in_num_pos,
          0 rio_num_pos,
          0 so_num_pos,
          0 scsb_uti_tot,
          0 scsb_uti_cassa,
          0 scsb_uti_firma,
          NULL cod_struttura_competente_dc,
          NULL desc_struttura_competente_dc,
          NULL cod_struttura_competente_dv,
          NULL desc_struttura_competente_dv,
          NULL cod_struttura_competente_ar,
          NULL desc_struttura_competente_ar,
          NULL cod_struttura_competente_fi,
          NULL desc_struttura_competente_fi,
          NULL cod_struttura_competente_rg,
          NULL desc_struttura_competente_rg,
          NULL COD_LIVELLO,
          0 num_pos_giro_comp
     FROM DUAL
   UNION ALL
   SELECT 'Trimestre attuale' desc_periodo,
          5 cod_q,
          NULL cod_comparto,
          NULL cod_abi_cartolarizzato,
          NULL cod_ndg,
          NULL id_utente,
          NULL id_referente,
          NULL cod_filiale,
          NULL cod_abi_istituto,
          0 ga_num_pos,
          0 in_num_pos,
          0 rio_num_pos,
          0 so_num_pos,
          0 scsb_uti_tot,
          0 scsb_uti_cassa,
          0 scsb_uti_firma,
          NULL cod_struttura_competente_dc,
          NULL desc_struttura_competente_dc,
          NULL cod_struttura_competente_dv,
          NULL desc_struttura_competente_dv,
          NULL cod_struttura_competente_ar,
          NULL desc_struttura_competente_ar,
          NULL cod_struttura_competente_fi,
          NULL desc_struttura_competente_fi,
          NULL cod_struttura_competente_rg,
          NULL desc_struttura_competente_rg,
          NULL COD_LIVELLO,
          0 num_pos_giro_comp
     FROM DUAL;
