/* Formatted on 21/07/2014 18:44:30 (QP5 v5.227.12220.39754) */
CREATE OR REPLACE FORCE VIEW MCRE_OWN.V_MCRES_ULTIMA_ACQ_BILANCIO
(
   COD_ABI,
   DTA_DPER,
   ID_DPER,
   VAL_ANNOMESE,
   VAL_ANNOMESE_PREC,
   VAL_ANNO,
   VAL_ANNO_PREC
)
AS
   SELECT                                         -- V1 17/10/2011 VG: CREATED
         DISTINCT
          W.COD_ABI,
          ID_DPER DTA_DPER,
          TO_CHAR (ID_DPER, 'YYYYMMDD') ID_DPER,
          TO_CHAR (ID_DPER, 'YYYYMM') VAL_ANNOMESE,
          TO_CHAR (ADD_MONTHS (ID_DPER, -1), 'YYYYMM') VAL_ANNOMESE_PREC,
          TO_CHAR (ID_DPER, 'YYYY') VAL_ANNO,
          TO_CHAR (ADD_MONTHS (ID_DPER, -12), 'YYYY') VAL_ANNO_PREC
     FROM MCRE_OWN.T_MCRES_WRK_ACQUISIZIONE W
    WHERE     COD_STATO IN ('CARICATO', 'CARICATO_APP')
          AND cod_flusso IN ('SISBA_CP', 'MCRDSISBACP');
