/* Formatted on 21/07/2014 18:34:19 (QP5 v5.227.12220.39754) */
CREATE OR REPLACE FORCE VIEW MCRE_OWN.V_MCRE0_APP_PM_DA_CONF
(
   ID_UTENTE,
   ID_REFERENTE,
   COD_COMPARTO,
   COD_SNDG,
   COD_NDG,
   DESC_NOME_CONTROPARTE,
   COD_GRUPPO_ECONOMICO,
   DESC_GRUPPO_ECONOMICO,
   COD_ABI_ISTITUTO,
   COD_ABI_CARTOLARIZZATO,
   DESC_ISTITUTO,
   COD_PERCORSO,
   COD_STRUTTURA_COMPETENTE_RG,
   DESC_STRUTTURA_COMPETENTE_RG,
   COD_STRUTTURA_COMPETENTE_AR,
   DESC_STRUTTURA_COMPETENTE_AR,
   COD_STRUTTURA_COMPETENTE_FI,
   DESC_STRUTTURA_COMPETENTE_FI,
   COD_STRUTTURA_COMPETENTE,
   DTA_DECORRENZA_STATO,
   DTA_SCADENZA_STATO,
   DTA_UTENTE_ASSEGNATO,
   COD_STATO_PRECEDENTE,
   COD_PROCESSO,
   SCSB_ACC_TOT,
   SCSB_UTI_TOT,
   VAL_NUMERO_PIANO,
   DTA_PIANO,
   DTA_SCADENZA,
   ID_WORKFLOW,
   COD_TIPO_PIANO,
   FLG_NUOVO_PIANO
)
AS
   SELECT                           -- VG 20140702 cod_tipo_piano diverso da L
         a.ID_UTENTE,
          a.ID_REFERENTE,
          a.COD_COMPARTO,
          a.COD_SNDG,
          a.COD_NDG,
          a.DESC_NOME_CONTROPARTE,
          a.COD_GRUPPO_ECONOMICO,
          a.DESC_GRUPPO_ECONOMICO,
          a.COD_ABI_ISTITUTO,
          a.COD_ABI_CARTOLARIZZATO,
          a.DESC_ISTITUTO,
          a.cod_percorso,
          a.COD_STRUTTURA_COMPETENTE_RG,
          a.DESC_STRUTTURA_COMPETENTE_RG,
          a.COD_STRUTTURA_COMPETENTE_AR,
          a.DESC_STRUTTURA_COMPETENTE_AR,
          a.COD_STRUTTURA_COMPETENTE_FI,
          a.DESC_STRUTTURA_COMPETENTE_FI,
          a.COD_STRUTTURA_COMPETENTE,
          a.DTA_DECORRENZA_STATO,
          a.DTA_SCADENZA_STATO,
          a.DTA_UTENTE_ASSEGNATO,
          (SELECT cod_macrostato
             FROM t_mcre0_app_stati
            WHERE cod_microstato = a.COD_STATO_PRECEDENTE)
             COD_STATO_PRECEDENTE,
          a.COD_PROCESSO,
          a.SCSB_ACC_TOT,
          a.SCSB_UTI_TOT,
          p.ID_PIANO VAL_NUMERO_PIANO,
          p.DTA_PIANO,
          p.DTA_SCADENZA,
          p.ID_WORKFLOW,
          P.COD_TIPO_PIANO,
          CASE WHEN P.ID_PIANO = 1 THEN 'S' ELSE 'N' END FLG_NUOVO_PIANO
     FROM V_MCRE0_APP_UPD_FIELDS a, T_MCRE0_APP_GEST_PM p
    WHERE     a.COD_ABI_CARTOLARIZZATO = p.COD_ABI_CARTOLARIZZATO
          AND a.COD_NDG = p.COD_NDG
          AND A.COD_STATO = 'PM'
          AND a.DTA_DECORRENZA_STATO = P.DTA_DECORRENZA_STATO
          AND P.FLG_PIANO_ANNULLATO = 'N'
          AND P.ID_WORKFLOW = 10                              --piano inserito
          AND dta_piano IS NOT NULL
          AND COD_TIPO_PIANO != 'L';
