/* Formatted on 21/07/2014 18:34:24 (QP5 v5.227.12220.39754) */
CREATE OR REPLACE FORCE VIEW MCRE_OWN.V_MCRE0_APP_PM_PIANI_ARCH
(
   COD_ABI_ISTITUTO,
   COD_ABI_CARTOLARIZZATO,
   COD_NDG,
   COD_SNDG,
   COD_FILIALE,
   COD_PERCORSO,
   VAL_NUMERO_PIANO,
   DTA_PIANO,
   DTA_SCADENZA,
   DTA_VALIDAZIONE,
   DTA_PIANO_ANNULLATO,
   COD_WORKFLOW,
   DESC_WORKFLOW,
   DTA_STATO_PROPOSTO,
   COD_STATO_PROPOSTO,
   VAL_NOTE_OPERATIVE,
   FLG_PRESA_VISIONE_MODIFICA,
   FLG_PIANO_ANNULLATO,
   ID_GESTORE,
   NOME,
   COGNOME,
   COD_MATRICOLA_ANNULLO,
   FLG_PIANO_ARCHIVIATO,
   COD_TIPO_PIANO
)
AS
   SELECT                                          --VG 20140707 cod_matricola
         a.COD_ABI_ISTITUTO,
          a.COD_ABI_CARTOLARIZZATO,
          a.COD_NDG,
          a.COD_SNDG,
          A.COD_FILIALE,
          A.COD_PERCORSO,
          p.ID_PIANO VAL_NUMERO_PIANO,
          p.DTA_PIANO,
          P.DTA_SCADENZA,
          P.DTA_PIANO_VALIDATO DTA_VALIDAZIONE,
          P.DTA_PIANO_ANNULLATO,
          W.COD_WORKFLOW,
          W.DESC_WORKFLOW,
          P.DTA_STATO_PROPOSTO,
          P.COD_STATO_PROPOSTO,
          P.VAL_NOTE_OPERATIVE,
          P.FLG_PRESA_VISIONE_MODIFICA,
          P.FLG_PIANO_ANNULLATO,
          NVL (P.ID_UTENTE_VALIDAZIONE, P.ID_UTENTE_ANNULLO) AS id_gestore,
          U.NOME,
          U.COGNOME,
          COD_MATRICOLA AS COD_MATRICOLA_ANNULLO,
          'S' flg_piano_archiviato,
          COD_TIPO_PIANO
     FROM t_mcre0_app_all_data a,
          T_MCRE0_APP_GEST_PM p,
          T_MCRE0_CL_WORKFLOW_PM w,
          T_MCRE0_APP_UTENTI u
    WHERE     a.COD_ABI_CARTOLARIZZATO = p.COD_ABI_CARTOLARIZZATO(+)
          AND a.COD_NDG = p.COD_NDG(+)
          AND COD_WORKFLOW(+) > 0
          AND A.COD_STATO = 'PM'
          AND (P.FLG_PIANO_ANNULLATO(+) = 'S' OR P.DTA_SCADENZA(+) < SYSDATE)
          AND A.COD_PERCORSO = P.COD_PERCORSO(+)
          AND P.ID_WORKFLOW = W.ID_WORKFLOW(+)
          AND NVL (P.ID_UTENTE_VALIDAZIONE, P.ID_UTENTE_ANNULLO) =
                 U.ID_UTENTE(+);
