/* Formatted on 21/07/2014 18:34:27 (QP5 v5.227.12220.39754) */
CREATE OR REPLACE FORCE VIEW MCRE_OWN.V_MCRE0_APP_PM_PIANI_RIF
(
   COD_ABI_ISTITUTO,
   COD_ABI_CARTOLARIZZATO,
   COD_NDG,
   COD_SNDG,
   DESC_ISTITUTO,
   DESC_NOME_CONTROPARTE,
   COD_COMPARTO,
   COD_FILIALE,
   COD_PERCORSO,
   COD_GRUPPO_ECONOMICO,
   DESC_GRUPPO_ECONOMICO,
   COD_STRUTTURA_COMPETENTE_RG,
   DESC_STRUTTURA_COMPETENTE_RG,
   COD_STRUTTURA_COMPETENTE_AR,
   DESC_STRUTTURA_COMPETENTE_AR,
   COD_STRUTTURA_COMPETENTE_FI,
   DESC_STRUTTURA_COMPETENTE_FI,
   COD_STRUTTURA_COMPETENTE,
   DTA_DECORRENZA_STATO,
   DTA_SCADENZA_STATO,
   COD_PROCESSO,
   VAL_NUMERO_PIANO,
   DTA_PIANO_ANNULLATO,
   DTA_PIANO,
   DTA_SCADENZA,
   DTA_SCADENZA_PRECEDENTE,
   DTA_VALIDAZIONE,
   VAL_NOTE_OPERATIVE,
   VAL_GG_PM,
   FLG_PIANO_MODIFICATO,
   FLG_PRESA_VISIONE_MODIFICA,
   SCSB_ACC_TOT,
   VAL_TOTALE_UTILIZZI
)
AS
   SELECT a.COD_ABI_ISTITUTO,
          a.COD_ABI_CARTOLARIZZATO,
          a.COD_NDG,
          a.COD_SNDG,
          a.DESC_ISTITUTO,
          a.DESC_NOME_CONTROPARTE,
          a.COD_COMPARTO,
          A.COD_FILIALE,
          a.cod_percorso,
          a.COD_GRUPPO_ECONOMICO,
          a.DESC_GRUPPO_ECONOMICO,
          a.COD_STRUTTURA_COMPETENTE_RG,
          a.DESC_STRUTTURA_COMPETENTE_RG,
          a.COD_STRUTTURA_COMPETENTE_AR,
          a.DESC_STRUTTURA_COMPETENTE_AR,
          a.COD_STRUTTURA_COMPETENTE_FI,
          a.DESC_STRUTTURA_COMPETENTE_FI,
          a.COD_STRUTTURA_COMPETENTE,
          a.DTA_DECORRENZA_STATO,
          a.DTA_SCADENZA_STATO,
          a.COD_PROCESSO,
          p.ID_PIANO VAL_NUMERO_PIANO,
          p.dta_piano_annullato,
          p.DTA_PIANO,
          P.DTA_SCADENZA,
          P.DTA_SCADENZA_PRECEDENTE,
          P.DTA_PIANO_VALIDATO DTA_VALIDAZIONE,
          P.VAL_NOTE_OPERATIVE,
          TRUNC (SYSDATE) - a.dta_decorrenza_stato VAL_GG_PM,
          P.FLG_PIANO_MODIFICATO,
          P.FLG_PRESA_VISIONE_MODIFICA,
          a.SCSB_ACC_TOT,
          a.SCSB_UTI_TOT val_totale_utilizzi
     FROM V_MCRE0_APP_UPD_FIELDS a,
          T_MCRE0_APP_GEST_PM p,
          T_MCRE0_APP_GEST_PM s
    WHERE     a.COD_ABI_CARTOLARIZZATO = p.COD_ABI_CARTOLARIZZATO
          AND a.COD_NDG = p.COD_NDG
          AND a.COD_PERCORSO = P.COD_PERCORSO
          AND s.COD_ABI_CARTOLARIZZATO(+) = p.COD_ABI_CARTOLARIZZATO
          AND s.COD_NDG(+) = p.COD_NDG
          AND s.COD_PERCORSO(+) = P.COD_PERCORSO
          AND s.ID_PIANO(+) > P.ID_PIANO
          AND a.COD_STATO = 'PM'
          AND p.ID_WORKFLOW = 30
          AND p.COD_TIPO_PIANO IN ('S', 'C')
          AND s.ID_PIANO IS NULL;
