/* Formatted on 21/07/2014 18:40:17 (QP5 v5.227.12220.39754) */
CREATE OR REPLACE FORCE VIEW MCRE_OWN.V_MCREI_APP_GARANZIE_PROP_HST
(
   COD_ABI,
   COD_GARANZIA,
   COD_FORMA_TECNICA,
   DESC_FORMA_TECNICA,
   DTA_PERFEZIONAMENTO,
   COD_NDG_GARANTITO,
   COD_NDG_GARANTE,
   VAL_IMPORTO,
   COD_TIPO_GARANZIA
)
AS
   SELECT "COD_ABI",
          "COD_GARANZIA",
          "COD_FORMA_TECNICA",
          "DESC_FORMA_TECNICA",
          "DTA_PERFEZIONAMENTO",
          "COD_NDG_GARANTITO",
          "COD_NDG_GARANTE",
          "VAL_IMPORTO",
          "COD_TIPO_GARANZIA"
     FROM V_MCREI_APP_GARANZIE_PROPOSTA;
