/* Formatted on 21/07/2014 18:39:05 (QP5 v5.227.12220.39754) */
CREATE OR REPLACE FORCE VIEW MCRE_OWN.V_MCREI_APP_BENI
(
   ID_DPER,
   ID_LOGICAL_BENE,
   COD_ABI,
   COD_UO_BENE,
   COD_BENE,
   DESC_EX_TIPO_BENE,
   COD_TIPO_BENE,
   DESC_COD_TIPO_BENE,
   COD_STATO_BENE,
   DESC_COMUNE,
   COD_PROVINCIA,
   DESC_LOCALITA,
   DESC_INDIRIZZO,
   DESC_BENE,
   DESC_NOTA_BENE,
   DTA_INS_BENE,
   DTA_UPD_BENE,
   DTA_CANCELLAZIONE,
   DTA_VISURA,
   COD_CONSERVATORIA,
   DESC_CONSERVATORIA,
   COD_CESPITE,
   COD_FOGL_MAP_SUB,
   FOGLIO,
   MAPPALE,
   SUBALTERNO,
   VAL_PROGR_BENE_CESP,
   COD_TIPO_DENUNCIA,
   VAL_NUM_DENUNCIA,
   VAL_ANNO_DENUNCIA,
   COD_TIPO,
   COD_CATASTO,
   VAL_NUM_VANI,
   COD_PIANO,
   COD_INTERNO,
   COD_SCALA,
   VAL_SUPERFICIE,
   FLG_PRES_SOLAIO,
   FLG_PRES_CANTINA,
   FLG_PRES_SERVIZI,
   VAL_NUM_RENDITA,
   COD_DIVISA,
   COD_TIPOLOGIA_TERRENO,
   COD_SNDG,
   COD_NDG,
   COD_DIRITTO,
   DESC_DIRITTO,
   VAL_QUOTA_DIR,
   DTA_INS,
   DTA_UPD,
   DTA_DELETE,
   FLG_MANUALE,
   FLG_TIPO_DATO,
   DESC_INTESTATARIO
)
AS
   SELECT id_dper,
          id_logical_bene,
          cod_abi,
          cod_uo_bene,
          cod_bene,
          desc_ex_tipo_bene,
          b.cod_tipo_bene,
          desc_cod_tipo_bene,
          cod_stato_bene,
          desc_comune,
          cod_provincia,
          desc_localita,
          desc_indirizzo,
          desc_bene,
          desc_nota_bene,
          dta_ins_bene,
          dta_upd_bene,
          dta_cancellazione,
          dta_visura,
          cod_conservatoria,
          desc_conservatoria,
          cod_cespite,
          cod_fogl_map_sub,
          SUBSTR (cod_fogl_map_sub, 1, 7) AS foglio,
          SUBSTR (cod_fogl_map_sub, 8, 8) AS mappale,
          SUBSTR (cod_fogl_map_sub, 16, 10) AS subalterno,
          val_progr_bene_cesp,
          cod_tipo_denuncia,
          val_num_denuncia,
          val_anno_denuncia,
          cod_tipo,
          cod_catasto,
          val_num_vani,
          cod_piano,
          cod_interno,
          cod_scala,
          val_superficie,
          flg_pres_solaio,
          flg_pres_cantina,
          flg_pres_servizi,
          val_num_rendita,
          cod_divisa,
          cod_tipologia_terreno,
          cod_sndg,
          cod_ndg,
          cod_diritto,
          desc_dominio AS desc_diritto,
          val_quo_diritto AS val_quota_dir,
          dta_ins,
          dta_upd,
          dta_delete,
          flg_manuale,
          flg_tipo_dato,
          desc_intestatario
     FROM t_mcrei_app_beni b, t_mcrei_cl_domini d, t_mcrei_cl_tipo_bene t
    WHERE     TRIM (b.cod_tipo_bene) = TRIM (t.cod_tipo_bene(+))
          AND TRIM (d.cod_dominio(+)) = 'COD_DIRITTO'
          AND TRIM (b.cod_diritto) = TRIM (d.val_dominio(+));
