/* Formatted on 21/07/2014 18:36:19 (QP5 v5.227.12220.39754) */
CREATE OR REPLACE FORCE VIEW MCRE_OWN.V_MCRE0_APP_STORICO_GESTORI
(
   COD_ABI_CARTOLARIZZATO,
   COD_NDG,
   DTA_INI_UTENTE,
   DTA_FINE_VALIDITA,
   ID_UTENTE,
   UTENTE,
   COD_STATO,
   COD_STRUTTURA_COMPETENTE
)
AS
     SELECT COD_ABI_CARTOLARIZZATO,
            COD_NDG,
            TRUNC (DTA_INI_UTENTE) AS dta_inizio,
            TRUNC (DTA_FINE_VALIDITA) AS dta_fine,
            ID_UTENTE,
            UTENTE,
            COD_STATO,
            COD_STRUTTURA_COMPETENTE
       FROM T_MCRE0_APP_STORICO_GESTORI
      WHERE (FLG_PROV, FLG_ATTIVO) NOT IN (SELECT 'F', '1' FROM DUAL)
   ORDER BY DTA_INI_UTENTE;
