/* Formatted on 21/07/2014 18:40:24 (QP5 v5.227.12220.39754) */
CREATE OR REPLACE FORCE VIEW MCRE_OWN.V_MCREI_APP_LISTA_PARERI_GEM
(
   COD_ABI,
   COD_NDG,
   DESC_CAUSA_INCAGLIO,
   DESC_PROVVEDIMENTI_PRESI,
   DESC_CAUSA_SOFFERENZA,
   DESC_PROVVEDIMENTI_ASSUNTI,
   DESC_PROVVEDIMENTI_LEGALI
)
AS
   SELECT COD_ABI,
          COD_NDG,
          CASE WHEN COD_TIPO_PAR = 'F01' THEN DESC_PARERE ELSE NULL END
             AS DESC_CAUSA_INCAGLIO,
          CASE WHEN COD_TIPO_PAR = 'F02' THEN DESC_PARERE ELSE NULL END
             AS DESC_PROVVEDIMENTI_PRESI,
          CASE WHEN COD_TIPO_PAR = 'F01' THEN DESC_PARERE ELSE NULL END
             AS DESC_CAUSA_SOFFERENZA,                          -- DA RIVEDERE
          CASE WHEN COD_TIPO_PAR = 'A01' THEN DESC_PARERE ELSE NULL END
             AS DESC_PROVVEDIMENTI_ASSUNTI,                     -- DA RIVEDERE
          CASE WHEN COD_TIPO_PAR = 'A07' THEN DESC_PARERE ELSE NULL END
             AS DESC_PROVVEDIMENTI_LEGALI                       -- DA RIVEDERE
     FROM T_MCREI_APP_PARERI;
