/* Formatted on 21/07/2014 18:33:24 (QP5 v5.227.12220.39754) */
CREATE OR REPLACE FORCE VIEW MCRE_OWN.V_MCRE0_APP_DATE_MATRICE_SA
(
   DTA_RIFERIMENTO_FLUSSO,
   DTA_AGGIORNAMENTO_PCR
)
AS
   SELECT TO_DATE (id_dper, 'YYYYMMDD') AS DTA_RIFERIMENTO_FLUSSO,
          TRUNC (dta_upd) AS DTA_AGGIORNAMENTO_PCR
     FROM t_mcrei_app_pcr_rapporti
    WHERE ROWNUM < 2;
