/* Formatted on 21/07/2014 18:39:00 (QP5 v5.227.12220.39754) */
CREATE OR REPLACE FORCE VIEW MCRE_OWN.V_MCREI_APP_ALERT_DEL_DA_CONF
(
   COD_ABI_CARTOLARIZZATO,
   COD_ABI_ISTITUTO,
   COD_COMPARTO_POSIZIONE,
   COD_COMPARTO_UTENTE,
   COD_GRUPPO_ECONOMICO,
   COD_MACROSTATO,
   COD_NDG,
   COD_PRIV,
   COD_PROCESSO,
   COD_RAMO_CALCOLATO,
   COD_SNDG,
   COD_STATO,
   COD_STRUTTURA_COMPETENTE_AR,
   COD_STRUTTURA_COMPETENTE_DC,
   COD_STRUTTURA_COMPETENTE_FI,
   COD_STRUTTURA_COMPETENTE_RG,
   DESC_COGNOME,
   DESC_ISTITUTO,
   DESC_NOME,
   DESC_NOME_CONTROPARTE,
   DESC_STRUTTURA_COMPETENTE_AR,
   DESC_STRUTTURA_COMPETENTE_DC,
   DESC_STRUTTURA_COMPETENTE_FI,
   DESC_STRUTTURA_COMPETENTE_RG,
   DTA_DECORRENZA_STATO,
   DTA_INS_ALERT,
   DTA_SCADENZA_STATO,
   DTA_UTENTE_ASSEGNATO,
   FLG_ABI_LAVORATO,
   FLG_GESTORE_ABILITATO,
   ID_REFERENTE,
   ID_UTENTE,
   VAL_ALERT,
   VAL_ANA_GRE,
   VAL_ORDINE_COLORE,
   DTA_INS_STATO_PROPOSTO,
   COD_MICRO_TIPOL,
   DESC_MICRO_TIPOL,
   COD_PROTOCOLLO_PACCHETTO
)
AS
   SELECT AD.COD_ABI_CARTOLARIZZATO,
          AD.COD_ABI_ISTITUTO,
          AD.COD_COMPARTO_ASSEGNATO AS COD_COMPARTO_POSIZIONE,
          UT.COD_COMPARTO_UTENTE,
          AD.COD_GRUPPO_ECONOMICO,
          AD.COD_MACROSTATO,
          AD.COD_NDG,
          UT.COD_PRIV,
          AD.COD_PROCESSO,
          AD.COD_RAMO_CALCOLATO,
          AD.COD_SNDG,
          AD.COD_STATO,
          ORG.COD_STRUTTURA_COMPETENTE_AR,
          ORG.COD_STRUTTURA_COMPETENTE_DC,
          ORG.COD_STRUTTURA_COMPETENTE_FI,
          ORG.COD_STRUTTURA_COMPETENTE_RG,
          UT.COGNOME,
          AD.DESC_ISTITUTO,
          UT.NOME,
          AD.DESC_NOME_CONTROPARTE,
          ORG.DESC_STRUTTURA_COMPETENTE_AR,
          ORG.DESC_STRUTTURA_COMPETENTE_DC,
          ORG.COD_STRUTTURA_COMPETENTE_FI,
          ORG.COD_STRUTTURA_COMPETENTE_RG,
          AD.DTA_DECORRENZA_STATO,
          SYSDATE AS DTA_INS_ALERT,
          AD.DTA_SCADENZA_STATO,
          AD.DTA_UTENTE_ASSEGNATO,
          '1' AS FLG_ABI_LAVORATO,
          UT.FLG_GESTORE_ABILITATO,
          UT.ID_REFERENTE,
          UT.ID_UTENTE,
          CASE
             WHEN TRUNC (SYSDATE) - D.DTA_UPD_FASE_PACCHETTO < 3
             --                      AND DTA_SCADENZA_STATO - TRUNC(SYSDATE) >= 15
             THEN
                'V'
             WHEN     TRUNC (SYSDATE) - D.DTA_UPD_FASE_PACCHETTO < 5
                  AND TRUNC (SYSDATE) - D.DTA_UPD_FASE_PACCHETTO > 2
             THEN
                'G'
             WHEN TRUNC (SYSDATE) - D.DTA_UPD_FASE_PACCHETTO > 4
             THEN
                'R'
          END
             AS VAL_ALERT,
          AD.DESC_GRUPPO_ECONOMICO AS VAL_ANA_GRE,
          CASE
             WHEN TRUNC (SYSDATE) - D.DTA_UPD_FASE_PACCHETTO < 3
             --                      AND DTA_SCADENZA_STATO - TRUNC(SYSDATE) >= 15
             THEN
                1
             WHEN     TRUNC (SYSDATE) - D.DTA_UPD_FASE_PACCHETTO < 5
                  AND TRUNC (SYSDATE) - D.DTA_UPD_FASE_PACCHETTO > 2
             THEN
                6
             WHEN TRUNC (SYSDATE) - D.DTA_UPD_FASE_PACCHETTO > 4
             THEN
                11
          END
             AS VAL_ORDINE_COLORE,
          D.DTA_INS_DELIBERA AS DTA_INS_STATO_PROPOSTO,
          D.COD_MICROTIPOLOGIA_DELIB AS COD_MICRO_TIPOL,
          TIP.DESC_MICROTIPOLOGIA AS DESC_MICRO_TIPOL,
          D.COD_PROTOCOLLO_PACCHETTO AS COD_PROTOCOLLO_PACCHETTO
     FROM T_MCREI_APP_DELIBERE D,
          T_MCRE0_APP_ALL_DATA AD,
          T_MCRE0_APP_UTENTI UT,
          T_MCREI_CL_TIPOLOGIE TIP,
          V_MCRE0_DENORM_STR_ORG ORG
    WHERE     D.COD_ABI = AD.COD_ABI_CARTOLARIZZATO
          AND D.COD_NDG = AD.COD_NDG
          AND AD.ID_UTENTE = UT.ID_UTENTE
          AND D.COD_ABI = ORG.COD_ABI_ISTITUTO_FI(+)
          AND D.COD_FILIALE_DELIBERA = COD_STRUTTURA_COMPETENTE_FI(+)
          AND D.COD_MICROTIPOLOGIA_DELIB = TIP.COD_MICROTIPOLOGIA(+)
          AND D.COD_FASE_PACCHETTO = 'ANM'


-- T_MCRE0_APP_ALERT_DEL_DA_CONF
;
