/* Formatted on 21/07/2014 18:39:21 (QP5 v5.227.12220.39754) */
CREATE OR REPLACE FORCE VIEW MCRE_OWN.V_MCREI_APP_DATI_CONTABILI_RAP
(
   COD_ABI,
   COD_NDG,
   COD_SNDG,
   COD_STATO,
   DTA_DECORRENZA_STATO,
   DESC_NOME_CONTROPARTE,
   VAL_ACCORDATO_CASSA,
   VAL_ACCORDATO_FIRMA,
   VAL_ACCORDATO_DERIVATI,
   VAL_UTILIZZATO_CASSA,
   VAL_UTILIZZATO_FIRMA,
   VAL_UTILIZZATO_DERIVATI,
   VAL_RETTIFICATO_CASSA,
   VAL_RETTIFICATO_FIRMA,
   VAL_RETTIFICATO_DERIVATI,
   VAL_ATTUALIZZAZIONE,
   VAL_STRALCIO_BREVE,
   VAL_STRALCIO_MLT,
   FLG_RECUPERO,
   FLG_DATO_FORZATO,
   FLG_RISTRUTTURAZIONE
)
AS
   SELECT NULL AS COD_ABI,
          NULL AS COD_NDG,
          NULL AS COD_SNDG,
          NULL AS COD_STATO,
          TO_DATE (NULL, 'DD/MM/YYYY') AS DTA_DECORRENZA_STATO,
          NULL AS DESC_NOME_CONTROPARTE, --DENOMINAZIONE_SNDG,DENOMINAZIONE_NDG, da all_Data
          NULL AS VAL_ACCORDATO_CASSA,
          NULL AS VAL_ACCORDATO_FIRMA,
          NULL AS VAL_ACCORDATO_DERIVATI,
          NULL AS VAL_UTILIZZATO_CASSA,
          NULL AS VAL_UTILIZZATO_FIRMA,
          NULL AS VAL_UTILIZZATO_DERIVATI,
          NULL AS VAL_RETTIFICATO_CASSA,
          NULL AS VAL_RETTIFICATO_FIRMA,
          NULL AS VAL_RETTIFICATO_DERIVATI,
          NULL AS VAL_ATTUALIZZAZIONE,
          NULL AS VAL_STRALCIO_BREVE,
          NULL AS VAL_STRALCIO_MLT,
          NULL AS FLG_RECUPERO,
          NULL AS FLG_DATO_FORZATO,
          NULL AS FLG_RISTRUTTURAZIONE
     FROM DUAL;
