/* Formatted on 21/07/2014 18:43:38 (QP5 v5.227.12220.39754) */
CREATE OR REPLACE FORCE VIEW MCRE_OWN.V_MCRES_CL_PRODOTTI_SOFF
(
   COD_TIPO_SOFF,
   VAL_DESC_TIPO_SOFF,
   FLG_FILIALE,
   FLG_PRESIDIO,
   FLG_AUTOMATICA,
   FLG_DISMESSA,
   DTA_INS,
   MATRICOLA_INS
)
AS
   SELECT COD_TIPO_SOFF,
          VAL_DESC_TIPO_SOFF,
          FLG_FILIALE,
          FLG_PRESIDIO,
          FLG_AUTOMATICA,
          FLG_DISMESSA,
          DTA_INS,
          MATRICOLA_INS
     FROM T_MCRES_CL_PRODOTTI_SOFF;
