/* Formatted on 21/07/2014 18:34:35 (QP5 v5.227.12220.39754) */
CREATE OR REPLACE FORCE VIEW MCRE_OWN.V_MCRE0_APP_POS_USCITE_RIPORT
(
   VAL_ALERT,
   VAL_ORDINE_COLORE,
   DTA_INS_ALERT,
   COD_SNDG,
   COD_ABI_CARTOLARIZZATO,
   COD_ABI_ISTITUTO,
   COD_GRUPPO_ECONOMICO,
   VAL_ANA_GRE,
   COD_STRUTTURA_COMPETENTE_DC,
   DESC_STRUTTURA_COMPETENTE_DC,
   COD_STRUTTURA_COMPETENTE_RG,
   DESC_STRUTTURA_COMPETENTE_RG,
   COD_STRUTTURA_COMPETENTE_AR,
   DESC_STRUTTURA_COMPETENTE_AR,
   COD_STRUTTURA_COMPETENTE_FI,
   DESC_STRUTTURA_COMPETENTE_FI,
   COD_PROCESSO,
   COD_STATO,
   DTA_DECORRENZA_STATO,
   DTA_SCADENZA_STATO,
   ID_UTENTE,
   DTA_UTENTE_ASSEGNATO,
   DESC_NOME,
   DESC_COGNOME,
   DTA_LAST_RIPORTAF,
   ID_UTENTE_PRE
)
AS
   SELECT ALERT_10 VAL_ALERT,
          (SELECT DECODE (
                     ALERT_10,
                     'V', VAL_VERDE,
                     DECODE (ALERT_10,
                             'A', VAL_ARANCIO,
                             DECODE (ALERT_10, 'R', VAL_ROSSO, NULL)))
             FROM T_MCRE0_APP_ALERT
            WHERE ID_ALERT = 10)
             VAL_ORDINE_COLORE,
          DTA_INS_10 DTA_INS_ALERT,
          A.COD_SNDG,
          A.COD_ABI_CARTOLARIZZATO,
          A.COD_ABI_ISTITUTO,
          X.COD_GRUPPO_ECONOMICO,
          X.DESC_GRUPPO_ECONOMICO VAL_ANA_GRE,
          X.COD_STRUTTURA_COMPETENTE_DC,
          X.DESC_STRUTTURA_COMPETENTE_DC,
          X.COD_STRUTTURA_COMPETENTE_RG,
          X.DESC_STRUTTURA_COMPETENTE_RG,
          X.COD_STRUTTURA_COMPETENTE_AR,
          X.DESC_STRUTTURA_COMPETENTE_AR,
          X.COD_STRUTTURA_COMPETENTE_FI,
          X.DESC_STRUTTURA_COMPETENTE_FI,
          X.COD_PROCESSO,
          X.COD_STATO,
          X.DTA_DECORRENZA_STATO,
          X.DTA_SCADENZA_STATO,
          X.ID_UTENTE,
          X.DTA_UTENTE_ASSEGNATO,
          X.NOME DESC_NOME,
          X.COGNOME DESC_COGNOME,
          X.DTA_LAST_RIPORTAF,
          A.ID_UTENTE_PRE
     FROM V_MCRE0_APP_ALERT_POS A,        --          MV_MCRE0_APP_ISTITUTI I,
                                  --          T_MCRE0_APP_ANAGRAFICA_GRUPPO G,
           V_MCRE0_APP_UPD_FIELDS X
    --          T_MCRE0_APP_ANAGR_GRE GE,
    --          MV_MCRE0_DENORM_STR_ORG S,
    --          T_MCRE0_APP_UTENTI U
    WHERE     ALERT_10 IS NOT NULL
          AND X.COD_ABI_CARTOLARIZZATO = A.COD_ABI_CARTOLARIZZATO
          AND X.COD_NDG = A.COD_NDG;
