/* Formatted on 21/07/2014 18:40:57 (QP5 v5.227.12220.39754) */
CREATE OR REPLACE FORCE VIEW MCRE_OWN.V_MCREI_DAY_POSMCI
(
   ID_DPER,
   COD_ABI,
   COD_NDG,
   ESPOSIZIONE_OGGI,
   ESPOSIZIONE_IERI,
   ID_UTENTE
)
AS
   SELECT TO_NUMBER (DATA_FLUSSO) AS ID_DPER,
          COD_ABI,
          LPAD (COD_NDG, 16, '0') AS cod_ndg,
          ESPOSIZIONE_OGGI,
          ESPOSIZIONE_IERI,
          NVL (GESTORE, '-1') AS ID_UTENTE
     FROM TE_MCREI_POSMCI;
