/* Formatted on 21/07/2014 18:34:37 (QP5 v5.227.12220.39754) */
CREATE OR REPLACE FORCE VIEW MCRE_OWN.V_MCRE0_APP_PREGIUDIZIEVOLI
(
   COD_SNDG,
   COD_TIPO_NOTIZIA,
   DTA_ELABORAZIONE,
   DESC_TIPO_NOTIZIA
)
AS
   SELECT COD_SNDG,
          COD_TIPO_NOTIZIA,
          DTA_ELABORAZIONE,
          DESC_TIPO_NOTIZIA
     FROM (SELECT COD_SNDG,
                  COD_TIPO_NOTIZIA,
                  DTA_ELABORAZIONE,
                  DESC_TIPO_NOTIZIA,
                  RANK ()
                  OVER (PARTITION BY cod_sndg ORDER BY DTA_ELABORAZIONE DESC)
                     LAST_5
             FROM T_MCRE0_APP_PREGIUDIZIEVOLI) A
    WHERE LAST_5 < 6;
