/* Formatted on 21/07/2014 18:42:26 (QP5 v5.227.12220.39754) */
CREATE OR REPLACE FORCE VIEW MCRE_OWN.V_MCRES_APP_NOTIZIE_PTF_DETT
(
   COD_ABI,
   COD_NDG,
   COD_TIPO_NOTIZIA,
   DESC_NOTIZIA
)
AS
   SELECT cod_abi,
          cod_ndg,
          COD_TIPO_NOTIZIA,
          DESC_NOTIZIA
     FROM T_MCRES_APP_NOTIZIE
    WHERE     COD_TIPO_NOTIZIA IN (1, 2, 85)
          AND DTA_FINE_VALIDITA = TO_DATE ('99991231', 'YYYYMMDD');
