/* Formatted on 21/07/2014 18:42:29 (QP5 v5.227.12220.39754) */
CREATE OR REPLACE FORCE VIEW MCRE_OWN.V_MCRES_APP_OPERAZ_PROVV_MO03
(
   ID,
   COD_ABI,
   COD_NDG,
   COD_CAUSALE,
   DTA_CONTABILE,
   VAL_DESC_CAUSALE,
   VAL_IMPORTO,
   DTA_VALUTA,
   DTA_INSERT,
   FLG_CANCEL,
   DTA_CANCEL,
   COD_TIPO_CONTROPART,
   VAL_DENOMINAZIONE_CLI,
   COD_FILIALE,
   VAL_ORDINANTE,
   VAL_MOTIVAZIONE,
   MATR_INS,
   MATR_CANC,
   COD_FILIALE_OPER
)
AS
   SELECT ID,
          COD_ABI,
          COD_NDG,
          COD_CAUSALE,
          DTA_CONTABILE,
          VAL_DESC_CAUSALE,
          VAL_IMPORTO,
          DTA_VALUTA,
          DTA_INSERT,
          FLG_CANCEL,
          DTA_CANCEL,
          COD_TIPO_CONTROPART,
          -- AP 14/05/2014 REQF-FU-5.5
          VAL_DENOMINAZIONE_CLI,
          COD_FILIALE,
          VAL_ORDINANTE,
          VAL_MOTIVAZIONE,
          MATR_INS,
          MATR_CANC,
          COD_FILIALE_OPER
     FROM T_MCRES_APP_MOV_PROPOS;
