/* Formatted on 21/07/2014 18:43:39 (QP5 v5.227.12220.39754) */
CREATE OR REPLACE FORCE VIEW MCRE_OWN.V_MCRES_CL_RACCORDO_PROD
(
   COD_TIPO_SOFFERENZA,
   VAL_DESC_SOFFERENZA,
   COD_FORMA_TECNICA,
   VAL_DESC_FORMA_TECNICA,
   DTA_INS,
   MATRICOLA_INS
)
AS
   SELECT A.COD_TIPO_SOFFERENZA,
          B.VAL_DESC_TIPO_SOFF VAL_DESC_SOFFERENZA,
          A.COD_FORMA_TECNICA,
          (SELECT VAL_DESC_FORMA_TECNICA
             FROM T_MCRES_CL_FORME_TECNICHE x
            WHERE x.COD_FORMA_TECNICA = a.COD_FORMA_TECNICA)
             VAL_DESC_FORMA_TECNICA,
          A.DTA_INS,
          A.MATRICOLA_INS
     FROM T_MCRES_CL_RACCORDO_PROD A
          JOIN T_MCRES_CL_PRODOTTI_SOFF B
             ON A.COD_TIPO_SOFFERENZA = B.COD_TIPO_SOFF
    WHERE B.FLG_FILIALE = 'S' AND a.flg_active = 1;
