/* Formatted on 21/07/2014 18:37:07 (QP5 v5.227.12220.39754) */
CREATE OR REPLACE FORCE VIEW MCRE_OWN.V_MCRE0_LIV_CRIT_PERCORSI
(
   ID_DPER,
   COD_ABI,
   COD_NDG,
   FL_SEMAFORO,
   NOTE,
   COD_STATO_PRE,
   COD_PROCESSO,
   COD_PERCORSO,
   DTA_SCADENZA,
   DTA_TIMESTAMP,
   COD_STATO,
   MATR_AGG
)
AS
   SELECT ID_DPER,
          COD_ABI,
          COD_NDG,
          FL_SEMAFORO,
          NOTE,
          COD_STATO_PRE,
          COD_PROCESSO,
          TO_NUMBER (COD_PERCORSO) AS COD_PERCORSO,
          TO_DATE (DTA_SCADENZA, 'DD/MM/YYYY HH24.MI.SS') AS DTA_SCADENZA,
          TO_DATE (DTA_TIMESTAMP, 'DD/MM/YYYY HH24.MI.SS') AS DTA_TIMESTAMP,
          COD_STATO,
          MATR_AGG
     FROM mcre_own.TE_MCRE0_LIV_CRIT_ST_PERCORSI;
