/* Formatted on 21/07/2014 18:37:06 (QP5 v5.227.12220.39754) */
CREATE OR REPLACE FORCE VIEW MCRE_OWN.V_MCRE0_LIV_CRIT
(
   ID_DPER,
   COD_ABI,
   COD_NDG,
   FL_SEMAFORO,
   NOTE,
   DTA_TIMESTAMP,
   MATR_AGG
)
AS
   SELECT ID_DPER,
          COD_ABI,
          COD_NDG,
          FL_SEMAFORO,
          NOTE,
          TO_DATE (DTA_TIMESTAMP, 'DD/MM/YYYY HH24.MI.SS') AS DTA_TIMESTAMP,
          MATR_AGG
     FROM mcre_own.TE_MCRE0_LIV_CRIT;
