CREATE OR REPLACE FORCE VIEW MCRE_OWN.V_MCRE0_APP_LGD_PAR_S AS
SELECT
ID_DPER,COD_ABI,COD_NDG,DTA_RIF_SISBA,COD_RAPP_UO,COD_RAPP_PROD,COD_RAPP_NUM,COD_RAPP_SISBA,COD_TIPO_RISCHIO,
COD_SEGMENTO_ECO,VAL_R014_MORTAGE,COD_TIPO_PROD,COD_AREA_GEO_ORIG,COD_AREA_GEO,COD_ST_GIUR_ORIG,COD_NAT_GIUR,
DTA_VAL_RISCHIO,VAL_TPERM_ST_RICHIO,FLG_CASSA_FIRMA,COD_FTC_SISBA_ORIG,COD_R791_PR_FTC_SISBA,COD_FTC_LGD_ORIG,
COD_FTC_LGD,COD_TIPO_LEASING,COD_TIPO_ESP_FACT,FLG_PRES_ASSICUR,VAL_CAP_PIU_INT,VAL_INT_MORA,VAL_IMP_RATA_MORA,
VAL_IMP_CRE_FIRMA,VAL_IMP_STO_INT_MUT,VAL_ESP_FSC_CL_CAS,VA_ESP_FSC_CL_FIR,VAL_ESP_FSC_RAPP,VAL_IMP_GAR_IPOT,
VAL_COP_GAR_IPOT,VAL_COP_GAR_IPOT_RAPP,VAL_PERC_LGD_IPO,VAL_RETT_VAL_IPO,VAL_GAR_PIGN,VAL_COP_GAR_PIGN_RAPP,
VAL_PERC_LGD_PIGN,VAL_RETT_VAL_PIGN,VAL_GAR_PERS,VAL_COP_GAR_PERS_RAPP,VAL_PERC_LGD_PERS,VAL_RETT_VAL_PERS,
VAL_CAP_RAPP_NON_GAR,VAL_PERC_LGD_NON_GAR,VAL_RETT_VAL_NON_GAR,VAL_RETT_TOTALE,VAL_RETT_TOT_PIU_MORA,
VAL_MM_PIANO,VAL_VALORE_ATTUALE,VAL_COSTO_ATTUALIZ,DTA_INS,DTA_PERIODO,
VAL_MM_PIANO VAL_TMR_1, 24 VAL_TMR_2,
CASE
  WHEN VAL_PERC_LGD_IPO>0 THEN VAL_PERC_LGD_IPO
  WHEN VAL_PERC_LGD_PIGN>0 THEN VAL_PERC_LGD_PIGN
  WHEN VAL_PERC_LGD_PERS>0 THEN VAL_PERC_LGD_PERS
  WHEN VAL_PERC_LGD_NON_GAR>0 THEN VAL_PERC_LGD_NON_GAR
  ELSE 0
END VAL_PERC_LGD,
CASE
  WHEN VAL_PERC_LGD_IPO>0 THEN 'IP'
  WHEN VAL_PERC_LGD_PIGN>0 THEN 'PG'
  WHEN VAL_PERC_LGD_PERS>0 THEN 'PE'
  WHEN VAL_PERC_LGD_NON_GAR>0 THEN 'UN'
  ELSE NULL
END COD_TIPO_GAR,
CASE
  WHEN VAL_PERC_LGD_IPO>0 THEN 'IPOTECARIA'
  WHEN VAL_PERC_LGD_PIGN>0 THEN 'PIGNORATIZIA'
  WHEN VAL_PERC_LGD_PERS>0 THEN 'PERSONALE'
  WHEN VAL_PERC_LGD_NON_GAR>0 THEN 'UNSECURED'
  ELSE NULL
END DESC_TIPO_GAR
FROM T_MCRE0_APP_LGD_PAR_S;

GRANT SELECT ON MCRE_OWN.V_MCRE0_APP_LGD_PAR_S TO MCRE_APP;
GRANT SELECT ON MCRE_OWN.V_MCRE0_APP_LGD_PAR_S TO MCRE_USR;
CREATE OR REPLACE PUBLIC SYNONYM V_MCRE0_APP_LGD_PAR_S FOR MCRE_OWN.V_MCRE0_APP_LGD_PAR_S;