/* Formatted on 21/07/2014 18:41:49 (QP5 v5.227.12220.39754) */
CREATE OR REPLACE FORCE VIEW MCRE_OWN.V_MCRES_APP_CONFERIMENTO_NTOLD
(
   COD_ABI,
   COD_NDG
)
AS
   SELECT DISTINCT cod_abi, cod_ndg
     FROM t_mcres_app_notizie n
    WHERE     N.COD_TIPO_NOTIZIA = '05'
          AND SYSDATE BETWEEN N.DTA_INIZO_VALIDITA AND N.DTA_FINE_VALIDITA;
