/* Formatted on 21/07/2014 18:44:31 (QP5 v5.227.12220.39754) */
CREATE OR REPLACE FORCE VIEW MCRE_OWN.V_MCRES_ULTIMA_ACQ_FILE
(
   COD_FILE,
   COD_ABI,
   COD_FLUSSO,
   ID_FLUSSO,
   DTA_DPER,
   ID_DPER,
   VAL_ANNOMESE,
   VAL_ANNO
)
AS
   SELECT                                      -- V1    07/02/2012 VG: CREATED
          -- V1.1  16/03/2012 AG: to_number
          COD_FILE,
          W.COD_ABI,
          W.COD_FLUSSO,
          ID_FLUSSO ID_FLUSSO,
          ID_DPER DTA_DPER,
          TO_NUMBER (TO_CHAR (ID_DPER, 'YYYYMMDD')) ID_DPER,
          TO_NUMBER (TO_CHAR (ID_DPER, 'YYYYMM')) VAL_ANNOMESE,
          TO_NUMBER (TO_CHAR (ID_DPER, 'YYYY')) VAL_ANNO
     FROM MCRE_OWN.T_MCRES_WRK_last_ACQUISIZIONE W
    WHERE COD_STATO IN ('CARICATO', 'CARICATO_APP');
