/* Formatted on 21/07/2014 18:42:46 (QP5 v5.227.12220.39754) */
CREATE OR REPLACE FORCE VIEW MCRE_OWN.V_MCRES_APP_REPORT_POSIZIONI
(
   ID_DPER,
   COD_ABI,
   COD_NDG,
   DTA_PASSAGGIO_SOFF,
   DTA_CHIUSURA,
   COD_STATO_RISCHIO,
   COD_STATO_GIURIDICO,
   FLG_ART_498,
   COD_UO_ART_498,
   FLG_FONDI_TERZI,
   FLG_RAPP_CARTOLARIZZATI,
   FLG_RAPP_ESTERI,
   FLG_CONFERIMENTO,
   DTA_CONFERIMENTO,
   COD_SNDG,
   FLG_ATTIVA,
   DTA_INS,
   DTA_UPD,
   COD_OPERATORE_INS_UPD,
   COD_FILIALE_PRINCIPALE
)
AS
   SELECT "ID_DPER",
          "COD_ABI",
          "COD_NDG",
          "DTA_PASSAGGIO_SOFF",
          "DTA_CHIUSURA",
          "COD_STATO_RISCHIO",
          "COD_STATO_GIURIDICO",
          "FLG_ART_498",
          "COD_UO_ART_498",
          "FLG_FONDI_TERZI",
          "FLG_RAPP_CARTOLARIZZATI",
          "FLG_RAPP_ESTERI",
          "FLG_CONFERIMENTO",
          "DTA_CONFERIMENTO",
          "COD_SNDG",
          "FLG_ATTIVA",
          "DTA_INS",
          "DTA_UPD",
          "COD_OPERATORE_INS_UPD",
          "COD_FILIALE_PRINCIPALE"
     FROM T_MCRES_APP_POSIZIONI P
    WHERE     FLG_ATTIVA = 1
          AND ID_DPER <
                 (SELECT TO_CHAR (ID_DPER - 5, 'YYYYMMDD')
                    FROM T_MCRES_WRK_LAST_ACQUISIZIONE A
                   WHERE COD_FLUSSO = 'POSIZIONI' AND A.COD_ABI = P.COD_ABI);
