/* Formatted on 21/07/2014 18:33:59 (QP5 v5.227.12220.39754) */
CREATE OR REPLACE FORCE VIEW MCRE_OWN.V_MCRE0_APP_GEST_GRAF_TP
(
   COD_SNDG,
   COD_ABI_CARTOLARIZZATO,
   COD_ABI_ISTITUTO,
   DESC_ISTITUTO,
   COD_NDG,
   COD_COMPARTO,
   COD_RAMO_CALCOLATO,
   DESC_NOME_CONTROPARTE,
   COD_GRUPPO_ECONOMICO,
   VAL_ANA_GRE,
   COD_STRUTTURA_COMPETENTE_DC,
   DESC_STRUTTURA_COMPETENTE_DC,
   COD_STRUTTURA_COMPETENTE_DV,
   DESC_STRUTTURA_COMPETENTE_DV,
   COD_STRUTTURA_COMPETENTE_RG,
   DESC_STRUTTURA_COMPETENTE_RG,
   COD_STRUTTURA_COMPETENTE_AR,
   DESC_STRUTTURA_COMPETENTE_AR,
   COD_STRUTTURA_COMPETENTE_FI,
   DESC_STRUTTURA_COMPETENTE_FI,
   COD_PROCESSO,
   COD_MACROSTATO,
   COD_STATO,
   DTA_DECORRENZA_STATO,
   DTA_SCADENZA_STATO,
   ID_UTENTE,
   DTA_UTENTE_ASSEGNATO,
   DESC_NOME,
   DESC_COGNOME,
   ID_REFERENTE,
   DTA_INSERIMENTO,
   TOT_AZIONI,
   COD_TIPOLOGIA_PRATICA,
   FLG_ESITO,
   FLG_STATUS,
   FLG_SG,
   DTA_SCADENZA,
   NOTE,
   COD_LIVELLO
)
AS
   SELECT X.COD_SNDG,
          X.COD_ABI_CARTOLARIZZATO,
          X.COD_ABI_ISTITUTO,
          X.DESC_ISTITUTO,
          X.COD_NDG,
          X.COD_COMPARTO,
          X.COD_RAMO_CALCOLATO,
          X.DESC_NOME_CONTROPARTE,
          X.COD_GRUPPO_ECONOMICO,
          X.DESC_GRUPPO_ECONOMICO AS VAL_ANA_GRE,
          X.COD_STRUTTURA_COMPETENTE_DC,
          X.DESC_STRUTTURA_COMPETENTE_DC,
          X.COD_STRUTTURA_COMPETENTE_DV,
          X.DESC_STRUTTURA_COMPETENTE_DV,
          X.COD_STRUTTURA_COMPETENTE_RG,
          X.DESC_STRUTTURA_COMPETENTE_RG,
          X.COD_STRUTTURA_COMPETENTE_AR,
          X.DESC_STRUTTURA_COMPETENTE_AR,
          X.COD_STRUTTURA_COMPETENTE_FI,
          X.DESC_STRUTTURA_COMPETENTE_FI,
          X.COD_PROCESSO,
          X.COD_MACROSTATO,
          X.COD_STATO,
          X.DTA_DECORRENZA_STATO,
          X.DTA_SCADENZA_STATO,
          NULLIF (X.ID_UTENTE, -1) AS ID_UTENTE,
          X.DTA_UTENTE_ASSEGNATO,
          X.NOME AS DESC_NOME,
          X.COGNOME AS DESC_COGNOME,
          X.ID_REFERENTE,
          A.DTA_INS AS DTA_INSERIMENTO,
          A.TOT_AZIONI,
          A.ID_TIPOLOGIA_PRATICA AS COD_TIPOLOGIA_PRATICA,
          A.FLG_ESITO_POSITIVO AS FLG_ESITO,
          A.FLG_COMPLETATA AS FLG_STATUS,
          CASE
             WHEN (X.FLG_GRUPPO_ECONOMICO = '0' AND X.FLG_GRUPPO_LEGAME = '0')
             THEN
                'S'
             WHEN (X.FLG_GRUPPO_ECONOMICO = '1' OR X.FLG_GRUPPO_LEGAME = '1')
             THEN
                'G'
             ELSE
                NULL
          END
             FLG_SG,
          A.DTA_SCADENZA,
          A.NOTE,
          X.COD_LIVELLO
     FROM V_MCRE0_APP_UPD_FIELDS X,
          T_MCRE0_APP_GEST_POSIZIONE G,
          (SELECT R.*,
                  COUNT (
                     *)
                  OVER (
                     PARTITION BY R.COD_ABI_CARTOLARIZZATO,
                                  R.COD_NDG,
                                  R.ID_TIPOLOGIA_PRATICA)
                     TOT_AZIONI
             FROM T_MCRE0_APP_GEST_PRATICA_FASI R
            WHERE R.FLG_DELETE = 'N') A
    WHERE     X.COD_ABI_CARTOLARIZZATO = G.COD_ABI_CARTOLARIZZATO
          AND G.COD_ABI_CARTOLARIZZATO = A.COD_ABI_CARTOLARIZZATO
          AND X.COD_NDG = G.COD_NDG
          AND G.COD_NDG = A.COD_NDG
          AND X.COD_MACROSTATO = G.COD_MACROSTATO
          AND G.COD_MACROSTATO = A.COD_MACROSTATO
          AND A.ID_TIPOLOGIA_PRATICA IS NOT NULL
          AND G.FLG_DELETE = 'N';
