/* Formatted on 21/07/2014 18:38:59 (QP5 v5.227.12220.39754) */
CREATE OR REPLACE FORCE VIEW MCRE_OWN.V_MCREI_ALERT_LOAD
(
   ID_ALERT,
   COD_ABI,
   COD_NDG,
   COD_SNDG,
   COD_STATO,
   VAL_ALERT,
   VAL_CNT_DELIBERE,
   VAL_CNT_RAPPORTI,
   COD_PROTOCOLLO_DELIBERA
)
AS
   SELECT 27 AS ID_ALERT,
          COD_ABI,
          COD_NDG,
          COD_SNDG,
          COD_STATO,
          VAL_ALERT,
          VAL_CNT_DELIBERE,
          VAL_CNT_RAPPORTI,
          COD_PROTOCOLLO_DELIBERA
     FROM V_MCRE0_WRK_ALERT_RAPP_DA_VAL
   UNION
   SELECT 29 AS ID_ALERT,
          COD_ABI,
          COD_NDG,
          COD_SNDG,
          COD_STATO,
          VAL_ALERT,
          VAL_CNT_DELIBERE,
          VAL_CNT_RAPPORTI,
          COD_PROTOCOLLO_DELIBERA
     FROM V_MCRE0_WRK_ALERT_INS_PIANO
   UNION
   SELECT 32 AS ID_ALERT,
          COD_ABI,
          COD_NDG,
          COD_SNDG,
          COD_STATO,
          VAL_ALERT,
          VAL_CNT_DELIBERE,
          VAL_CNT_RAPPORTI,
          COD_PROTOCOLLO_DELIBERA
     FROM V_MCRE0_WRK_ALERT_INRI_P_DAINS;
