
create or replace view V_MCRE0_LIV_CRIT_PERCORSI as
select 
  ID_DPER,
  COD_ABI,
  COD_NDG,
  FL_SEMAFORO,
  NOTE,
  COD_STATO_PRE,
  COD_PROCESSO,
  to_number(COD_PERCORSO) as COD_PERCORSO,
  to_date (DTA_SCADENZA,'DD/MM/YYYY HH24.MI.SS') as DTA_SCADENZA,
  to_date (DTA_TIMESTAMP,'DD/MM/YYYY HH24.MI.SS') as DTA_TIMESTAMP,
  COD_STATO,
  MATR_AGG
  from mcre_own.TE_MCRE0_LIV_CRIT_ST_PERCORSI;
  
  GRANT SELECT ON MCRE_OWN.V_MCRE0_LIV_CRIT_PERCORSI TO MCRE_USR;
