/* Formatted on 21/07/2014 18:35:45 (QP5 v5.227.12220.39754) */
CREATE OR REPLACE FORCE VIEW MCRE_OWN.V_MCRE0_APP_RIO_GESTIONE
(
   COD_MACROSTATO_DESTINAZIONE,
   FLG_WORKFLOW,
   COD_ABI_CARTOLARIZZATO,
   COD_NDG,
   DTA_INS,
   NOTE_CLASSIFICAZIONE,
   FLG_LETTURA_VERBALE,
   COD_MACROSTATO,
   COD_STATO,
   COD_SNDG,
   FLG_PRESA_IN_CARICO,
   DTA_UPD_WORKFLOW
)
AS
   SELECT A."COD_MACROSTATO_DESTINAZIONE",
          A."FLG_WORKFLOW",
          A."COD_ABI_CARTOLARIZZATO",
          A."COD_NDG",
          A."DTA_INS",
          A."NOTE_CLASSIFICAZIONE",
          A."FLG_LETTURA_VERBALE",
          X.COD_MACROSTATO,
          X.COD_STATO,
          x.cod_sndg,
          A.FLG_PRESA_IN_CARICo,
          A.DTA_UPD_WORKFLOW
     FROM T_MCRE0_APP_RIO_gestione A, V_MCRE0_APP_UPD_FIELDS_P1 X
    WHERE     A.COD_ABI_CARTOLARIZZATO = X.COD_ABI_CARTOLARIZZATO
          AND A.COD_NDG = X.COD_NDG
          AND a.flg_delete = 0;
