/* Formatted on 21/07/2014 18:43:37 (QP5 v5.227.12220.39754) */
CREATE OR REPLACE FORCE VIEW MCRE_OWN.V_MCRES_CL_FORME_TECNICHE
(
   COD_FORMA_TECNICA,
   VAL_DESC_FORMA_TECNICA,
   DTA_INS,
   MATRICOLA_INS
)
AS
   SELECT COD_FORMA_TECNICA,
          VAL_DESC_FORMA_TECNICA,
          DTA_INS,
          MATRICOLA_INS
     FROM T_MCRES_CL_FORME_TECNICHE;
