/* Formatted on 21/07/2014 18:42:47 (QP5 v5.227.12220.39754) */
CREATE OR REPLACE FORCE VIEW MCRE_OWN.V_MCRES_APP_REPORT_PRATICHE
(
   ID_DPER,
   COD_ABI,
   COD_NDG,
   VAL_ANNO,
   COD_PRATICA,
   DTA_APERTURA,
   DTA_CHIUSURA,
   COD_UO_PRATICA,
   COD_MATR_PRATICA,
   DTA_ASSEGN_ADDET,
   FLG_ATTIVA,
   DTA_INS,
   DTA_UPD,
   COD_OPERATORE_INS_UPD
)
AS
   SELECT "ID_DPER",
          "COD_ABI",
          "COD_NDG",
          "VAL_ANNO",
          "COD_PRATICA",
          "DTA_APERTURA",
          "DTA_CHIUSURA",
          "COD_UO_PRATICA",
          "COD_MATR_PRATICA",
          "DTA_ASSEGN_ADDET",
          "FLG_ATTIVA",
          "DTA_INS",
          "DTA_UPD",
          "COD_OPERATORE_INS_UPD"
     FROM T_MCRES_APP_PRATICHE P
    WHERE     FLG_ATTIVA = 1
          AND ID_DPER <
                 (SELECT TO_CHAR (ID_DPER - 5, 'YYYYMMDD')
                    FROM T_MCRES_WRK_LAST_ACQUISIZIONE A
                   WHERE COD_FLUSSO = 'PRATICHE' AND A.COD_ABI = P.COD_ABI);
