/* Formatted on 21/07/2014 18:32:46 (QP5 v5.227.12220.39754) */
CREATE OR REPLACE FORCE VIEW MCRE_OWN.V_MCRE0_APP_ALERT_RAPP_DAVAL_X
(
   VAL_ALERT,
   COD_STRUTTURA_COMPETENTE,
   COD_SNDG,
   COD_ABI_CARTOLARIZZATO,
   COD_ABI_ISTITUTO,
   COD_NDG,
   COD_GRUPPO_ECONOMICO,
   DESC_GRUPPO_ECONOMICO,
   COD_STRUTTURA_COMPETENTE_RG,
   DESC_STRUTTURA_COMPETENTE_RG,
   COD_STRUTTURA_COMPETENTE_AR,
   DESC_STRUTTURA_COMPETENTE_AR,
   COD_STRUTTURA_COMPETENTE_FI,
   DESC_STRUTTURA_COMPETENTE_FI,
   COD_STRUTTURA_COMPETENTE_DC,
   DESC_STRUTTURA_COMPETENTE_DC,
   COD_PROCESSO,
   COD_STATO,
   DTA_DECORRENZA_STATO_ATTUALE,
   COD_GESTORE,
   COD_COMPARTO_POSIZIONE,
   COD_COMPARTO_UTENTE,
   COD_MICROTIPOLOGIA,
   COD_PRIV,
   DESC_COGNOME,
   DESC_NOME_CONTROPARTE,
   DESC_NOME,
   ID_UTENTE,
   DTA_INS_ALERT,
   DTA_SCADENZA_STATO,
   DTA_UTENTE_ASSEGNATO,
   DESC_ISTITUTO,
   COD_PROTOCOLLO_DELIBERA,
   VAL_NUM_RAPPORTI,
   COD_PROTOCOLLO_PACCHETTO,
   VAL_RETT_PROGRESSIVA,
   FLG_ABI_LAVORATO,
   FLG_GESTORE_ABILITATO,
   ID_REFERENTE,
   VAL_ANA_GRE,
   VAL_ORDINE_COLORE,
   COD_FASE_DELIBERA,
   COD_RAMO_CALCOLATO,
   COD_MACROSTATO
)
AS
   SELECT POS.ALERT AS VAL_ALERT,
          AD.COD_STRUTTURA_COMPETENTE,
          AD.COD_SNDG,
          AD.COD_ABI_CARTOLARIZZATO,
          AD.COD_ABI_ISTITUTO,
          AD.COD_NDG,
          AD.COD_GRUPPO_ECONOMICO AS COD_GRUPPO_ECONOMICO,
          AD.DESC_GRUPPO_ECONOMICO AS DESC_GRUPPO_ECONOMICO,
          O.COD_STRUTTURA_COMPETENTE_RG,
          O.DESC_STRUTTURA_COMPETENTE_RG,
          O.COD_STRUTTURA_COMPETENTE_AR,
          O.DESC_STRUTTURA_COMPETENTE_AR,
          O.COD_STRUTTURA_COMPETENTE_FI,
          O.DESC_STRUTTURA_COMPETENTE_FI,
          O.COD_STRUTTURA_COMPETENTE_DC,
          O.DESC_STRUTTURA_COMPETENTE_DC,
          AD.COD_PROCESSO,
          AD.COD_STATO,
          AD.DTA_DECORRENZA_STATO AS DTA_DECORRENZA_STATO_ATTUALE,
          AD.COD_GESTORE_MKT AS COD_GESTORE,
          AD.COD_COMPARTO_ASSEGNATO AS COD_COMPARTO_POSIZIONE,
          U.COD_COMPARTO_UTENTE,
          POS.COD_MICROTIPOLOGIA_DELIBERA AS COD_MICROTIPOLOGIA,
          U.COD_PRIV,
          U.COGNOME AS DESC_COGNOME,
          AD.DESC_NOME_CONTROPARTE,
          U.NOME AS DESC_NOME,
          U.ID_UTENTE,
          POS.DTA_INS AS DTA_INS_ALERT,
          AD.DTA_SCADENZA_STATO,
          AD.DTA_UTENTE_ASSEGNATO,
          AD.DESC_ISTITUTO,
          POS.COD_PROTOCOLLO_DELIBERA,
          POS.VAL_CNT_RAPPORTI AS VAL_NUM_RAPPORTI,
          POS.COD_PROTOCOLLO_PACCHETTO,
          POS.VAL_RETT_PROGRESSIVA, -- A LIVELLO DI POSIZIONE, LA SOMMA, OPPURE L'ULTIMA ???
          '1' AS FLG_ABI_LAVORATO,
          U.FLG_GESTORE_ABILITATO,
          U.ID_REFERENTE,
          AD.DESC_GRUPPO_ECONOMICO AS VAL_ANA_GRE,
          POS.VAL_ORDINE_COLORE,
          POS.COD_FASE_DELIBERA,
          AD.COD_RAMO_CALCOLATO,
          AD.COD_MACROSTATO
     FROM (SELECT DISTINCT
                  ST.COD_ABI AS COD_ABI, -- POSIZIONI SENZA PIANI DI RECUPERO  E CON UTILIZZATO DIVERSO DA 0
                  ST.COD_NDG AS COD_NDG,
                  ST.COD_SNDG,
                  ST.COD_MICROTIPOLOGIA_DELIBERA,
                  ST.COD_PROTOCOLLO_DELIBERA,
                  ST.COD_PROTOCOLLO_PACCHETTO,
                  SUM (VAL_RETT_PROGRESSIVA)
                     OVER (PARTITION BY ST.COD_ABI, ST.COD_NDG)
                     AS VAL_RETT_PROGRESSIVA,
                  MIN (MIN_DTA) OVER (PARTITION BY ST.COD_ABI, ST.COD_NDG)
                     AS MIN_DTA,
                  VAL_CNT_RAPPORTI,
                  ALERT,
                  ST.DTA_INS,
                  ST.VAL_ORDINE_COLORE,
                  ST.COD_FASE_DELIBERA
             FROM (SELECT DISTINCT
                          S.COD_ABI,
                          S.COD_NDG,
                          S.COD_SNDG,
                          S.COD_RAPPORTO,
                          S.COD_MICROTIPOLOGIA_DELIBERA,
                          S.COD_PROTOCOLLO_DELIBERA,
                          DE.COD_PROTOCOLLO_PACCHETTO,
                          SUM (
                             S.VAL_RDV_TOT)
                          OVER (
                             PARTITION BY S.COD_ABI,
                                          S.COD_NDG,
                                          S.COD_RAPPORTO)
                             AS VAL_RETT_PROGRESSIVA,
                          MIN (DTA_STIMA)
                             OVER (PARTITION BY S.cod_abi, S.cod_ndg)
                             AS MIN_DTA,
                          PW.VAL_CNT_RAPPORTI,
                          PW.ALERT,
                          PW.DTA_INS,
                          PW.VAL_ORDINE_COLORE,
                          DE.COD_FASE_DELIBERA
                     FROM T_MCREI_APP_STIME PARTITION (INC_PATTIVE) S,
                          T_MCREI_APP_DELIBERE PARTITION (INC_PATTIVE) DE,
                          T_MCREI_APP_ALERT_POS_WRK PARTITION (INC_P01) PW -- CONDIZIONI DI ACCENSIONE ALERT "INTRINSECHE"
                    WHERE     S.COD_ABI = PW.COD_ABI
                          AND S.COD_NDG = PW.COD_NDG
                          AND S.FLG_ATTIVA = '1'
                          AND S.COD_ABI = DE.COD_ABI
                          AND S.COD_NDG = DE.COD_NDG
                          AND S.COD_PROTOCOLLO_DELIBERA =
                                 DE.COD_PROTOCOLLO_DELIBERA
                          AND DE.FLG_ATTIVA = 1) ST) POS,
          T_MCRE0_APP_ALL_DATA PARTITION (CCP_P1) AD,
          T_MCRE0_APP_UTENTI U,
          V_MCRE0_DENORM_STR_ORG O
    WHERE     POS.COD_ABI = AD.COD_ABI_CARTOLARIZZATO
          AND POS.COD_NDG = AD.COD_NDG
          AND AD.COD_ABI_CARTOLARIZZATO = O.COD_ABI_ISTITUTO_FI(+)
          AND AD.COD_FILIALE = O.COD_STRUTTURA_COMPETENTE_FI(+)
          AND AD.TODAY_FLG(+) = '1'
          AND AD.ID_UTENTE = U.ID_UTENTE(+);
