/* Formatted on 21/07/2014 18:38:17 (QP5 v5.227.12220.39754) */
CREATE OR REPLACE FORCE VIEW MCRE_OWN.V_MCRE0_WEB_DATA
(
   TODAY_FLG,
   FLG_ACTIVE,
   FLG_SOURCE,
   FLG_BLOCCO,
   ID_DPER,
   ID_DPERFG,
   ID_DPERMO,
   COD_SNDG,
   DESC_NOME_CONTROPARTE,
   COD_NDG,
   COD_ABI_CARTOLARIZZATO,
   COD_ABI_ISTITUTO,
   DESC_ISTITUTO,
   DESC_BREVE,
   FLG_TARGET,
   FLG_CARTOLARIZZATO,
   DTA_ABI_ELAB,
   COD_GRUPPO_ECONOMICO,
   DESC_GRUPPO_ECONOMICO,
   COD_GRUPPO_LEGAME,
   FLG_GRUPPO_ECONOMICO,
   FLG_GRUPPO_LEGAME,
   FLG_SINGOLO,
   FLG_CONDIVISO,
   FLG_SOMMA,
   FLG_OUTSOURCING,
   COD_FILIALE,
   COD_STRUTTURA_COMPETENTE,
   COD_STATO,
   DTA_DECORRENZA_STATO,
   DTA_SCADENZA_STATO,
   COD_STATO_PRECEDENTE,
   DTA_DECORRENZA_STATO_PRE,
   DTA_INTERCETTAMENTO,
   COD_TIPO_INGRESSO,
   COD_CAUSALE_INGRESSO,
   COD_PERCORSO,
   COD_PROCESSO,
   DTA_PROCESSO,
   COD_PROCESSO_PRE,
   COD_MACROSTATO,
   DTA_DEC_MACROSTATO,
   COD_RAMO_CALCOLATO,
   COD_COMPARTO_CALCOLATO,
   DTA_COMPARTO_CALCOLATO,
   COD_COMPARTO_CALCOLATO_PRE,
   COD_GRUPPO_SUPER,
   COD_GRUPPO_SUPER_OLD,
   FLG_RIPORTAFOGLIATO,
   DTA_LAST_RIPORTAF,
   FLG_PROPOSTO_ASSEGNATO,
   DTA_UTENTE_ASSEGNATO,
   COD_COMPARTO_ASSEGNATO,
   ID_UTENTE,
   ID_UTENTE_PRE,
   COD_SERVIZIO,
   DTA_SERVIZIO,
   ID_STATO_POSIZIONE,
   COD_CLIENTE_ESTESO,
   ID_CLIENTE_ESTESO,
   DESC_ANAG_GESTORE_MKT,
   COD_GESTORE_MKT,
   COD_TIPO_PORTAFOGLIO,
   FLG_GESTIONE_ESTERNA,
   VAL_PERC_DECURTAZIONE,
   COD_COMPARTO_HOST,
   ID_TRANSIZIONE,
   COD_RAMO_HOST,
   COD_MATR_RISCHIO,
   COD_UO_RISCHIO,
   COD_DISP_RISCHIO,
   DTA_INS,
   DTA_UPD,
   COD_OPERATORE_INS_UPD,
   COD_MATR_ASSEGNATORE,
   COD_SEZIONE_PREASSEGNATA,
   ID_UTENTE_PREASSEGNATO,
   COD_COMPARTO_PREASSEGNATO,
   COD_PROCESSO_PREASSEGNATO,
   FLG_STATO_GB,
   COD_FILIALE_GB,
   COD_PROCESSO_CALCOLATO_GB,
   COD_MACROSTATO_PROPOSTO_GB,
   DTA_INS_GB
)
AS
   SELECT DISTINCT TODAY_FLG,
                   FLG_ACTIVE,
                   FLG_SOURCE,
                   FLG_BLOCCO,
                   ID_DPER,
                   ID_DPERFG,
                   ID_DPERMO,
                   COD_SNDG,
                   DESC_NOME_CONTROPARTE,
                   COD_NDG,
                   COD_ABI_CARTOLARIZZATO,
                   COD_ABI_ISTITUTO,
                   DESC_ISTITUTO,
                   DESC_BREVE,
                   FLG_TARGET,
                   FLG_CARTOLARIZZATO,
                   DTA_ABI_ELAB,
                   COD_GRUPPO_ECONOMICO,
                   DESC_GRUPPO_ECONOMICO,
                   COD_GRUPPO_LEGAME,
                   FLG_GRUPPO_ECONOMICO,
                   FLG_GRUPPO_LEGAME,
                   FLG_SINGOLO,
                   FLG_CONDIVISO,
                   FLG_SOMMA,
                   FLG_OUTSOURCING,
                   COD_FILIALE,
                   COD_STRUTTURA_COMPETENTE,
                   COD_STATO,
                   DTA_DECORRENZA_STATO,
                   DTA_SCADENZA_STATO,
                   COD_STATO_PRECEDENTE,
                   DTA_DECORRENZA_STATO_PRE,
                   DTA_INTERCETTAMENTO,
                   COD_TIPO_INGRESSO,
                   COD_CAUSALE_INGRESSO,
                   COD_PERCORSO,
                   COD_PROCESSO,
                   DTA_PROCESSO,
                   COD_PROCESSO_PRE,
                   COD_MACROSTATO,
                   DTA_DEC_MACROSTATO,
                   COD_RAMO_CALCOLATO,
                   COD_COMPARTO_CALCOLATO,
                   DTA_COMPARTO_CALCOLATO,
                   COD_COMPARTO_CALCOLATO_PRE,
                   COD_GRUPPO_SUPER,
                   COD_GRUPPO_SUPER_OLD,
                   FLG_RIPORTAFOGLIATO,
                   DTA_LAST_RIPORTAF,
                   FLG_PROPOSTO_ASSEGNATO,
                   DTA_UTENTE_ASSEGNATO,
                   COD_COMPARTO_ASSEGNATO,
                   ID_UTENTE,
                   ID_UTENTE_PRE,
                   cod_servizio,
                   dta_servizio,
                   ID_STATO_POSIZIONE,
                   COD_CLIENTE_ESTESO,
                   ID_CLIENTE_ESTESO,
                   DESC_ANAG_GESTORE_MKT,
                   COD_GESTORE_MKT,
                   COD_TIPO_PORTAFOGLIO,
                   FLG_GESTIONE_ESTERNA,
                   VAL_PERC_DECURTAZIONE,
                   COD_COMPARTO_HOST,
                   ID_TRANSIZIONE,
                   COD_RAMO_HOST,
                   COD_MATR_RISCHIO,
                   COD_UO_RISCHIO,
                   COD_DISP_RISCHIO,
                   DTA_INS,
                   DTA_UPD,
                   COD_OPERATORE_INS_UPD,
                   COD_MATR_ASSEGNATORE,
                   COD_SEZIONE_PREASSEGNATA,
                   ID_UTENTE_PREASSEGNATO,
                   COD_COMPARTO_PREASSEGNATO,
                   COD_PROCESSO_PREASSEGNATO,
                   FLG_STATO_GB,
                   COD_FILIALE_GB,
                   COD_PROCESSO_CALCOLATO_GB,
                   COD_MACROSTATO_PROPOSTO_GB,
                   DTA_INS_GB
     FROM (SELECT TODAY_FLG,
                  '1' FLG_ACTIVE,
                  FLG_SOURCE,
                  FLG_BLOCCO,
                  ID_DPER,
                  ID_DPERFG,
                  ID_DPERMO,
                  COD_SNDG,
                  DESC_NOME_CONTROPARTE,
                  COD_NDG,
                  COD_ABI_CARTOLARIZZATO,
                  COD_ABI_ISTITUTO,
                  DESC_ISTITUTO,
                  DESC_BREVE,
                  FLG_TARGET,
                  FLG_CARTOLARIZZATO,
                  DTA_ABI_ELAB,
                  COD_GRUPPO_ECONOMICO,
                  DESC_GRUPPO_ECONOMICO,
                  COD_GRUPPO_LEGAME,
                  FLG_GRUPPO_ECONOMICO,
                  FLG_GRUPPO_LEGAME,
                  FLG_SINGOLO,
                  FLG_CONDIVISO,
                  FLG_SOMMA,
                  FLG_OUTSOURCING,
                  COD_FILIALE,
                  COD_STRUTTURA_COMPETENTE,
                  COD_STATO,
                  DTA_DECORRENZA_STATO,
                  DTA_SCADENZA_STATO,
                  COD_STATO_PRECEDENTE,
                  DTA_DECORRENZA_STATO_PRE,
                  DTA_INTERCETTAMENTO,
                  COD_TIPO_INGRESSO,
                  COD_CAUSALE_INGRESSO,
                  COD_PERCORSO,
                  COD_PROCESSO,
                  DTA_PROCESSO,
                  COD_PROCESSO_PRE,
                  COD_MACROSTATO,
                  DTA_DEC_MACROSTATO,
                  COD_RAMO_CALCOLATO,
                  COD_COMPARTO_CALCOLATO,
                  DTA_COMPARTO_CALCOLATO,
                  COD_COMPARTO_CALCOLATO_PRE,
                  COD_GRUPPO_SUPER,
                  COD_GRUPPO_SUPER_OLD,
                  FLG_RIPORTAFOGLIATO,
                  DTA_LAST_RIPORTAF,
                  FLG_PROPOSTO_ASSEGNATO,
                  DTA_UTENTE_ASSEGNATO,
                  COD_COMPARTO_ASSEGNATO,
                  ID_UTENTE,
                  ID_UTENTE_PRE,
                  CASE
                     WHEN w.cod_comparto_calcolato = '011901'
                     THEN
                        --                              (SELECT cod_servizio
                        --                                 FROM t_mcre0_app_comparti
                        --                                WHERE cod_comparto =
                        --                                         NVL (w.cod_comparto_assegnato,
                        --                                              w.cod_comparto_calcolato))
                        c.cod_servizio
                     ELSE
                        w.cod_servizio
                  END
                     --                     ELSE
                     --                        NULL
                     --                  END
                     cod_servizio,
                  --                  CASE
                  --                     WHEN w.cod_macrostato IN
                  --                             ('PT', 'RIO', 'IN', 'SC', 'RS', 'SO')
                  --                     THEN
                  CASE
                     WHEN w.cod_comparto_calcolato = '011901'
                     THEN
                        CASE
                           WHEN w.cod_macrostato IN ('IN', 'RS')
                           THEN
                              NVL (
                                 MIN (
                                    CASE
                                       WHEN w.cod_stato IN ('IN', 'RS')
                                       THEN
                                          w.dta_servizio
                                       ELSE
                                          NULL
                                    END)
                                 OVER (PARTITION BY w.cod_sndg),
                                 SYSDATE)
                           WHEN w.cod_macrostato IN ('RIO', 'SC', 'SO')
                           THEN
                              NVL (w.dta_servizio, SYSDATE)
                           ELSE
                              NULL
                        END
                     ELSE
                        w.dta_servizio
                  END
                     --                     ELSE
                     --                        NULL
                     --                  END
                     dta_servizio,
                  ID_STATO_POSIZIONE,
                  COD_CLIENTE_ESTESO,
                  ID_CLIENTE_ESTESO,
                  DESC_ANAG_GESTORE_MKT,
                  COD_GESTORE_MKT,
                  COD_TIPO_PORTAFOGLIO,
                  FLG_GESTIONE_ESTERNA,
                  VAL_PERC_DECURTAZIONE,
                  COD_COMPARTO_HOST,
                  ID_TRANSIZIONE,
                  COD_RAMO_HOST,
                  COD_MATR_RISCHIO,
                  COD_UO_RISCHIO,
                  COD_DISP_RISCHIO,
                  DTA_INS,
                  DTA_UPD,
                  COD_OPERATORE_INS_UPD,
                  COD_MATR_ASSEGNATORE,
                  COD_SEZIONE_PREASSEGNATA,
                  ID_UTENTE_PREASSEGNATO,
                  COD_COMPARTO_PREASSEGNATO,
                  COD_PROCESSO_PREASSEGNATO,
                  FLG_STATO_GB,
                  COD_FILIALE_GB,
                  COD_PROCESSO_CALCOLATO_GB,
                  COD_MACROSTATO_PROPOSTO_GB,
                  DTA_INS_GB
             FROM mcre_own.TTMCRE0_WEB_DATA_5 w, t_mcre0_app_comparti c
            WHERE (    w.flg_active(+) = '1'
                   AND w.cod_macrostato IN
                          ('PT', 'RIO', 'IN', 'SC', 'RS', 'SO')
                   AND c.cod_comparto =
                          NVL (w.cod_comparto_assegnato,
                               w.cod_comparto_calcolato))
           UNION ALL
           SELECT TODAY_FLG,
                  '1' FLG_ACTIVE,
                  FLG_SOURCE,
                  FLG_BLOCCO,
                  ID_DPER,
                  ID_DPERFG,
                  ID_DPERMO,
                  COD_SNDG,
                  DESC_NOME_CONTROPARTE,
                  COD_NDG,
                  COD_ABI_CARTOLARIZZATO,
                  COD_ABI_ISTITUTO,
                  DESC_ISTITUTO,
                  DESC_BREVE,
                  FLG_TARGET,
                  FLG_CARTOLARIZZATO,
                  DTA_ABI_ELAB,
                  COD_GRUPPO_ECONOMICO,
                  DESC_GRUPPO_ECONOMICO,
                  COD_GRUPPO_LEGAME,
                  FLG_GRUPPO_ECONOMICO,
                  FLG_GRUPPO_LEGAME,
                  FLG_SINGOLO,
                  FLG_CONDIVISO,
                  FLG_SOMMA,
                  FLG_OUTSOURCING,
                  COD_FILIALE,
                  COD_STRUTTURA_COMPETENTE,
                  COD_STATO,
                  DTA_DECORRENZA_STATO,
                  DTA_SCADENZA_STATO,
                  COD_STATO_PRECEDENTE,
                  DTA_DECORRENZA_STATO_PRE,
                  DTA_INTERCETTAMENTO,
                  COD_TIPO_INGRESSO,
                  COD_CAUSALE_INGRESSO,
                  COD_PERCORSO,
                  COD_PROCESSO,
                  DTA_PROCESSO,
                  COD_PROCESSO_PRE,
                  COD_MACROSTATO,
                  DTA_DEC_MACROSTATO,
                  COD_RAMO_CALCOLATO,
                  COD_COMPARTO_CALCOLATO,
                  DTA_COMPARTO_CALCOLATO,
                  COD_COMPARTO_CALCOLATO_PRE,
                  COD_GRUPPO_SUPER,
                  COD_GRUPPO_SUPER_OLD,
                  FLG_RIPORTAFOGLIATO,
                  DTA_LAST_RIPORTAF,
                  FLG_PROPOSTO_ASSEGNATO,
                  DTA_UTENTE_ASSEGNATO,
                  COD_COMPARTO_ASSEGNATO,
                  ID_UTENTE,
                  ID_UTENTE_PRE,
                  NULL cod_servizio,
                  NULL dta_servizio,
                  ID_STATO_POSIZIONE,
                  COD_CLIENTE_ESTESO,
                  ID_CLIENTE_ESTESO,
                  DESC_ANAG_GESTORE_MKT,
                  COD_GESTORE_MKT,
                  COD_TIPO_PORTAFOGLIO,
                  FLG_GESTIONE_ESTERNA,
                  VAL_PERC_DECURTAZIONE,
                  COD_COMPARTO_HOST,
                  ID_TRANSIZIONE,
                  COD_RAMO_HOST,
                  COD_MATR_RISCHIO,
                  COD_UO_RISCHIO,
                  COD_DISP_RISCHIO,
                  DTA_INS,
                  DTA_UPD,
                  COD_OPERATORE_INS_UPD,
                  COD_MATR_ASSEGNATORE,
                  COD_SEZIONE_PREASSEGNATA,
                  ID_UTENTE_PREASSEGNATO,
                  COD_COMPARTO_PREASSEGNATO,
                  COD_PROCESSO_PREASSEGNATO,
                  FLG_STATO_GB,
                  COD_FILIALE_GB,
                  COD_PROCESSO_CALCOLATO_GB,
                  COD_MACROSTATO_PROPOSTO_GB,
                  DTA_INS_GB
             FROM mcre_own.TTMCRE0_WEB_DATA_5 w
            WHERE    (    w.cod_macrostato NOT IN
                             ('PT', 'RIO', 'IN', 'SC', 'RS', 'SO')
                      AND w.cod_macrostato IS NOT NULL)
                  OR (w.cod_macrostato IS NULL));
