/* Formatted on 21/07/2014 18:40:34 (QP5 v5.227.12220.39754) */
CREATE OR REPLACE FORCE VIEW MCRE_OWN.V_MCREI_APP_PARERI_HST
(
   ID_DPER,
   COD_ABI,
   ID_PARERE,
   COD_PROTOCOLLO_DELIBERA,
   COD_PROGR_PARERE,
   DESC_PARERE,
   COD_TIPO_PAR,
   COD_UO,
   COD_UTENTE,
   DTA_INS_PARERE,
   COD_NDG,
   COD_SNDG,
   VAL_ANNO_PROPOSTA,
   VAL_PROGR_PROPOSTA,
   FLG_ATTIVA,
   DTA_INS,
   DTA_UPD,
   COD_OPERATORE_INS_UPD,
   FLG_PARERE_CAPOGRUPPO,
   COD_PROTOCOLLO_PACCHETTO,
   FLG_DIFFORME,
   DESC_PARERE_ESTESO,
   FLG_DELETE
)
AS
   SELECT id_dper,
          cod_abi,
          id_parere,
          cod_protocollo_delibera,
          cod_progr_parere,
          desc_parere,
          cod_tipo_par,
          cod_uo,
          cod_utente,
          dta_ins_parere,
          cod_ndg,
          cod_sndg,
          val_anno_proposta,
          val_progr_proposta,
          flg_attiva,
          dta_ins,
          dta_upd,
          cod_operatore_ins_upd,
          TO_CHAR (NULL) flg_parere_capogruppo,
          cod_protocollo_pacchetto,
          TO_CHAR (NULL) flg_difforme,
          TO_CHAR (NULL) desc_parere_esteso,
          TO_CHAR (NULL) flg_delete
     FROM t_mcrei_hst_pareri;
