/* Formatted on 21/07/2014 18:45:26 (QP5 v5.227.12220.39754) */
CREATE OR REPLACE FORCE VIEW MCRE_OWN.VNMCRE0_APP_HP_EXCEL
(
   COD_COMPARTO,
   DESC_COMPARTO,
   VAL_BANCA,
   VAL_DIREZIONE,
   VAL_REGIONE,
   COD_REGIONE,
   VAL_AEREA,
   COD_AREA,
   COD_FILIALE,
   COD_ABI_ISTITUTO,
   COD_ABI_CARTOLARIZZATO,
   COD_NDG,
   COD_SNDG,
   DESC_NOME_CONTROPARTE,
   COD_GE,
   DESC_GE,
   COD_PROCESSO,
   COD_STATO,
   DTA_DECORRENZA_STATO,
   DTA_SCADENZA_STATO,
   COD_STATO_RISTRUTTURATO,
   DTA_DECORRENZA_STATO_RIS,
   VAL_TOT_UTILIZZO,
   VAL_TOT_ACCORDATO,
   VAL_TOT_UTI_CASSA,
   VAL_TOT_UTI_FIRMA,
   VAL_TOT_ACC_CASSA,
   VAL_TOT_ACC_FIRMA,
   VAL_MAU,
   COGNOME,
   NOME,
   DTA_UTENTE_ASSEGNATO,
   DTA_ESTRAZIONE,
   ID_UTENTE,
   ID_REFERENTE,
   FLG_OUTSOURCING,
   VAL_GG_PT
)
AS
   SELECT                                   -- vg  26/01/2011 Codice e desc ge
          -- mm 02/02/2011 dta_estrazione a sysdate, cod_ristrutt. a '-'
          -- vg  14/03/2011 GG di PT
          cod_comparto,
          desc_comparto,
          desc_istituto val_banca,
          desc_struttura_competente_dc val_direzione,
          desc_struttura_competente_rg val_regione,
          cod_struttura_competente_rg cod_regione,
          desc_struttura_competente_ar val_aerea,
          cod_struttura_competente_ar cod_area,
          cod_filiale,
          cod_abi_istituto,
          cod_abi_cartolarizzato,
          cod_ndg,
          cod_sndg,
          desc_nome_controparte,
          cod_gruppo_economico cod_ge,
          desc_gruppo_economico desc_ge,
          cod_processo,
          cod_stato,
          dta_decorrenza_stato,
          dta_scadenza_stato,
          '-' cod_stato_ristrutturato,
          TO_DATE (NULL) dta_decorrenza_stato_ris,
          SCSB_UTI_TOT VAL_TOT_UTILIZZO,
          SCSB_ACC_TOT VAL_TOT_ACCORDATO,
          SCSB_UTI_CASSA VAL_TOT_UTI_CASSA,
          SCSB_UTI_FIRMA VAL_TOT_UTI_FIRMA,
          SCSB_ACC_CASSA VAL_TOT_ACC_CASSA,
          SCSB_ACC_FIRMA VAL_TOT_ACC_FIRMA,
          GB_VAL_MAU VAL_MAU,
          cognome,
          nome,
          dta_utente_assegnato,
          SYSDATE dta_estrazione,
          id_utente,
          id_referente,
          flg_outsourcing,
          DECODE (cod_stato,
                  'PT', TRUNC (SYSDATE) - dta_decorrenza_stato,
                  TO_NUMBER (NULL))
             val_gg_pt
     FROM V_MCRE0_APP_UPD_FIELDS p
    WHERE FLG_STATO_CHK = '1';
