/* Formatted on 21/07/2014 18:46:14 (QP5 v5.227.12220.39754) */
CREATE OR REPLACE FORCE VIEW MCRE_OWN.VOMCRE0_APP_POS_USCITE_RIPORT
(
   VAL_ALERT,
   VAL_ORDINE_COLORE,
   DTA_INS_ALERT,
   COD_SNDG,
   COD_ABI_CARTOLARIZZATO,
   COD_ABI_ISTITUTO,
   COD_GRUPPO_ECONOMICO,
   VAL_ANA_GRE,
   COD_STRUTTURA_COMPETENTE_DC,
   DESC_STRUTTURA_COMPETENTE_DC,
   COD_STRUTTURA_COMPETENTE_RG,
   DESC_STRUTTURA_COMPETENTE_RG,
   COD_STRUTTURA_COMPETENTE_AR,
   DESC_STRUTTURA_COMPETENTE_AR,
   COD_STRUTTURA_COMPETENTE_FI,
   DESC_STRUTTURA_COMPETENTE_FI,
   COD_PROCESSO,
   COD_STATO,
   DTA_DECORRENZA_STATO,
   DTA_SCADENZA_STATO,
   ID_UTENTE,
   DTA_UTENTE_ASSEGNATO,
   DESC_NOME,
   DESC_COGNOME,
   DTA_LAST_RIPORTAF,
   ID_UTENTE_PRE
)
AS
   SELECT ALERT_10 VAL_ALERT,
          (SELECT DECODE (
                     ALERT_10,
                     'V', VAL_VERDE,
                     DECODE (ALERT_10,
                             'A', VAL_ARANCIO,
                             DECODE (ALERT_10, 'R', VAL_ROSSO, NULL)))
             FROM T_MCRE0_APP_ALERT
            WHERE ID_ALERT = 10)
             VAL_ORDINE_COLORE,
          DTA_INS_10 DTA_INS_ALERT,
          A.COD_SNDG,
          A.COD_ABI_CARTOLARIZZATO,
          A.COD_ABI_ISTITUTO,
          X.COD_GRUPPO_ECONOMICO,
          GE.VAL_ANA_GRE,
          S.COD_STRUTTURA_COMPETENTE_DC,
          S.DESC_STRUTTURA_COMPETENTE_DC,
          S.COD_STRUTTURA_COMPETENTE_RG,
          S.DESC_STRUTTURA_COMPETENTE_RG,
          S.COD_STRUTTURA_COMPETENTE_AR,
          S.DESC_STRUTTURA_COMPETENTE_AR,
          S.COD_STRUTTURA_COMPETENTE_FI,
          S.DESC_STRUTTURA_COMPETENTE_FI,
          X.COD_PROCESSO,
          X.COD_STATO,
          X.DTA_DECORRENZA_STATO,
          X.DTA_SCADENZA_STATO,
          X.ID_UTENTE,
          X.DTA_UTENTE_ASSEGNATO,
          U.NOME DESC_NOME,
          U.COGNOME DESC_COGNOME,
          X.DTA_LAST_RIPORTAF,
          A.ID_UTENTE_PRE
     FROM V_MCRE0_APP_ALERT_POS A,
          MV_MCRE0_APP_ISTITUTI I,
          T_MCRE0_APP_ANAGRAFICA_GRUPPO G,
          MV_MCRE0_APP_UPD_FIELD X,
          T_MCRE0_APP_ANAGR_GRE GE,
          MV_MCRE0_DENORM_STR_ORG S,
          T_MCRE0_APP_UTENTI U
    WHERE     ALERT_10 IS NOT NULL
          AND X.COD_ABI_CARTOLARIZZATO = A.COD_ABI_CARTOLARIZZATO
          AND X.COD_NDG = A.COD_NDG
          AND X.COD_ABI_ISTITUTO = I.COD_ABI(+)
          AND X.COD_SNDG = G.COD_SNDG(+)
          AND X.COD_GRUPPO_ECONOMICO = GE.COD_GRE(+)
          AND X.COD_ABI_ISTITUTO = S.COD_ABI_ISTITUTO_FI(+)
          AND X.COD_FILIALE = S.COD_STRUTTURA_COMPETENTE_FI(+)
          AND X.ID_UTENTE = U.ID_UTENTE(+);
