/* Formatted on 21/07/2014 18:45:39 (QP5 v5.227.12220.39754) */
CREATE OR REPLACE FORCE VIEW MCRE_OWN.VOMCRE0_APP_AGENDA
(
   ID,
   ID_UTENTE,
   COD_NDG,
   COD_ABI_CARTOLARIZZATO,
   DTA_INIZIO_APPUNTAMENTO,
   DESCRIZIONE,
   DTA_FINE_APPUNTAMENTO,
   DESC_NOME_CONTROPARTE,
   COD_GRUPPO_ECONOMICO,
   VAL_ANA_GRE
)
AS
   SELECT                                          -- v1 VG 21/04/2011 : Nuova
         A."ID",
          A."ID_UTENTE",
          A."COD_NDG",
          A."COD_ABI_CARTOLARIZZATO",
          A."DTA_INIZIO_APPUNTAMENTO",
          A."DESCRIZIONE",
          A."DTA_FINE_APPUNTAMENTO",
          G.DESC_NOME_CONTROPARTE,
          F.COD_GRUPPO_ECONOMICO,
          GE.VAL_ANA_GRE
     FROM T_MCRE0_APP_AGENDA A,
          T_MCRE0_APP_FILE_GUIDA F,
          T_MCRE0_APP_ANAGRAFICA_GRUPPO G,
          T_MCRE0_APP_ANAGR_GRE GE
    WHERE     A.COD_ABI_CARTOLARIZZATO = F.COD_ABI_CARTOLARIZZATO(+)
          AND A.COD_NDG = F.COD_NDG(+)
          AND F.COD_SNDG = G.COD_SNDG(+)
          AND F.COD_GRUPPO_ECONOMICO = GE.COD_GRE(+);
