/* Formatted on 21/07/2014 18:46:40 (QP5 v5.227.12220.39754) */
CREATE OR REPLACE FORCE VIEW MCRE_OWN.VOMCRE0_APP_RIO_SINTESI_POS
(
   COD_ABI_CARTOLARIZZATO,
   COD_NDG,
   COD_COMPARTO,
   ID_UTENTE,
   DTA_PRESA_IN_CARICO,
   SCSB_ACC_TOT,
   SCSB_UTI_TOT,
   SCGB_ACC_TOT,
   SCGB_UTI_TOT,
   SB_QI,
   GB_QI,
   VAL_PD_ONLINE,
   DTA_RIF_PD_ONLINE,
   VAL_RATING_ONLINE,
   VAL_PD_MONIT_ONLINE,
   DTA_RIF_PD_MONIT_ONLINE,
   VAL_RATING_MONIT_ONLINE,
   DTA_RIF_RATING_MONIT_ONLINE,
   VAL_IRIS,
   VAL_LGD,
   VAL_EAD,
   VAL_PA,
   VAL_STRATEGIA_CREDITIZIA
)
AS
   SELECT                          -- v1.1 aggiunti iris e strategia cred. pef
                                                  -- v2 17/06/2011 VG: New PCR
         X.COD_ABI_CARTOLARIZZATO,
         X.COD_NDG,
         X.COD_COMPARTO,
         X.ID_UTENTE,
         X.DTA_UTENTE_ASSEGNATO DTA_PRESA_IN_CARICO,
         P.SCSB_ACC_TOT,
         P.SCSB_UTI_TOT,
         P.SCGB_ACC_CASSA + P.SCGB_ACC_FIRMA SCGB_ACC_TOT,
         P.SCGB_UTI_CASSA + P.SCGB_UTI_FIRMA SCGB_UTI_TOT,
         NULL SB_QI,
         NULL GB_QI,
         A.VAL_PD_ONLINE,
         A.DTA_RIF_PD_ONLINE,
         A.VAL_RATING_ONLINE,
         I.VAL_PD_MONITORAGGIO VAL_PD_MONIT_ONLINE,
         I.DTA_PD_MONITORAGGIO DTA_RIF_PD_MONIT_ONLINE,
         I.VAL_RATING_MONITORAGGIO VAL_RATING_MONIT_ONLINE,
         I.DTA_PD_MONITORAGGIO DTA_RIF_RATING_MONIT_ONLINE,
         I.VAL_IRIS_CLI VAL_IRIS,
         I.VAL_LGD,
         I.VAL_EAD,
         I.VAL_PA,
         E.COD_STRATEGIA_CRZ VAL_STRATEGIA_CREDITIZIA
    FROM MV_MCRE0_APP_UPD_FIELD X,
         T_MCRE0_APP_PCR P,
         T_MCRE0_APP_ANAGRAFICA_GRUPPO A,
         T_MCRE0_APP_IRIS I,
         T_MCRE0_APP_PEF E
   WHERE     X.COD_MACROSTATO = 'RIO'
         AND X.ID_UTENTE IS NOT NULL
         AND X.COD_ABI_CARTOLARIZZATO = P.COD_ABI_CARTOLARIZZATO(+)
         AND X.COD_NDG = P.COD_NDG(+)
         AND X.COD_SNDG = A.COD_SNDG(+)
         AND X.COD_SNDG = I.COD_SNDG(+)
         AND X.COD_ABI_ISTITUTO = E.COD_ABI_ISTITUTO(+)
         AND X.COD_NDG = E.COD_NDG(+);
